# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms\bopeMainForm.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dwcBopeMainForm(object):
    def setupUi(self, dwcBopeMainForm):
        dwcBopeMainForm.setObjectName("dwcBopeMainForm")
        dwcBopeMainForm.resize(518, 625)
        dwcBopeMainForm.setMinimumSize(QtCore.QSize(518, 565))
        self.dwcBopeMain = QtWidgets.QWidget()
        self.dwcBopeMain.setObjectName("dwcBopeMain")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.dwcBopeMain)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.scrollArea = QtWidgets.QScrollArea(self.dwcBopeMain)
        self.scrollArea.setMinimumSize(QtCore.QSize(500, 500))
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -202, 486, 768))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setContentsMargins(0, 1, 0, 1)
        self.horizontalLayout_12.setSpacing(2)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.btnFiltreCartoManuel = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnFiltreCartoManuel.setEnabled(False)
        self.btnFiltreCartoManuel.setMinimumSize(QtCore.QSize(120, 30))
        self.btnFiltreCartoManuel.setObjectName("btnFiltreCartoManuel")
        self.horizontalLayout_12.addWidget(self.btnFiltreCartoManuel)
        self.chkFiltreCartoAuto = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.chkFiltreCartoAuto.setMinimumSize(QtCore.QSize(130, 0))
        self.chkFiltreCartoAuto.setObjectName("chkFiltreCartoAuto")
        self.horizontalLayout_12.addWidget(self.chkFiltreCartoAuto)
        self.btnFiltreAttributaire = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnFiltreAttributaire.setMinimumSize(QtCore.QSize(97, 30))
        self.btnFiltreAttributaire.setObjectName("btnFiltreAttributaire")
        self.horizontalLayout_12.addWidget(self.btnFiltreAttributaire)
        self.btnDeleteFiltrage = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnDeleteFiltrage.setEnabled(False)
        self.btnDeleteFiltrage.setMinimumSize(QtCore.QSize(110, 30))
        self.btnDeleteFiltrage.setObjectName("btnDeleteFiltrage")
        self.horizontalLayout_12.addWidget(self.btnDeleteFiltrage)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.grp_bail = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.grp_bail.setMinimumSize(QtCore.QSize(0, 0))
        self.grp_bail.setObjectName("grp_bail")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.grp_bail)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label = QtWidgets.QLabel(self.grp_bail)
        self.label.setObjectName("label")
        self.horizontalLayout_26.addWidget(self.label)
        self.leBopeId = QtWidgets.QLineEdit(self.grp_bail)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leBopeId.sizePolicy().hasHeightForWidth())
        self.leBopeId.setSizePolicy(sizePolicy)
        self.leBopeId.setMaximumSize(QtCore.QSize(50, 16777215))
        self.leBopeId.setAlignment(QtCore.Qt.AlignCenter)
        self.leBopeId.setObjectName("leBopeId")
        self.horizontalLayout_26.addWidget(self.leBopeId)
        self.lblEcheance = QtWidgets.QLabel(self.grp_bail)
        self.lblEcheance.setEnabled(True)
        self.lblEcheance.setMinimumSize(QtCore.QSize(350, 20))
        self.lblEcheance.setStyleSheet("color: rgb(230, 0, 38);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.lblEcheance.setFrameShape(QtWidgets.QFrame.Box)
        self.lblEcheance.setAlignment(QtCore.Qt.AlignCenter)
        self.lblEcheance.setObjectName("lblEcheance")
        self.horizontalLayout_26.addWidget(self.lblEcheance)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout_26)
        self.grp_localisation = QtWidgets.QGroupBox(self.grp_bail)
        self.grp_localisation.setObjectName("grp_localisation")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.grp_localisation)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.lbl_parcelle_2 = QtWidgets.QLabel(self.grp_localisation)
        self.lbl_parcelle_2.setMinimumSize(QtCore.QSize(50, 0))
        self.lbl_parcelle_2.setObjectName("lbl_parcelle_2")
        self.horizontalLayout_14.addWidget(self.lbl_parcelle_2)
        self.cmbAappma = QtWidgets.QComboBox(self.grp_localisation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbAappma.sizePolicy().hasHeightForWidth())
        self.cmbAappma.setSizePolicy(sizePolicy)
        self.cmbAappma.setObjectName("cmbAappma")
        self.horizontalLayout_14.addWidget(self.cmbAappma)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem1)
        self.verticalLayout_7.addLayout(self.horizontalLayout_14)
        self.lbl_parcelles = QtWidgets.QLabel(self.grp_localisation)
        self.lbl_parcelles.setObjectName("lbl_parcelles")
        self.verticalLayout_7.addWidget(self.lbl_parcelles)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tbvParcelle = QtWidgets.QTableView(self.grp_localisation)
        self.tbvParcelle.setMinimumSize(QtCore.QSize(360, 100))
        self.tbvParcelle.setObjectName("tbvParcelle")
        self.horizontalLayout.addWidget(self.tbvParcelle)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.btnAjoutParcelle = QtWidgets.QPushButton(self.grp_localisation)
        self.btnAjoutParcelle.setMaximumSize(QtCore.QSize(25, 16777215))
        self.btnAjoutParcelle.setObjectName("btnAjoutParcelle")
        self.verticalLayout_12.addWidget(self.btnAjoutParcelle)
        self.btnSuppParcelle = QtWidgets.QPushButton(self.grp_localisation)
        self.btnSuppParcelle.setMaximumSize(QtCore.QSize(25, 16777215))
        self.btnSuppParcelle.setObjectName("btnSuppParcelle")
        self.verticalLayout_12.addWidget(self.btnSuppParcelle)
        self.horizontalLayout.addLayout(self.verticalLayout_12)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.btnSelectParcelle = QtWidgets.QPushButton(self.grp_localisation)
        self.btnSelectParcelle.setMaximumSize(QtCore.QSize(25, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/icons/select.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSelectParcelle.setIcon(icon)
        self.btnSelectParcelle.setObjectName("btnSelectParcelle")
        self.verticalLayout_13.addWidget(self.btnSelectParcelle)
        self.btnZoomParcelle = QtWidgets.QPushButton(self.grp_localisation)
        self.btnZoomParcelle.setMaximumSize(QtCore.QSize(25, 16777215))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/icons/zoom.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnZoomParcelle.setIcon(icon1)
        self.btnZoomParcelle.setObjectName("btnZoomParcelle")
        self.verticalLayout_13.addWidget(self.btnZoomParcelle)
        self.horizontalLayout.addLayout(self.verticalLayout_13)
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        self.lbl_riviere = QtWidgets.QLabel(self.grp_localisation)
        self.lbl_riviere.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_riviere.setObjectName("lbl_riviere")
        self.verticalLayout_7.addWidget(self.lbl_riviere)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.tbvRiviere = QtWidgets.QTableView(self.grp_localisation)
        self.tbvRiviere.setObjectName("tbvRiviere")
        self.horizontalLayout_7.addWidget(self.tbvRiviere)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.btnAjoutRiviere = QtWidgets.QPushButton(self.grp_localisation)
        self.btnAjoutRiviere.setMaximumSize(QtCore.QSize(25, 16777215))
        self.btnAjoutRiviere.setObjectName("btnAjoutRiviere")
        self.verticalLayout_9.addWidget(self.btnAjoutRiviere)
        self.btnSuppRiviere = QtWidgets.QPushButton(self.grp_localisation)
        self.btnSuppRiviere.setMaximumSize(QtCore.QSize(25, 16777215))
        self.btnSuppRiviere.setObjectName("btnSuppRiviere")
        self.verticalLayout_9.addWidget(self.btnSuppRiviere)
        self.horizontalLayout_7.addLayout(self.verticalLayout_9)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        self.verticalLayout_3.addWidget(self.grp_localisation)
        self.grp_description = QtWidgets.QGroupBox(self.grp_bail)
        self.grp_description.setMinimumSize(QtCore.QSize(0, 0))
        self.grp_description.setObjectName("grp_description")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.grp_description)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.chkPossession = QtWidgets.QCheckBox(self.grp_description)
        self.chkPossession.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.chkPossession.setObjectName("chkPossession")
        self.horizontalLayout_10.addWidget(self.chkPossession)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.chkOrigine = QtWidgets.QCheckBox(self.grp_description)
        self.chkOrigine.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.chkOrigine.setObjectName("chkOrigine")
        self.horizontalLayout_6.addWidget(self.chkOrigine)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_6)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.lbl_signature = QtWidgets.QLabel(self.grp_description)
        self.lbl_signature.setObjectName("lbl_signature")
        self.horizontalLayout_8.addWidget(self.lbl_signature)
        self.dateSign = QtWidgets.QDateEdit(self.grp_description)
        self.dateSign.setCalendarPopup(True)
        self.dateSign.setObjectName("dateSign")
        self.horizontalLayout_8.addWidget(self.dateSign)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_8)
        self.chkIntemporel = QtWidgets.QCheckBox(self.grp_description)
        self.chkIntemporel.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.chkIntemporel.setObjectName("chkIntemporel")
        self.horizontalLayout_11.addWidget(self.chkIntemporel)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.lblDateFin = QtWidgets.QLabel(self.grp_description)
        self.lblDateFin.setObjectName("lblDateFin")
        self.horizontalLayout_9.addWidget(self.lblDateFin)
        self.dateFin = QtWidgets.QDateEdit(self.grp_description)
        self.dateFin.setCalendarPopup(True)
        self.dateFin.setObjectName("dateFin")
        self.horizontalLayout_9.addWidget(self.dateFin)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.btnOuvrePdf = QtWidgets.QPushButton(self.grp_description)
        self.btnOuvrePdf.setObjectName("btnOuvrePdf")
        self.horizontalLayout_18.addWidget(self.btnOuvrePdf)
        self.btnAjoutPdf = QtWidgets.QPushButton(self.grp_description)
        self.btnAjoutPdf.setMinimumSize(QtCore.QSize(55, 0))
        self.btnAjoutPdf.setMaximumSize(QtCore.QSize(55, 20))
        self.btnAjoutPdf.setObjectName("btnAjoutPdf")
        self.horizontalLayout_18.addWidget(self.btnAjoutPdf)
        self.btnRetraitPdf = QtWidgets.QPushButton(self.grp_description)
        self.btnRetraitPdf.setMinimumSize(QtCore.QSize(60, 0))
        self.btnRetraitPdf.setMaximumSize(QtCore.QSize(60, 20))
        self.btnRetraitPdf.setObjectName("btnRetraitPdf")
        self.horizontalLayout_18.addWidget(self.btnRetraitPdf)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem5)
        self.verticalLayout_4.addLayout(self.horizontalLayout_18)
        self.verticalLayout_3.addWidget(self.grp_description)
        self.verticalLayout_2.addWidget(self.grp_bail)
        self.grp_proprio = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.grp_proprio.setObjectName("grp_proprio")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.grp_proprio)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.grp_proprio)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2)
        self.cmbProprio = QtWidgets.QComboBox(self.grp_proprio)
        self.cmbProprio.setObjectName("cmbProprio")
        self.verticalLayout_6.addWidget(self.cmbProprio)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.btnCherchProprio = QtWidgets.QPushButton(self.grp_proprio)
        self.btnCherchProprio.setStyleSheet("")
        self.btnCherchProprio.setObjectName("btnCherchProprio")
        self.horizontalLayout_15.addWidget(self.btnCherchProprio)
        self.btnFiche = QtWidgets.QPushButton(self.grp_proprio)
        self.btnFiche.setObjectName("btnFiche")
        self.horizontalLayout_15.addWidget(self.btnFiche)
        self.verticalLayout_6.addLayout(self.horizontalLayout_15)
        self.verticalLayout_8.addLayout(self.verticalLayout_6)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.btnCreaProprio = QtWidgets.QPushButton(self.grp_proprio)
        self.btnCreaProprio.setStyleSheet("color: rgb(75, 179, 38);")
        self.btnCreaProprio.setObjectName("btnCreaProprio")
        self.horizontalLayout_16.addWidget(self.btnCreaProprio)
        self.btnModifProprio = QtWidgets.QPushButton(self.grp_proprio)
        self.btnModifProprio.setStyleSheet("color: rgb(85, 0, 255);")
        self.btnModifProprio.setObjectName("btnModifProprio")
        self.horizontalLayout_16.addWidget(self.btnModifProprio)
        self.btnSuppProprio = QtWidgets.QPushButton(self.grp_proprio)
        self.btnSuppProprio.setStyleSheet("color: rgb(230, 0, 38);")
        self.btnSuppProprio.setObjectName("btnSuppProprio")
        self.horizontalLayout_16.addWidget(self.btnSuppProprio)
        self.verticalLayout_8.addLayout(self.horizontalLayout_16)
        self.verticalLayout_2.addWidget(self.grp_proprio)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.btnPrec = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnPrec.setObjectName("btnPrec")
        self.horizontalLayout_19.addWidget(self.btnPrec)
        self.btnPremier = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnPremier.setObjectName("btnPremier")
        self.horizontalLayout_19.addWidget(self.btnPremier)
        self.btnDernier = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnDernier.setObjectName("btnDernier")
        self.horizontalLayout_19.addWidget(self.btnDernier)
        self.btnSuiv = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnSuiv.setObjectName("btnSuiv")
        self.horizontalLayout_19.addWidget(self.btnSuiv)
        self.horizontalLayout_24.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.btnZoom = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnZoom.setEnabled(True)
        self.btnZoom.setMinimumSize(QtCore.QSize(0, 36))
        self.btnZoom.setIcon(icon1)
        self.btnZoom.setObjectName("btnZoom")
        self.horizontalLayout_22.addWidget(self.btnZoom)
        self.btnSelection = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnSelection.setEnabled(True)
        self.btnSelection.setMinimumSize(QtCore.QSize(0, 36))
        self.btnSelection.setIcon(icon)
        self.btnSelection.setObjectName("btnSelection")
        self.horizontalLayout_22.addWidget(self.btnSelection)
        self.horizontalLayout_24.addLayout(self.horizontalLayout_22)
        self.verticalLayout_2.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.btnNouveau = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnNouveau.setMinimumSize(QtCore.QSize(85, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.btnNouveau.setFont(font)
        self.btnNouveau.setStyleSheet("color: rgb(0, 170, 0);")
        self.btnNouveau.setObjectName("btnNouveau")
        self.horizontalLayout_25.addWidget(self.btnNouveau)
        self.btnEnregistrer = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnEnregistrer.setMinimumSize(QtCore.QSize(85, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.btnEnregistrer.setFont(font)
        self.btnEnregistrer.setStyleSheet("color: rgb(85, 0, 255);")
        self.btnEnregistrer.setObjectName("btnEnregistrer")
        self.horizontalLayout_25.addWidget(self.btnEnregistrer)
        self.btnSupprimer = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnSupprimer.setMinimumSize(QtCore.QSize(85, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.btnSupprimer.setFont(font)
        self.btnSupprimer.setStyleSheet("color: rgb(231, 0, 0);")
        self.btnSupprimer.setObjectName("btnSupprimer")
        self.horizontalLayout_25.addWidget(self.btnSupprimer)
        self.btnAnnuler = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnAnnuler.setMinimumSize(QtCore.QSize(85, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnAnnuler.setFont(font)
        self.btnAnnuler.setObjectName("btnAnnuler")
        self.horizontalLayout_25.addWidget(self.btnAnnuler)
        self.verticalLayout_2.addLayout(self.horizontalLayout_25)
        self.grp_proprio.raise_()
        self.grp_bail.raise_()
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_5.addWidget(self.scrollArea)
        dwcBopeMainForm.setWidget(self.dwcBopeMain)

        self.retranslateUi(dwcBopeMainForm)
        QtCore.QMetaObject.connectSlotsByName(dwcBopeMainForm)

    def retranslateUi(self, dwcBopeMainForm):
        _translate = QtCore.QCoreApplication.translate
        dwcBopeMainForm.setWindowTitle(_translate("dwcBopeMainForm", "Gedopi - Droits de pêche"))
        self.btnFiltreCartoManuel.setText(_translate("dwcBopeMainForm", "Filtre carto manuel"))
        self.chkFiltreCartoAuto.setText(_translate("dwcBopeMainForm", "filtre carto automatique"))
        self.btnFiltreAttributaire.setText(_translate("dwcBopeMainForm", "Filtre attributaire"))
        self.btnDeleteFiltrage.setText(_translate("dwcBopeMainForm", "Suppression filtrage"))
        self.grp_bail.setTitle(_translate("dwcBopeMainForm", "Bail de pêche :"))
        self.label.setText(_translate("dwcBopeMainForm", "ID :"))
        self.grp_localisation.setTitle(_translate("dwcBopeMainForm", "Localisation :"))
        self.lbl_parcelle_2.setText(_translate("dwcBopeMainForm", "AAPPMA :"))
        self.lbl_parcelles.setText(_translate("dwcBopeMainForm", "Parcelle(s) concernée(s) :"))
        self.btnAjoutParcelle.setText(_translate("dwcBopeMainForm", "+"))
        self.btnSuppParcelle.setText(_translate("dwcBopeMainForm", "-"))
        self.lbl_riviere.setText(_translate("dwcBopeMainForm", "Rivière(s) concernée(s) :"))
        self.btnAjoutRiviere.setText(_translate("dwcBopeMainForm", "+"))
        self.btnSuppRiviere.setText(_translate("dwcBopeMainForm", "-"))
        self.grp_description.setTitle(_translate("dwcBopeMainForm", "Description :"))
        self.chkPossession.setText(_translate("dwcBopeMainForm", "En possession :"))
        self.chkOrigine.setText(_translate("dwcBopeMainForm", "Obtenu par la fédération :"))
        self.lbl_signature.setText(_translate("dwcBopeMainForm", "Date de signature :"))
        self.chkIntemporel.setText(_translate("dwcBopeMainForm", "Intemporel :"))
        self.lblDateFin.setText(_translate("dwcBopeMainForm", "Date de fin :"))
        self.btnOuvrePdf.setText(_translate("dwcBopeMainForm", "Ouvrir scan du bail"))
        self.btnAjoutPdf.setText(_translate("dwcBopeMainForm", "Lier scan"))
        self.btnRetraitPdf.setText(_translate("dwcBopeMainForm", "Délier scan"))
        self.grp_proprio.setTitle(_translate("dwcBopeMainForm", "Propriétaire :"))
        self.label_2.setText(_translate("dwcBopeMainForm", "Informations principales :"))
        self.btnCherchProprio.setText(_translate("dwcBopeMainForm", "Chercher propriétaire"))
        self.btnFiche.setText(_translate("dwcBopeMainForm", "Fiche complète"))
        self.btnCreaProprio.setText(_translate("dwcBopeMainForm", "Créer propriétaire"))
        self.btnModifProprio.setText(_translate("dwcBopeMainForm", "Modifier propriétaire"))
        self.btnSuppProprio.setText(_translate("dwcBopeMainForm", "Supprimer propriétaire"))
        self.btnPrec.setText(_translate("dwcBopeMainForm", "<"))
        self.btnPremier.setText(_translate("dwcBopeMainForm", "<<"))
        self.btnDernier.setText(_translate("dwcBopeMainForm", ">>"))
        self.btnSuiv.setText(_translate("dwcBopeMainForm", ">"))
        self.btnZoom.setToolTip(_translate("dwcBopeMainForm", "Zoomer sur l\'objet"))
        self.btnSelection.setToolTip(_translate("dwcBopeMainForm", "Sélectionner l\'objet"))
        self.btnNouveau.setText(_translate("dwcBopeMainForm", "Nouveau"))
        self.btnEnregistrer.setText(_translate("dwcBopeMainForm", "Enregistrer"))
        self.btnSupprimer.setText(_translate("dwcBopeMainForm", "Supprimer"))
        self.btnAnnuler.setText(_translate("dwcBopeMainForm", "Abandonner"))

import ressourceGedopi_rc
