# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms\bopeRechercheForm.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dlgBopeRechercheForm(object):
    def setupUi(self, dlgBopeRechercheForm):
        dlgBopeRechercheForm.setObjectName("dlgBopeRechercheForm")
        dlgBopeRechercheForm.resize(433, 569)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(dlgBopeRechercheForm)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.scrollArea = QtWidgets.QScrollArea(dlgBopeRechercheForm)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -277, 396, 826))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.groupBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem)
        self.btnEt = QtWidgets.QPushButton(self.groupBox_2)
        self.btnEt.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btnEt.setObjectName("btnEt")
        self.horizontalLayout_14.addWidget(self.btnEt)
        self.btnOu = QtWidgets.QPushButton(self.groupBox_2)
        self.btnOu.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btnOu.setObjectName("btnOu")
        self.horizontalLayout_14.addWidget(self.btnOu)
        self.verticalLayout_7.addLayout(self.horizontalLayout_14)
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.spnId = QtWidgets.QSpinBox(self.groupBox)
        self.spnId.setMaximum(900000)
        self.spnId.setObjectName("spnId")
        self.horizontalLayout.addWidget(self.spnId)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.cmbRiviere = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbRiviere.sizePolicy().hasHeightForWidth())
        self.cmbRiviere.setSizePolicy(sizePolicy)
        self.cmbRiviere.setObjectName("cmbRiviere")
        self.horizontalLayout_5.addWidget(self.cmbRiviere)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_8.addWidget(self.label_9)
        self.cmbAappma = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbAappma.sizePolicy().hasHeightForWidth())
        self.cmbAappma.setSizePolicy(sizePolicy)
        self.cmbAappma.setObjectName("cmbAappma")
        self.horizontalLayout_8.addWidget(self.cmbAappma)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_9.addWidget(self.label_10)
        self.chkPossession = QtWidgets.QCheckBox(self.groupBox)
        self.chkPossession.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.chkPossession.setText("")
        self.chkPossession.setObjectName("chkPossession")
        self.horizontalLayout_9.addWidget(self.chkPossession)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_7.addWidget(self.label_8)
        self.dateSign = QtWidgets.QDateEdit(self.groupBox)
        self.dateSign.setCurrentSection(QtWidgets.QDateTimeEdit.YearSection)
        self.dateSign.setCalendarPopup(False)
        self.dateSign.setObjectName("dateSign")
        self.horizontalLayout_7.addWidget(self.dateSign)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.dateFin = QtWidgets.QDateEdit(self.groupBox)
        self.dateFin.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateFin.setCurrentSection(QtWidgets.QDateTimeEdit.YearSection)
        self.dateFin.setCalendarPopup(False)
        self.dateFin.setObjectName("dateFin")
        self.horizontalLayout_6.addWidget(self.dateFin)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_17.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.btnId = QtWidgets.QPushButton(self.groupBox)
        self.btnId.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btnId.setObjectName("btnId")
        self.horizontalLayout_15.addWidget(self.btnId)
        self.verticalLayout_2.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.btnRiviere = QtWidgets.QPushButton(self.groupBox)
        self.btnRiviere.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btnRiviere.setObjectName("btnRiviere")
        self.horizontalLayout_10.addWidget(self.btnRiviere)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.btnAappma = QtWidgets.QPushButton(self.groupBox)
        self.btnAappma.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btnAappma.setObjectName("btnAappma")
        self.horizontalLayout_33.addWidget(self.btnAappma)
        self.verticalLayout_2.addLayout(self.horizontalLayout_33)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.btnPossession = QtWidgets.QPushButton(self.groupBox)
        self.btnPossession.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btnPossession.setObjectName("btnPossession")
        self.horizontalLayout_16.addWidget(self.btnPossession)
        self.verticalLayout_2.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.btnSign = QtWidgets.QPushButton(self.groupBox)
        self.btnSign.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btnSign.setObjectName("btnSign")
        self.horizontalLayout_12.addWidget(self.btnSign)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.btnFin = QtWidgets.QPushButton(self.groupBox)
        self.btnFin.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btnFin.setObjectName("btnFin")
        self.horizontalLayout_13.addWidget(self.btnFin)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_17.addLayout(self.verticalLayout_2)
        self.verticalLayout_12.addLayout(self.horizontalLayout_17)
        self.verticalLayout_7.addWidget(self.groupBox)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.cmbCommune = QtWidgets.QComboBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbCommune.sizePolicy().hasHeightForWidth())
        self.cmbCommune.setSizePolicy(sizePolicy)
        self.cmbCommune.setObjectName("cmbCommune")
        self.horizontalLayout_2.addWidget(self.cmbCommune)
        self.verticalLayout_11.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.cmbSection = QtWidgets.QComboBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbSection.sizePolicy().hasHeightForWidth())
        self.cmbSection.setSizePolicy(sizePolicy)
        self.cmbSection.setObjectName("cmbSection")
        self.horizontalLayout_3.addWidget(self.cmbSection)
        self.verticalLayout_11.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.cmbParcelle = QtWidgets.QComboBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbParcelle.sizePolicy().hasHeightForWidth())
        self.cmbParcelle.setSizePolicy(sizePolicy)
        self.cmbParcelle.setObjectName("cmbParcelle")
        self.horizontalLayout_4.addWidget(self.cmbParcelle)
        self.verticalLayout_11.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.btnC = QtWidgets.QPushButton(self.groupBox_3)
        self.btnC.setObjectName("btnC")
        self.horizontalLayout_20.addWidget(self.btnC)
        self.btnCS = QtWidgets.QPushButton(self.groupBox_3)
        self.btnCS.setObjectName("btnCS")
        self.horizontalLayout_20.addWidget(self.btnCS)
        self.btnCSP = QtWidgets.QPushButton(self.groupBox_3)
        self.btnCSP.setObjectName("btnCSP")
        self.horizontalLayout_20.addWidget(self.btnCSP)
        self.verticalLayout_11.addLayout(self.horizontalLayout_20)
        self.verticalLayout_7.addWidget(self.groupBox_3)
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.lbl_nom_2 = QtWidgets.QLabel(self.groupBox_5)
        self.lbl_nom_2.setObjectName("lbl_nom_2")
        self.horizontalLayout_21.addWidget(self.lbl_nom_2)
        self.leNom = QtWidgets.QLineEdit(self.groupBox_5)
        self.leNom.setAlignment(QtCore.Qt.AlignCenter)
        self.leNom.setObjectName("leNom")
        self.horizontalLayout_21.addWidget(self.leNom)
        self.verticalLayout_9.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.lbl_mail_2 = QtWidgets.QLabel(self.groupBox_5)
        self.lbl_mail_2.setObjectName("lbl_mail_2")
        self.horizontalLayout_23.addWidget(self.lbl_mail_2)
        self.leMail = QtWidgets.QLineEdit(self.groupBox_5)
        self.leMail.setAlignment(QtCore.Qt.AlignCenter)
        self.leMail.setObjectName("leMail")
        self.horizontalLayout_23.addWidget(self.leMail)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.lbl_tel_2 = QtWidgets.QLabel(self.groupBox_5)
        self.lbl_tel_2.setMinimumSize(QtCore.QSize(60, 0))
        self.lbl_tel_2.setObjectName("lbl_tel_2")
        self.horizontalLayout_24.addWidget(self.lbl_tel_2)
        self.leTel = QtWidgets.QLineEdit(self.groupBox_5)
        self.leTel.setMinimumSize(QtCore.QSize(0, 0))
        self.leTel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.leTel.setAlignment(QtCore.Qt.AlignCenter)
        self.leTel.setObjectName("leTel")
        self.horizontalLayout_24.addWidget(self.leTel)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem5)
        self.horizontalLayout_23.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_22.addLayout(self.horizontalLayout_23)
        self.verticalLayout_9.addLayout(self.horizontalLayout_22)
        self.verticalLayout_6.addLayout(self.verticalLayout_9)
        self.btnProprio = QtWidgets.QPushButton(self.groupBox_5)
        self.btnProprio.setObjectName("btnProprio")
        self.verticalLayout_6.addWidget(self.btnProprio)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.lbl_adresse = QtWidgets.QLabel(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_adresse.sizePolicy().hasHeightForWidth())
        self.lbl_adresse.setSizePolicy(sizePolicy)
        self.lbl_adresse.setObjectName("lbl_adresse")
        self.horizontalLayout_18.addWidget(self.lbl_adresse)
        self.leAdresse = QtWidgets.QLineEdit(self.groupBox_5)
        self.leAdresse.setAlignment(QtCore.Qt.AlignCenter)
        self.leAdresse.setObjectName("leAdresse")
        self.horizontalLayout_18.addWidget(self.leAdresse)
        self.verticalLayout_6.addLayout(self.horizontalLayout_18)
        self.btnAdresse = QtWidgets.QPushButton(self.groupBox_5)
        self.btnAdresse.setObjectName("btnAdresse")
        self.verticalLayout_6.addWidget(self.btnAdresse)
        self.verticalLayout_7.addWidget(self.groupBox_5)
        self.verticalLayout_10.addWidget(self.groupBox_2)
        self.groupBox_4 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.txtSql = QtWidgets.QTextEdit(self.groupBox_4)
        self.txtSql.setMaximumSize(QtCore.QSize(16777215, 100))
        self.txtSql.setObjectName("txtSql")
        self.verticalLayout_3.addWidget(self.txtSql)
        self.verticalLayout_10.addWidget(self.groupBox_4)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.btnPrevisualiser = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnPrevisualiser.setObjectName("btnPrevisualiser")
        self.horizontalLayout_11.addWidget(self.btnPrevisualiser)
        self.btnExec = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnExec.setObjectName("btnExec")
        self.horizontalLayout_11.addWidget(self.btnExec)
        self.btnRaz = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnRaz.setObjectName("btnRaz")
        self.horizontalLayout_11.addWidget(self.btnRaz)
        self.btnAnnuler = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnAnnuler.setObjectName("btnAnnuler")
        self.horizontalLayout_11.addWidget(self.btnAnnuler)
        self.verticalLayout_10.addLayout(self.horizontalLayout_11)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_5.addWidget(self.scrollArea)

        self.retranslateUi(dlgBopeRechercheForm)
        QtCore.QMetaObject.connectSlotsByName(dlgBopeRechercheForm)

    def retranslateUi(self, dlgBopeRechercheForm):
        _translate = QtCore.QCoreApplication.translate
        dlgBopeRechercheForm.setWindowTitle(_translate("dlgBopeRechercheForm", "Recherche de droit(s) de pêche"))
        self.groupBox_2.setTitle(_translate("dlgBopeRechercheForm", "Critère(s) :"))
        self.btnEt.setText(_translate("dlgBopeRechercheForm", "Et"))
        self.btnOu.setText(_translate("dlgBopeRechercheForm", "Ou"))
        self.groupBox.setTitle(_translate("dlgBopeRechercheForm", "Description : "))
        self.label.setText(_translate("dlgBopeRechercheForm", "ID :"))
        self.label_5.setText(_translate("dlgBopeRechercheForm", "Rivières :"))
        self.label_9.setText(_translate("dlgBopeRechercheForm", "AAPPMA :"))
        self.label_10.setText(_translate("dlgBopeRechercheForm", "En possession :"))
        self.label_8.setText(_translate("dlgBopeRechercheForm", "Année de signature :"))
        self.dateSign.setDisplayFormat(_translate("dlgBopeRechercheForm", "yyyy"))
        self.label_7.setText(_translate("dlgBopeRechercheForm", "Année de fin :"))
        self.dateFin.setDisplayFormat(_translate("dlgBopeRechercheForm", "yyyy"))
        self.btnId.setText(_translate("dlgBopeRechercheForm", "Ajouter"))
        self.btnRiviere.setText(_translate("dlgBopeRechercheForm", "Ajouter"))
        self.btnAappma.setText(_translate("dlgBopeRechercheForm", "Ajouter"))
        self.btnPossession.setText(_translate("dlgBopeRechercheForm", "Ajouter"))
        self.btnSign.setText(_translate("dlgBopeRechercheForm", "Ajouter"))
        self.btnFin.setText(_translate("dlgBopeRechercheForm", "Ajouter"))
        self.groupBox_3.setTitle(_translate("dlgBopeRechercheForm", "Localisation : "))
        self.label_2.setText(_translate("dlgBopeRechercheForm", "Commune :"))
        self.label_3.setText(_translate("dlgBopeRechercheForm", "<html><head/><body><p>Section <span style=\" font-size:7pt;\">(section ; commune absorbée)</span> :</p></body></html>"))
        self.label_4.setText(_translate("dlgBopeRechercheForm", "Parcelle :"))
        self.btnC.setText(_translate("dlgBopeRechercheForm", "Commune"))
        self.btnCS.setText(_translate("dlgBopeRechercheForm", "Commune / Section"))
        self.btnCSP.setText(_translate("dlgBopeRechercheForm", "Commune / Section / Parcelle"))
        self.groupBox_5.setTitle(_translate("dlgBopeRechercheForm", "Propriétaire : "))
        self.lbl_nom_2.setText(_translate("dlgBopeRechercheForm", "Nom :"))
        self.lbl_mail_2.setText(_translate("dlgBopeRechercheForm", "E-mail :"))
        self.lbl_tel_2.setText(_translate("dlgBopeRechercheForm", "Téléphone :"))
        self.btnProprio.setText(_translate("dlgBopeRechercheForm", "Ajouter infos propriétaire"))
        self.lbl_adresse.setText(_translate("dlgBopeRechercheForm", "Adresse : "))
        self.btnAdresse.setText(_translate("dlgBopeRechercheForm", "Ajouter adresse"))
        self.groupBox_4.setTitle(_translate("dlgBopeRechercheForm", "Requête SQL :"))
        self.label_6.setText(_translate("dlgBopeRechercheForm", "<html><head/><body><p align=\"justify\"><span style=\" font-size:7pt;\">Attention : les modifications dans la requête sont possibles mais peuvent faire échouer celle-ci voir endommager la base de données ! ! !</span></p></body></html>"))
        self.txtSql.setHtml(_translate("dlgBopeRechercheForm", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p></body></html>"))
        self.btnPrevisualiser.setText(_translate("dlgBopeRechercheForm", "Prévisualisation"))
        self.btnExec.setText(_translate("dlgBopeRechercheForm", "Exécuter"))
        self.btnRaz.setText(_translate("dlgBopeRechercheForm", "Réinitialiser"))
        self.btnAnnuler.setText(_translate("dlgBopeRechercheForm", "Annuler"))

