# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms\bopeCreaProprioForm.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dlgBopeCreaProprioForm(object):
    def setupUi(self, dlgBopeCreaProprioForm):
        dlgBopeCreaProprioForm.setObjectName("dlgBopeCreaProprioForm")
        dlgBopeCreaProprioForm.resize(490, 390)
        self.verticalLayout = QtWidgets.QVBoxLayout(dlgBopeCreaProprioForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(dlgBopeCreaProprioForm)
        self.label_2.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.groupBox = QtWidgets.QGroupBox(dlgBopeCreaProprioForm)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_riviere = QtWidgets.QLabel(self.groupBox)
        self.lbl_riviere.setObjectName("lbl_riviere")
        self.horizontalLayout.addWidget(self.lbl_riviere)
        self.leNomRecherche = QtWidgets.QLineEdit(self.groupBox)
        self.leNomRecherche.setObjectName("leNomRecherche")
        self.horizontalLayout.addWidget(self.leNomRecherche)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnChercher = QtWidgets.QPushButton(self.groupBox)
        self.btnChercher.setObjectName("btnChercher")
        self.horizontalLayout_2.addWidget(self.btnChercher)
        self.btnAjouter = QtWidgets.QPushButton(self.groupBox)
        self.btnAjouter.setObjectName("btnAjouter")
        self.horizontalLayout_2.addWidget(self.btnAjouter)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lbl_resu = QtWidgets.QLabel(self.groupBox)
        self.lbl_resu.setObjectName("lbl_resu")
        self.verticalLayout_3.addWidget(self.lbl_resu)
        self.tbvProprio = QtWidgets.QTableView(self.groupBox)
        self.tbvProprio.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tbvProprio.setObjectName("tbvProprio")
        self.verticalLayout_3.addWidget(self.tbvProprio)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout.addWidget(self.groupBox)
        self.grp_proprio = QtWidgets.QGroupBox(dlgBopeCreaProprioForm)
        self.grp_proprio.setObjectName("grp_proprio")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.grp_proprio)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.lbl_nom = QtWidgets.QLabel(self.grp_proprio)
        self.lbl_nom.setObjectName("lbl_nom")
        self.horizontalLayout_12.addWidget(self.lbl_nom)
        self.leNom = QtWidgets.QLineEdit(self.grp_proprio)
        self.leNom.setText("")
        self.leNom.setAlignment(QtCore.Qt.AlignCenter)
        self.leNom.setObjectName("leNom")
        self.horizontalLayout_12.addWidget(self.leNom)
        self.verticalLayout_6.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.lbl_mail = QtWidgets.QLabel(self.grp_proprio)
        self.lbl_mail.setObjectName("lbl_mail")
        self.horizontalLayout_14.addWidget(self.lbl_mail)
        self.leMail = QtWidgets.QLineEdit(self.grp_proprio)
        self.leMail.setText("")
        self.leMail.setAlignment(QtCore.Qt.AlignCenter)
        self.leMail.setObjectName("leMail")
        self.horizontalLayout_14.addWidget(self.leMail)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.lbl_tel = QtWidgets.QLabel(self.grp_proprio)
        self.lbl_tel.setMinimumSize(QtCore.QSize(50, 0))
        self.lbl_tel.setObjectName("lbl_tel")
        self.horizontalLayout_13.addWidget(self.lbl_tel)
        self.leTel = QtWidgets.QLineEdit(self.grp_proprio)
        self.leTel.setMinimumSize(QtCore.QSize(0, 0))
        self.leTel.setMaximumSize(QtCore.QSize(100, 16777215))
        self.leTel.setText("")
        self.leTel.setAlignment(QtCore.Qt.AlignCenter)
        self.leTel.setObjectName("leTel")
        self.horizontalLayout_13.addWidget(self.leTel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_13)
        self.verticalLayout_6.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.grp_proprio)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.leAdresse = QtWidgets.QLineEdit(self.grp_proprio)
        self.leAdresse.setText("")
        self.leAdresse.setAlignment(QtCore.Qt.AlignCenter)
        self.leAdresse.setObjectName("leAdresse")
        self.horizontalLayout_3.addWidget(self.leAdresse)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.grp_proprio)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_6.addWidget(self.buttonBox)
        self.verticalLayout.addWidget(self.grp_proprio)

        self.retranslateUi(dlgBopeCreaProprioForm)
        QtCore.QMetaObject.connectSlotsByName(dlgBopeCreaProprioForm)

    def retranslateUi(self, dlgBopeCreaProprioForm):
        _translate = QtCore.QCoreApplication.translate
        dlgBopeCreaProprioForm.setWindowTitle(_translate("dlgBopeCreaProprioForm", "Création d\'un propriétaire"))
        self.label_2.setText(_translate("dlgBopeCreaProprioForm", "<html><head/><body><p align=\"center\">Recherchez si le propriétaire existe avant d\'en créer un nouveau !</p></body></html>"))
        self.groupBox.setTitle(_translate("dlgBopeCreaProprioForm", "Recherche"))
        self.lbl_riviere.setText(_translate("dlgBopeCreaProprioForm", "Nom du propriétaire :"))
        self.btnChercher.setText(_translate("dlgBopeCreaProprioForm", "Chercher"))
        self.btnAjouter.setText(_translate("dlgBopeCreaProprioForm", "Ajouter"))
        self.lbl_resu.setText(_translate("dlgBopeCreaProprioForm", "Résultat(s) :"))
        self.grp_proprio.setTitle(_translate("dlgBopeCreaProprioForm", "Propriétaire "))
        self.lbl_nom.setText(_translate("dlgBopeCreaProprioForm", "Nom :"))
        self.lbl_mail.setText(_translate("dlgBopeCreaProprioForm", "E-mail :"))
        self.lbl_tel.setText(_translate("dlgBopeCreaProprioForm", "Téléphone :"))
        self.label_3.setText(_translate("dlgBopeCreaProprioForm", "Adresse :"))

