# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms\bopeProprioForm.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dlgBopeProprioForm(object):
    def setupUi(self, dlgBopeProprioForm):
        dlgBopeProprioForm.setObjectName("dlgBopeProprioForm")
        dlgBopeProprioForm.resize(489, 162)
        self.verticalLayout = QtWidgets.QVBoxLayout(dlgBopeProprioForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.grp_proprio = QtWidgets.QGroupBox(dlgBopeProprioForm)
        self.grp_proprio.setObjectName("grp_proprio")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.grp_proprio)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.lbl_nom = QtWidgets.QLabel(self.grp_proprio)
        self.lbl_nom.setObjectName("lbl_nom")
        self.horizontalLayout_15.addWidget(self.lbl_nom)
        self.leNom = QtWidgets.QLineEdit(self.grp_proprio)
        self.leNom.setAlignment(QtCore.Qt.AlignCenter)
        self.leNom.setObjectName("leNom")
        self.horizontalLayout_15.addWidget(self.leNom)
        self.verticalLayout_6.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.lbl_mail = QtWidgets.QLabel(self.grp_proprio)
        self.lbl_mail.setObjectName("lbl_mail")
        self.horizontalLayout_16.addWidget(self.lbl_mail)
        self.leMail = QtWidgets.QLineEdit(self.grp_proprio)
        self.leMail.setAlignment(QtCore.Qt.AlignCenter)
        self.leMail.setObjectName("leMail")
        self.horizontalLayout_16.addWidget(self.leMail)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.lbl_tel = QtWidgets.QLabel(self.grp_proprio)
        self.lbl_tel.setObjectName("lbl_tel")
        self.horizontalLayout_17.addWidget(self.lbl_tel)
        self.leTel = QtWidgets.QLineEdit(self.grp_proprio)
        self.leTel.setMinimumSize(QtCore.QSize(0, 0))
        self.leTel.setMaximumSize(QtCore.QSize(100, 16777215))
        self.leTel.setAlignment(QtCore.Qt.AlignCenter)
        self.leTel.setObjectName("leTel")
        self.horizontalLayout_17.addWidget(self.leTel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem)
        self.horizontalLayout_16.addLayout(self.horizontalLayout_17)
        self.verticalLayout_6.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.grp_proprio)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.leAdresse = QtWidgets.QLineEdit(self.grp_proprio)
        self.leAdresse.setAlignment(QtCore.Qt.AlignCenter)
        self.leAdresse.setObjectName("leAdresse")
        self.horizontalLayout_4.addWidget(self.leAdresse)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btnFermer = QtWidgets.QPushButton(self.grp_proprio)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnFermer.sizePolicy().hasHeightForWidth())
        self.btnFermer.setSizePolicy(sizePolicy)
        self.btnFermer.setMaximumSize(QtCore.QSize(100, 16777215))
        self.btnFermer.setObjectName("btnFermer")
        self.horizontalLayout.addWidget(self.btnFermer)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.grp_proprio)

        self.retranslateUi(dlgBopeProprioForm)
        QtCore.QMetaObject.connectSlotsByName(dlgBopeProprioForm)

    def retranslateUi(self, dlgBopeProprioForm):
        _translate = QtCore.QCoreApplication.translate
        dlgBopeProprioForm.setWindowTitle(_translate("dlgBopeProprioForm", "Fiche propriétaire"))
        self.grp_proprio.setTitle(_translate("dlgBopeProprioForm", "Propriétaire "))
        self.lbl_nom.setText(_translate("dlgBopeProprioForm", "Nom :"))
        self.lbl_mail.setText(_translate("dlgBopeProprioForm", "E-mail :"))
        self.lbl_tel.setText(_translate("dlgBopeProprioForm", "Téléphone :"))
        self.label_4.setText(_translate("dlgBopeProprioForm", "Adresse :"))
        self.btnFermer.setText(_translate("dlgBopeProprioForm", "Fermer"))

