# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms\bopeAjouParcelleForm.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dlgBopeAjoutParcelleForm(object):
    def setupUi(self, dlgBopeAjoutParcelleForm):
        dlgBopeAjoutParcelleForm.setObjectName("dlgBopeAjoutParcelleForm")
        dlgBopeAjoutParcelleForm.resize(433, 579)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(dlgBopeAjoutParcelleForm)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.scrollArea = QtWidgets.QScrollArea(dlgBopeAjoutParcelleForm)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 413, 559))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.groupBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.cmbCommune = QtWidgets.QComboBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbCommune.sizePolicy().hasHeightForWidth())
        self.cmbCommune.setSizePolicy(sizePolicy)
        self.cmbCommune.setObjectName("cmbCommune")
        self.horizontalLayout_2.addWidget(self.cmbCommune)
        self.verticalLayout_11.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.cmbSection = QtWidgets.QComboBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbSection.sizePolicy().hasHeightForWidth())
        self.cmbSection.setSizePolicy(sizePolicy)
        self.cmbSection.setObjectName("cmbSection")
        self.horizontalLayout_3.addWidget(self.cmbSection)
        self.verticalLayout_11.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.cmbParcelle = QtWidgets.QComboBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbParcelle.sizePolicy().hasHeightForWidth())
        self.cmbParcelle.setSizePolicy(sizePolicy)
        self.cmbParcelle.setObjectName("cmbParcelle")
        self.horizontalLayout_4.addWidget(self.cmbParcelle)
        self.verticalLayout_11.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.btnC = QtWidgets.QPushButton(self.groupBox_3)
        self.btnC.setObjectName("btnC")
        self.horizontalLayout_20.addWidget(self.btnC)
        self.btnCS = QtWidgets.QPushButton(self.groupBox_3)
        self.btnCS.setObjectName("btnCS")
        self.horizontalLayout_20.addWidget(self.btnCS)
        self.btnCSP = QtWidgets.QPushButton(self.groupBox_3)
        self.btnCSP.setObjectName("btnCSP")
        self.horizontalLayout_20.addWidget(self.btnCSP)
        self.verticalLayout_11.addLayout(self.horizontalLayout_20)
        self.verticalLayout_7.addWidget(self.groupBox_3)
        self.verticalLayout_10.addWidget(self.groupBox_2)
        self.groupBox_4 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.txtSql = QtWidgets.QTextEdit(self.groupBox_4)
        self.txtSql.setMaximumSize(QtCore.QSize(16777215, 100))
        self.txtSql.setObjectName("txtSql")
        self.verticalLayout_3.addWidget(self.txtSql)
        self.verticalLayout_10.addWidget(self.groupBox_4)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.btnPrevisualiser = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnPrevisualiser.setObjectName("btnPrevisualiser")
        self.horizontalLayout_11.addWidget(self.btnPrevisualiser)
        self.btnRechercher = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnRechercher.setObjectName("btnRechercher")
        self.horizontalLayout_11.addWidget(self.btnRechercher)
        self.btnRaz = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnRaz.setObjectName("btnRaz")
        self.horizontalLayout_11.addWidget(self.btnRaz)
        self.btnAnnuler = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnAnnuler.setObjectName("btnAnnuler")
        self.horizontalLayout_11.addWidget(self.btnAnnuler)
        self.verticalLayout_10.addLayout(self.horizontalLayout_11)
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tbvResu = QtWidgets.QTableView(self.groupBox)
        self.tbvResu.setMaximumSize(QtCore.QSize(16777215, 100))
        self.tbvResu.setObjectName("tbvResu")
        self.verticalLayout.addWidget(self.tbvResu)
        self.btnAjouter = QtWidgets.QPushButton(self.groupBox)
        self.btnAjouter.setObjectName("btnAjouter")
        self.verticalLayout.addWidget(self.btnAjouter)
        self.verticalLayout_10.addWidget(self.groupBox)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_5.addWidget(self.scrollArea)

        self.retranslateUi(dlgBopeAjoutParcelleForm)
        QtCore.QMetaObject.connectSlotsByName(dlgBopeAjoutParcelleForm)

    def retranslateUi(self, dlgBopeAjoutParcelleForm):
        _translate = QtCore.QCoreApplication.translate
        dlgBopeAjoutParcelleForm.setWindowTitle(_translate("dlgBopeAjoutParcelleForm", "Ajout de parcelle(s)"))
        self.groupBox_2.setTitle(_translate("dlgBopeAjoutParcelleForm", "Critère(s) :"))
        self.groupBox_3.setTitle(_translate("dlgBopeAjoutParcelleForm", "Localisation : "))
        self.label_2.setText(_translate("dlgBopeAjoutParcelleForm", "Commune :"))
        self.label_3.setText(_translate("dlgBopeAjoutParcelleForm", "<html><head/><body><p>Section <span style=\" font-size:7pt;\">(section ; commune absorbée)</span> :</p></body></html>"))
        self.label_4.setText(_translate("dlgBopeAjoutParcelleForm", "Parcelle :"))
        self.btnC.setText(_translate("dlgBopeAjoutParcelleForm", "Commune"))
        self.btnCS.setText(_translate("dlgBopeAjoutParcelleForm", "Commune / Section"))
        self.btnCSP.setText(_translate("dlgBopeAjoutParcelleForm", "Commune / Section / Parcelle"))
        self.groupBox_4.setTitle(_translate("dlgBopeAjoutParcelleForm", "Requête SQL :"))
        self.label_6.setText(_translate("dlgBopeAjoutParcelleForm", "<html><head/><body><p align=\"justify\"><span style=\" font-size:7pt;\">Attention : les modifications dans la requête sont possibles mais peuvent faire échouer celle-ci voir endommager la base de données ! ! !</span></p></body></html>"))
        self.txtSql.setHtml(_translate("dlgBopeAjoutParcelleForm", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p></body></html>"))
        self.btnPrevisualiser.setText(_translate("dlgBopeAjoutParcelleForm", "Prévisualiser"))
        self.btnRechercher.setText(_translate("dlgBopeAjoutParcelleForm", "Rechercher"))
        self.btnRaz.setText(_translate("dlgBopeAjoutParcelleForm", "Réinitialiser"))
        self.btnAnnuler.setText(_translate("dlgBopeAjoutParcelleForm", "Annuler"))
        self.groupBox.setTitle(_translate("dlgBopeAjoutParcelleForm", "Résultat(s) : "))
        self.btnAjouter.setText(_translate("dlgBopeAjoutParcelleForm", "Ajouter"))

