# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms\exportCsvForm.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dwcExportForm(object):
    def setupUi(self, dwcExportForm):
        dwcExportForm.setObjectName("dwcExportForm")
        dwcExportForm.resize(518, 565)
        dwcExportForm.setMinimumSize(QtCore.QSize(518, 565))
        self.dwcEport = QtWidgets.QWidget()
        self.dwcEport.setObjectName("dwcEport")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.dwcEport)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(self.dwcEport)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 481, 650))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.tabWidget = QtWidgets.QTabWidget(self.scrollAreaWidgetContents)
        self.tabWidget.setMaximumSize(QtCore.QSize(480, 270))
        self.tabWidget.setObjectName("tabWidget")
        self.tabBope = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabBope.sizePolicy().hasHeightForWidth())
        self.tabBope.setSizePolicy(sizePolicy)
        self.tabBope.setObjectName("tabBope")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tabBope)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tabBope)
        self.scrollArea_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 424, 562))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_3)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.btnBopeEt = QtWidgets.QPushButton(self.groupBox)
        self.btnBopeEt.setObjectName("btnBopeEt")
        self.horizontalLayout_7.addWidget(self.btnBopeEt)
        self.btnBopeOu = QtWidgets.QPushButton(self.groupBox)
        self.btnBopeOu.setObjectName("btnBopeOu")
        self.horizontalLayout_7.addWidget(self.btnBopeOu)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btnBopePossede = QtWidgets.QPushButton(self.groupBox)
        self.btnBopePossede.setObjectName("btnBopePossede")
        self.verticalLayout_4.addWidget(self.btnBopePossede)
        self.btnBopeCommune = QtWidgets.QPushButton(self.groupBox)
        self.btnBopeCommune.setObjectName("btnBopeCommune")
        self.verticalLayout_4.addWidget(self.btnBopeCommune)
        self.btnBopeAappma = QtWidgets.QPushButton(self.groupBox)
        self.btnBopeAappma.setObjectName("btnBopeAappma")
        self.verticalLayout_4.addWidget(self.btnBopeAappma)
        self.btnBopeCeau = QtWidgets.QPushButton(self.groupBox)
        self.btnBopeCeau.setObjectName("btnBopeCeau")
        self.verticalLayout_4.addWidget(self.btnBopeCeau)
        self.btnBopeSign = QtWidgets.QPushButton(self.groupBox)
        self.btnBopeSign.setObjectName("btnBopeSign")
        self.verticalLayout_4.addWidget(self.btnBopeSign)
        self.btnBopeFin = QtWidgets.QPushButton(self.groupBox)
        self.btnBopeFin.setObjectName("btnBopeFin")
        self.verticalLayout_4.addWidget(self.btnBopeFin)
        self.horizontalLayout_6.addLayout(self.verticalLayout_4)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.chkBopePossede = QtWidgets.QCheckBox(self.groupBox)
        self.chkBopePossede.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.chkBopePossede.setObjectName("chkBopePossede")
        self.horizontalLayout_4.addWidget(self.chkBopePossede)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.cmbBopeCommune = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbBopeCommune.sizePolicy().hasHeightForWidth())
        self.cmbBopeCommune.setSizePolicy(sizePolicy)
        self.cmbBopeCommune.setMaximumSize(QtCore.QSize(247, 16777215))
        self.cmbBopeCommune.setObjectName("cmbBopeCommune")
        self.horizontalLayout_3.addWidget(self.cmbBopeCommune)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.cmbBopeAappma = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbBopeAappma.sizePolicy().hasHeightForWidth())
        self.cmbBopeAappma.setSizePolicy(sizePolicy)
        self.cmbBopeAappma.setMaximumSize(QtCore.QSize(253, 16777215))
        self.cmbBopeAappma.setObjectName("cmbBopeAappma")
        self.horizontalLayout.addWidget(self.cmbBopeAappma)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.cmbBopeCeau = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbBopeCeau.sizePolicy().hasHeightForWidth())
        self.cmbBopeCeau.setSizePolicy(sizePolicy)
        self.cmbBopeCeau.setMaximumSize(QtCore.QSize(237, 16777215))
        self.cmbBopeCeau.setObjectName("cmbBopeCeau")
        self.horizontalLayout_2.addWidget(self.cmbBopeCeau)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_10.addWidget(self.label_5)
        self.dateBopeSign = QtWidgets.QDateEdit(self.groupBox)
        self.dateBopeSign.setObjectName("dateBopeSign")
        self.horizontalLayout_10.addWidget(self.dateBopeSign)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_9.addWidget(self.label_4)
        self.dateBopeFin = QtWidgets.QDateEdit(self.groupBox)
        self.dateBopeFin.setObjectName("dateBopeFin")
        self.horizontalLayout_9.addWidget(self.dateBopeFin)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem3)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_6.addLayout(self.verticalLayout_6)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_40 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.lbl_nom_2 = QtWidgets.QLabel(self.groupBox_8)
        self.lbl_nom_2.setObjectName("lbl_nom_2")
        self.horizontalLayout_40.addWidget(self.lbl_nom_2)
        self.leNom = QtWidgets.QLineEdit(self.groupBox_8)
        self.leNom.setAlignment(QtCore.Qt.AlignCenter)
        self.leNom.setObjectName("leNom")
        self.horizontalLayout_40.addWidget(self.leNom)
        self.verticalLayout_10.addLayout(self.horizontalLayout_40)
        self.horizontalLayout_41 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        self.horizontalLayout_42 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_42.setObjectName("horizontalLayout_42")
        self.lbl_mail_2 = QtWidgets.QLabel(self.groupBox_8)
        self.lbl_mail_2.setObjectName("lbl_mail_2")
        self.horizontalLayout_42.addWidget(self.lbl_mail_2)
        self.leMail = QtWidgets.QLineEdit(self.groupBox_8)
        self.leMail.setAlignment(QtCore.Qt.AlignCenter)
        self.leMail.setObjectName("leMail")
        self.horizontalLayout_42.addWidget(self.leMail)
        self.horizontalLayout_43 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        self.lbl_tel_2 = QtWidgets.QLabel(self.groupBox_8)
        self.lbl_tel_2.setMinimumSize(QtCore.QSize(60, 0))
        self.lbl_tel_2.setObjectName("lbl_tel_2")
        self.horizontalLayout_43.addWidget(self.lbl_tel_2)
        self.leTel = QtWidgets.QLineEdit(self.groupBox_8)
        self.leTel.setMinimumSize(QtCore.QSize(0, 0))
        self.leTel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.leTel.setAlignment(QtCore.Qt.AlignCenter)
        self.leTel.setObjectName("leTel")
        self.horizontalLayout_43.addWidget(self.leTel)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_43.addItem(spacerItem4)
        self.horizontalLayout_42.addLayout(self.horizontalLayout_43)
        self.horizontalLayout_41.addLayout(self.horizontalLayout_42)
        self.verticalLayout_10.addLayout(self.horizontalLayout_41)
        self.verticalLayout_9.addLayout(self.verticalLayout_10)
        self.btnProprio = QtWidgets.QPushButton(self.groupBox_8)
        self.btnProprio.setObjectName("btnProprio")
        self.verticalLayout_9.addWidget(self.btnProprio)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.lbl_adresse = QtWidgets.QLabel(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_adresse.sizePolicy().hasHeightForWidth())
        self.lbl_adresse.setSizePolicy(sizePolicy)
        self.lbl_adresse.setMinimumSize(QtCore.QSize(0, 0))
        self.lbl_adresse.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lbl_adresse.setObjectName("lbl_adresse")
        self.horizontalLayout_19.addWidget(self.lbl_adresse)
        self.leAdresse = QtWidgets.QLineEdit(self.groupBox_8)
        self.leAdresse.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.leAdresse.setObjectName("leAdresse")
        self.horizontalLayout_19.addWidget(self.leAdresse)
        self.verticalLayout_9.addLayout(self.horizontalLayout_19)
        self.btnAdresse = QtWidgets.QPushButton(self.groupBox_8)
        self.btnAdresse.setObjectName("btnAdresse")
        self.verticalLayout_9.addWidget(self.btnAdresse)
        self.verticalLayout_7.addWidget(self.groupBox_8)
        self.verticalLayout_24.addWidget(self.groupBox)
        self.groupBox_3 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_3)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.chkSign = QtWidgets.QCheckBox(self.groupBox_3)
        self.chkSign.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkSign.setObjectName("chkSign")
        self.verticalLayout_5.addWidget(self.chkSign)
        self.chkFin = QtWidgets.QCheckBox(self.groupBox_3)
        self.chkFin.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkFin.setObjectName("chkFin")
        self.verticalLayout_5.addWidget(self.chkFin)
        self.chkPossede = QtWidgets.QCheckBox(self.groupBox_3)
        self.chkPossede.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkPossede.setObjectName("chkPossede")
        self.verticalLayout_5.addWidget(self.chkPossede)
        self.chkIntemporel = QtWidgets.QCheckBox(self.groupBox_3)
        self.chkIntemporel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkIntemporel.setObjectName("chkIntemporel")
        self.verticalLayout_5.addWidget(self.chkIntemporel)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)
        self.verticalLayout_31 = QtWidgets.QVBoxLayout()
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.chkAappma = QtWidgets.QCheckBox(self.groupBox_3)
        self.chkAappma.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkAappma.setObjectName("chkAappma")
        self.verticalLayout_31.addWidget(self.chkAappma)
        self.chkCeau = QtWidgets.QCheckBox(self.groupBox_3)
        self.chkCeau.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkCeau.setObjectName("chkCeau")
        self.verticalLayout_31.addWidget(self.chkCeau)
        self.chkParcelle = QtWidgets.QCheckBox(self.groupBox_3)
        self.chkParcelle.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkParcelle.setObjectName("chkParcelle")
        self.verticalLayout_31.addWidget(self.chkParcelle)
        self.chkSection = QtWidgets.QCheckBox(self.groupBox_3)
        self.chkSection.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkSection.setObjectName("chkSection")
        self.verticalLayout_31.addWidget(self.chkSection)
        self.horizontalLayout_5.addLayout(self.verticalLayout_31)
        self.verticalLayout_32 = QtWidgets.QVBoxLayout()
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.chkCommune = QtWidgets.QCheckBox(self.groupBox_3)
        self.chkCommune.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkCommune.setObjectName("chkCommune")
        self.verticalLayout_32.addWidget(self.chkCommune)
        self.chkInsee = QtWidgets.QCheckBox(self.groupBox_3)
        self.chkInsee.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkInsee.setObjectName("chkInsee")
        self.verticalLayout_32.addWidget(self.chkInsee)
        self.chkPostal = QtWidgets.QCheckBox(self.groupBox_3)
        self.chkPostal.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkPostal.setObjectName("chkPostal")
        self.verticalLayout_32.addWidget(self.chkPostal)
        self.horizontalLayout_5.addLayout(self.verticalLayout_32)
        self.verticalLayout_33 = QtWidgets.QVBoxLayout()
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.chkProprio = QtWidgets.QCheckBox(self.groupBox_3)
        self.chkProprio.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkProprio.setObjectName("chkProprio")
        self.verticalLayout_33.addWidget(self.chkProprio)
        self.chkAdresse = QtWidgets.QCheckBox(self.groupBox_3)
        self.chkAdresse.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkAdresse.setObjectName("chkAdresse")
        self.verticalLayout_33.addWidget(self.chkAdresse)
        self.chkTel = QtWidgets.QCheckBox(self.groupBox_3)
        self.chkTel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkTel.setObjectName("chkTel")
        self.verticalLayout_33.addWidget(self.chkTel)
        self.chkMail = QtWidgets.QCheckBox(self.groupBox_3)
        self.chkMail.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkMail.setObjectName("chkMail")
        self.verticalLayout_33.addWidget(self.chkMail)
        self.horizontalLayout_5.addLayout(self.verticalLayout_33)
        self.verticalLayout_24.addWidget(self.groupBox_3)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_2.addWidget(self.scrollArea_2)
        self.tabWidget.addTab(self.tabBope, "")
        self.tabPeche = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabPeche.sizePolicy().hasHeightForWidth())
        self.tabPeche.setSizePolicy(sizePolicy)
        self.tabPeche.setObjectName("tabPeche")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.tabPeche)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.tabPeche)
        self.scrollArea_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 425, 496))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_28.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.groupBox_5 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem5)
        self.btnPecheEt = QtWidgets.QPushButton(self.groupBox_5)
        self.btnPecheEt.setObjectName("btnPecheEt")
        self.horizontalLayout_14.addWidget(self.btnPecheEt)
        self.btnPecheOu = QtWidgets.QPushButton(self.groupBox_5)
        self.btnPecheOu.setObjectName("btnPecheOu")
        self.horizontalLayout_14.addWidget(self.btnPecheOu)
        self.verticalLayout_12.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.btnPecheAappma = QtWidgets.QPushButton(self.groupBox_5)
        self.btnPecheAappma.setObjectName("btnPecheAappma")
        self.verticalLayout_13.addWidget(self.btnPecheAappma)
        self.btnPechePdpg = QtWidgets.QPushButton(self.groupBox_5)
        self.btnPechePdpg.setObjectName("btnPechePdpg")
        self.verticalLayout_13.addWidget(self.btnPechePdpg)
        self.btnPecheCeau = QtWidgets.QPushButton(self.groupBox_5)
        self.btnPecheCeau.setObjectName("btnPecheCeau")
        self.verticalLayout_13.addWidget(self.btnPecheCeau)
        self.btnPecheMeau = QtWidgets.QPushButton(self.groupBox_5)
        self.btnPecheMeau.setObjectName("btnPecheMeau")
        self.verticalLayout_13.addWidget(self.btnPecheMeau)
        self.btnPecheAnnee = QtWidgets.QPushButton(self.groupBox_5)
        self.btnPecheAnnee.setObjectName("btnPecheAnnee")
        self.verticalLayout_13.addWidget(self.btnPecheAnnee)
        self.btnPecheEspece = QtWidgets.QPushButton(self.groupBox_5)
        self.btnPecheEspece.setObjectName("btnPecheEspece")
        self.verticalLayout_13.addWidget(self.btnPecheEspece)
        self.horizontalLayout_16.addLayout(self.verticalLayout_13)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_8 = QtWidgets.QLabel(self.groupBox_5)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_21.addWidget(self.label_8)
        self.cmbPecheAappma = QtWidgets.QComboBox(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbPecheAappma.sizePolicy().hasHeightForWidth())
        self.cmbPecheAappma.setSizePolicy(sizePolicy)
        self.cmbPecheAappma.setMaximumSize(QtCore.QSize(253, 16777215))
        self.cmbPecheAappma.setObjectName("cmbPecheAappma")
        self.horizontalLayout_21.addWidget(self.cmbPecheAappma)
        self.verticalLayout_14.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_17 = QtWidgets.QLabel(self.groupBox_5)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_18.addWidget(self.label_17)
        self.cmbPechePdpg = QtWidgets.QComboBox(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbPechePdpg.sizePolicy().hasHeightForWidth())
        self.cmbPechePdpg.setSizePolicy(sizePolicy)
        self.cmbPechePdpg.setMaximumSize(QtCore.QSize(220, 16777215))
        self.cmbPechePdpg.setObjectName("cmbPechePdpg")
        self.horizontalLayout_18.addWidget(self.cmbPechePdpg)
        self.verticalLayout_14.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_13 = QtWidgets.QLabel(self.groupBox_5)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_23.addWidget(self.label_13)
        self.cmbPecheCeau = QtWidgets.QComboBox(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbPecheCeau.sizePolicy().hasHeightForWidth())
        self.cmbPecheCeau.setSizePolicy(sizePolicy)
        self.cmbPecheCeau.setMaximumSize(QtCore.QSize(237, 16777215))
        self.cmbPecheCeau.setObjectName("cmbPecheCeau")
        self.horizontalLayout_23.addWidget(self.cmbPecheCeau)
        self.verticalLayout_14.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_14 = QtWidgets.QLabel(self.groupBox_5)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_24.addWidget(self.label_14)
        self.cmbPecheMeau = QtWidgets.QComboBox(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbPecheMeau.sizePolicy().hasHeightForWidth())
        self.cmbPecheMeau.setSizePolicy(sizePolicy)
        self.cmbPecheMeau.setMaximumSize(QtCore.QSize(235, 16777215))
        self.cmbPecheMeau.setObjectName("cmbPecheMeau")
        self.horizontalLayout_24.addWidget(self.cmbPecheMeau)
        self.verticalLayout_14.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_15 = QtWidgets.QLabel(self.groupBox_5)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_25.addWidget(self.label_15)
        self.datePecheAnnee = QtWidgets.QDateEdit(self.groupBox_5)
        self.datePecheAnnee.setObjectName("datePecheAnnee")
        self.horizontalLayout_25.addWidget(self.datePecheAnnee)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem6)
        self.verticalLayout_14.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_16 = QtWidgets.QLabel(self.groupBox_5)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_26.addWidget(self.label_16)
        self.cmbPecheEspece = QtWidgets.QComboBox(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbPecheEspece.sizePolicy().hasHeightForWidth())
        self.cmbPecheEspece.setSizePolicy(sizePolicy)
        self.cmbPecheEspece.setMaximumSize(QtCore.QSize(255, 16777215))
        self.cmbPecheEspece.setObjectName("cmbPecheEspece")
        self.horizontalLayout_26.addWidget(self.cmbPecheEspece)
        self.verticalLayout_14.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_16.addLayout(self.verticalLayout_14)
        self.verticalLayout_12.addLayout(self.horizontalLayout_16)
        self.verticalLayout_28.addWidget(self.groupBox_5)
        self.groupBox_9 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_9.setObjectName("groupBox_9")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.groupBox_9)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_35 = QtWidgets.QVBoxLayout()
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.chkDatePeche = QtWidgets.QCheckBox(self.groupBox_9)
        self.chkDatePeche.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkDatePeche.setObjectName("chkDatePeche")
        self.verticalLayout_35.addWidget(self.chkDatePeche)
        self.chkLongueurPeche = QtWidgets.QCheckBox(self.groupBox_9)
        self.chkLongueurPeche.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkLongueurPeche.setObjectName("chkLongueurPeche")
        self.verticalLayout_35.addWidget(self.chkLongueurPeche)
        self.chkProfondeur = QtWidgets.QCheckBox(self.groupBox_9)
        self.chkProfondeur.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkProfondeur.setObjectName("chkProfondeur")
        self.verticalLayout_35.addWidget(self.chkProfondeur)
        self.chkLargeurPeche = QtWidgets.QCheckBox(self.groupBox_9)
        self.chkLargeurPeche.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkLargeurPeche.setObjectName("chkLargeurPeche")
        self.verticalLayout_35.addWidget(self.chkLargeurPeche)
        self.chkSurfacePeche = QtWidgets.QCheckBox(self.groupBox_9)
        self.chkSurfacePeche.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkSurfacePeche.setObjectName("chkSurfacePeche")
        self.verticalLayout_35.addWidget(self.chkSurfacePeche)
        self.chkPente = QtWidgets.QCheckBox(self.groupBox_9)
        self.chkPente.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkPente.setObjectName("chkPente")
        self.verticalLayout_35.addWidget(self.chkPente)
        self.chkXYPeche = QtWidgets.QCheckBox(self.groupBox_9)
        self.chkXYPeche.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkXYPeche.setObjectName("chkXYPeche")
        self.verticalLayout_35.addWidget(self.chkXYPeche)
        self.horizontalLayout_8.addLayout(self.verticalLayout_35)
        self.verticalLayout_34 = QtWidgets.QVBoxLayout()
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.chkNtt = QtWidgets.QCheckBox(self.groupBox_9)
        self.chkNtt.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkNtt.setObjectName("chkNtt")
        self.verticalLayout_34.addWidget(self.chkNtt)
        self.chkNttReel = QtWidgets.QCheckBox(self.groupBox_9)
        self.chkNttReel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkNttReel.setObjectName("chkNttReel")
        self.verticalLayout_34.addWidget(self.chkNttReel)
        self.chkIpr = QtWidgets.QCheckBox(self.groupBox_9)
        self.chkIpr.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkIpr.setObjectName("chkIpr")
        self.verticalLayout_34.addWidget(self.chkIpr)
        self.chkIprCorrespond = QtWidgets.QCheckBox(self.groupBox_9)
        self.chkIprCorrespond.setObjectName("chkIprCorrespond")
        self.verticalLayout_34.addWidget(self.chkIprCorrespond)
        self.chkEspece = QtWidgets.QCheckBox(self.groupBox_9)
        self.chkEspece.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkEspece.setObjectName("chkEspece")
        self.verticalLayout_34.addWidget(self.chkEspece)
        self.chkBiomasse = QtWidgets.QCheckBox(self.groupBox_9)
        self.chkBiomasse.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkBiomasse.setObjectName("chkBiomasse")
        self.verticalLayout_34.addWidget(self.chkBiomasse)
        self.chkBioCorrespond = QtWidgets.QCheckBox(self.groupBox_9)
        self.chkBioCorrespond.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkBioCorrespond.setObjectName("chkBioCorrespond")
        self.verticalLayout_34.addWidget(self.chkBioCorrespond)
        self.chkDensite = QtWidgets.QCheckBox(self.groupBox_9)
        self.chkDensite.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkDensite.setObjectName("chkDensite")
        self.verticalLayout_34.addWidget(self.chkDensite)
        self.chkDenCorrespond = QtWidgets.QCheckBox(self.groupBox_9)
        self.chkDenCorrespond.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkDenCorrespond.setObjectName("chkDenCorrespond")
        self.verticalLayout_34.addWidget(self.chkDenCorrespond)
        self.horizontalLayout_8.addLayout(self.verticalLayout_34)
        self.verticalLayout_25 = QtWidgets.QVBoxLayout()
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.chkComplet = QtWidgets.QCheckBox(self.groupBox_9)
        self.chkComplet.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkComplet.setObjectName("chkComplet")
        self.verticalLayout_25.addWidget(self.chkComplet)
        self.chkObservationPeche = QtWidgets.QCheckBox(self.groupBox_9)
        self.chkObservationPeche.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkObservationPeche.setObjectName("chkObservationPeche")
        self.verticalLayout_25.addWidget(self.chkObservationPeche)
        self.chkCeauPeche = QtWidgets.QCheckBox(self.groupBox_9)
        self.chkCeauPeche.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkCeauPeche.setObjectName("chkCeauPeche")
        self.verticalLayout_25.addWidget(self.chkCeauPeche)
        self.chkMotif = QtWidgets.QCheckBox(self.groupBox_9)
        self.chkMotif.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkMotif.setObjectName("chkMotif")
        self.verticalLayout_25.addWidget(self.chkMotif)
        self.chkCondition = QtWidgets.QCheckBox(self.groupBox_9)
        self.chkCondition.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkCondition.setObjectName("chkCondition")
        self.verticalLayout_25.addWidget(self.chkCondition)
        self.chkPdpgPeche = QtWidgets.QCheckBox(self.groupBox_9)
        self.chkPdpgPeche.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkPdpgPeche.setObjectName("chkPdpgPeche")
        self.verticalLayout_25.addWidget(self.chkPdpgPeche)
        self.chkMeauPeche = QtWidgets.QCheckBox(self.groupBox_9)
        self.chkMeauPeche.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkMeauPeche.setObjectName("chkMeauPeche")
        self.verticalLayout_25.addWidget(self.chkMeauPeche)
        self.chkMeauCodePeche = QtWidgets.QCheckBox(self.groupBox_9)
        self.chkMeauCodePeche.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkMeauCodePeche.setObjectName("chkMeauCodePeche")
        self.verticalLayout_25.addWidget(self.chkMeauCodePeche)
        self.horizontalLayout_8.addLayout(self.verticalLayout_25)
        self.verticalLayout_36 = QtWidgets.QVBoxLayout()
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        self.chkCodePeche = QtWidgets.QCheckBox(self.groupBox_9)
        self.chkCodePeche.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkCodePeche.setObjectName("chkCodePeche")
        self.verticalLayout_36.addWidget(self.chkCodePeche)
        self.chkStationPeche = QtWidgets.QCheckBox(self.groupBox_9)
        self.chkStationPeche.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkStationPeche.setObjectName("chkStationPeche")
        self.verticalLayout_36.addWidget(self.chkStationPeche)
        self.chkDistancePeche = QtWidgets.QCheckBox(self.groupBox_9)
        self.chkDistancePeche.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkDistancePeche.setObjectName("chkDistancePeche")
        self.verticalLayout_36.addWidget(self.chkDistancePeche)
        self.chkAltitudePeche = QtWidgets.QCheckBox(self.groupBox_9)
        self.chkAltitudePeche.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkAltitudePeche.setObjectName("chkAltitudePeche")
        self.verticalLayout_36.addWidget(self.chkAltitudePeche)
        self.chkAappmaPeche = QtWidgets.QCheckBox(self.groupBox_9)
        self.chkAappmaPeche.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkAappmaPeche.setObjectName("chkAappmaPeche")
        self.verticalLayout_36.addWidget(self.chkAappmaPeche)
        self.chkSurfBVPeche = QtWidgets.QCheckBox(self.groupBox_9)
        self.chkSurfBVPeche.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkSurfBVPeche.setObjectName("chkSurfBVPeche")
        self.verticalLayout_36.addWidget(self.chkSurfBVPeche)
        self.chkMoaPeche = QtWidgets.QCheckBox(self.groupBox_9)
        self.chkMoaPeche.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkMoaPeche.setObjectName("chkMoaPeche")
        self.verticalLayout_36.addWidget(self.chkMoaPeche)
        self.horizontalLayout_8.addLayout(self.verticalLayout_36)
        self.verticalLayout_28.addWidget(self.groupBox_9)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_15.addWidget(self.scrollArea_3)
        self.tabWidget.addTab(self.tabPeche, "")
        self.tabThermi = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabThermi.sizePolicy().hasHeightForWidth())
        self.tabThermi.setSizePolicy(sizePolicy)
        self.tabThermi.setObjectName("tabThermi")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.tabThermi)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.scrollArea_4 = QtWidgets.QScrollArea(self.tabThermi)
        self.scrollArea_4.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName("scrollArea_4")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 420, 611))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_4)
        self.verticalLayout_29.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.groupBox_6 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_4)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem7)
        self.btnThermiEt = QtWidgets.QPushButton(self.groupBox_6)
        self.btnThermiEt.setObjectName("btnThermiEt")
        self.horizontalLayout_22.addWidget(self.btnThermiEt)
        self.btnThermiOu = QtWidgets.QPushButton(self.groupBox_6)
        self.btnThermiOu.setObjectName("btnThermiOu")
        self.horizontalLayout_22.addWidget(self.btnThermiOu)
        self.verticalLayout_16.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.btnThermiAappma = QtWidgets.QPushButton(self.groupBox_6)
        self.btnThermiAappma.setObjectName("btnThermiAappma")
        self.verticalLayout_17.addWidget(self.btnThermiAappma)
        self.btnThermiPdpg = QtWidgets.QPushButton(self.groupBox_6)
        self.btnThermiPdpg.setObjectName("btnThermiPdpg")
        self.verticalLayout_17.addWidget(self.btnThermiPdpg)
        self.btnThermiCeau = QtWidgets.QPushButton(self.groupBox_6)
        self.btnThermiCeau.setObjectName("btnThermiCeau")
        self.verticalLayout_17.addWidget(self.btnThermiCeau)
        self.btnThermiMeau = QtWidgets.QPushButton(self.groupBox_6)
        self.btnThermiMeau.setObjectName("btnThermiMeau")
        self.verticalLayout_17.addWidget(self.btnThermiMeau)
        self.btnThermiAnnee = QtWidgets.QPushButton(self.groupBox_6)
        self.btnThermiAnnee.setObjectName("btnThermiAnnee")
        self.verticalLayout_17.addWidget(self.btnThermiAnnee)
        self.horizontalLayout_27.addLayout(self.verticalLayout_17)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_9 = QtWidgets.QLabel(self.groupBox_6)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_29.addWidget(self.label_9)
        self.cmbThermiAappma = QtWidgets.QComboBox(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbThermiAappma.sizePolicy().hasHeightForWidth())
        self.cmbThermiAappma.setSizePolicy(sizePolicy)
        self.cmbThermiAappma.setMaximumSize(QtCore.QSize(253, 16777215))
        self.cmbThermiAappma.setObjectName("cmbThermiAappma")
        self.horizontalLayout_29.addWidget(self.cmbThermiAappma)
        self.verticalLayout_18.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_18 = QtWidgets.QLabel(self.groupBox_6)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_28.addWidget(self.label_18)
        self.cmbThermiPdpg = QtWidgets.QComboBox(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbThermiPdpg.sizePolicy().hasHeightForWidth())
        self.cmbThermiPdpg.setSizePolicy(sizePolicy)
        self.cmbThermiPdpg.setMaximumSize(QtCore.QSize(220, 16777215))
        self.cmbThermiPdpg.setObjectName("cmbThermiPdpg")
        self.horizontalLayout_28.addWidget(self.cmbThermiPdpg)
        self.verticalLayout_18.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.label_19 = QtWidgets.QLabel(self.groupBox_6)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_30.addWidget(self.label_19)
        self.cmbThermiCeau = QtWidgets.QComboBox(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbThermiCeau.sizePolicy().hasHeightForWidth())
        self.cmbThermiCeau.setSizePolicy(sizePolicy)
        self.cmbThermiCeau.setMaximumSize(QtCore.QSize(237, 16777215))
        self.cmbThermiCeau.setObjectName("cmbThermiCeau")
        self.horizontalLayout_30.addWidget(self.cmbThermiCeau)
        self.verticalLayout_18.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.label_20 = QtWidgets.QLabel(self.groupBox_6)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_31.addWidget(self.label_20)
        self.cmbThermiMeau = QtWidgets.QComboBox(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbThermiMeau.sizePolicy().hasHeightForWidth())
        self.cmbThermiMeau.setSizePolicy(sizePolicy)
        self.cmbThermiMeau.setMaximumSize(QtCore.QSize(235, 16777215))
        self.cmbThermiMeau.setObjectName("cmbThermiMeau")
        self.horizontalLayout_31.addWidget(self.cmbThermiMeau)
        self.verticalLayout_18.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.label_21 = QtWidgets.QLabel(self.groupBox_6)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_32.addWidget(self.label_21)
        self.dateThermiAnnee = QtWidgets.QDateEdit(self.groupBox_6)
        self.dateThermiAnnee.setObjectName("dateThermiAnnee")
        self.horizontalLayout_32.addWidget(self.dateThermiAnnee)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_32.addItem(spacerItem8)
        self.verticalLayout_18.addLayout(self.horizontalLayout_32)
        self.horizontalLayout_27.addLayout(self.verticalLayout_18)
        self.verticalLayout_16.addLayout(self.horizontalLayout_27)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_16.addItem(spacerItem9)
        self.verticalLayout_29.addWidget(self.groupBox_6)
        self.groupBox_12 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_4)
        self.groupBox_12.setObjectName("groupBox_12")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.groupBox_12)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_37 = QtWidgets.QVBoxLayout()
        self.verticalLayout_37.setObjectName("verticalLayout_37")
        self.chkDateDebut = QtWidgets.QCheckBox(self.groupBox_12)
        self.chkDateDebut.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkDateDebut.setObjectName("chkDateDebut")
        self.verticalLayout_37.addWidget(self.chkDateDebut)
        self.chkDateFin = QtWidgets.QCheckBox(self.groupBox_12)
        self.chkDateFin.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkDateFin.setObjectName("chkDateFin")
        self.verticalLayout_37.addWidget(self.chkDateFin)
        self.chkDuree = QtWidgets.QCheckBox(self.groupBox_12)
        self.chkDuree.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkDuree.setObjectName("chkDuree")
        self.verticalLayout_37.addWidget(self.chkDuree)
        self.chkTimin = QtWidgets.QCheckBox(self.groupBox_12)
        self.chkTimin.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkTimin.setObjectName("chkTimin")
        self.verticalLayout_37.addWidget(self.chkTimin)
        self.chkTimax = QtWidgets.QCheckBox(self.groupBox_12)
        self.chkTimax.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkTimax.setObjectName("chkTimax")
        self.verticalLayout_37.addWidget(self.chkTimax)
        self.chkAjmaxTi = QtWidgets.QCheckBox(self.groupBox_12)
        self.chkAjmaxTi.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkAjmaxTi.setObjectName("chkAjmaxTi")
        self.verticalLayout_37.addWidget(self.chkAjmaxTi)
        self.chkDAjmaxTi = QtWidgets.QCheckBox(self.groupBox_12)
        self.chkDAjmaxTi.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkDAjmaxTi.setObjectName("chkDAjmaxTi")
        self.verticalLayout_37.addWidget(self.chkDAjmaxTi)
        self.chkTmjMin = QtWidgets.QCheckBox(self.groupBox_12)
        self.chkTmjMin.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkTmjMin.setObjectName("chkTmjMin")
        self.verticalLayout_37.addWidget(self.chkTmjMin)
        self.chkTmjMax = QtWidgets.QCheckBox(self.groupBox_12)
        self.chkTmjMax.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkTmjMax.setObjectName("chkTmjMax")
        self.verticalLayout_37.addWidget(self.chkTmjMax)
        self.chkTmpMoy = QtWidgets.QCheckBox(self.groupBox_12)
        self.chkTmpMoy.setObjectName("chkTmpMoy")
        self.verticalLayout_37.addWidget(self.chkTmpMoy)
        self.chkTmj30Max = QtWidgets.QCheckBox(self.groupBox_12)
        self.chkTmj30Max.setObjectName("chkTmj30Max")
        self.verticalLayout_37.addWidget(self.chkTmj30Max)
        self.chkNbjTmj419 = QtWidgets.QCheckBox(self.groupBox_12)
        self.chkNbjTmj419.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkNbjTmj419.setObjectName("chkNbjTmj419")
        self.verticalLayout_37.addWidget(self.chkNbjTmj419)
        self.chkP100Tmj419 = QtWidgets.QCheckBox(self.groupBox_12)
        self.chkP100Tmj419.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkP100Tmj419.setObjectName("chkP100Tmj419")
        self.verticalLayout_37.addWidget(self.chkP100Tmj419)
        self.horizontalLayout_11.addLayout(self.verticalLayout_37)
        self.verticalLayout_39 = QtWidgets.QVBoxLayout()
        self.verticalLayout_39.setObjectName("verticalLayout_39")
        self.chkP100TmjInf4 = QtWidgets.QCheckBox(self.groupBox_12)
        self.chkP100TmjInf4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkP100TmjInf4.setObjectName("chkP100TmjInf4")
        self.verticalLayout_39.addWidget(self.chkP100TmjInf4)
        self.chkP100TmjSup19 = QtWidgets.QCheckBox(self.groupBox_12)
        self.chkP100TmjSup19.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkP100TmjSup19.setObjectName("chkP100TmjSup19")
        self.verticalLayout_39.addWidget(self.chkP100TmjSup19)
        self.chkNbMaxTiCsfSup19 = QtWidgets.QCheckBox(self.groupBox_12)
        self.chkNbMaxTiCsfSup19.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkNbMaxTiCsfSup19.setObjectName("chkNbMaxTiCsfSup19")
        self.verticalLayout_39.addWidget(self.chkNbMaxTiCsfSup19)
        self.chkNbMaxTiCsfSupEg25 = QtWidgets.QCheckBox(self.groupBox_12)
        self.chkNbMaxTiCsfSupEg25.setObjectName("chkNbMaxTiCsfSupEg25")
        self.verticalLayout_39.addWidget(self.chkNbMaxTiCsfSupEg25)
        self.chkNbMaxTiCsfSupEg15 = QtWidgets.QCheckBox(self.groupBox_12)
        self.chkNbMaxTiCsfSupEg15.setObjectName("chkNbMaxTiCsfSupEg15")
        self.verticalLayout_39.addWidget(self.chkNbMaxTiCsfSupEg15)
        self.chkD50Ponte = QtWidgets.QCheckBox(self.groupBox_12)
        self.chkD50Ponte.setObjectName("chkD50Ponte")
        self.verticalLayout_39.addWidget(self.chkD50Ponte)
        self.chkNbjIncub = QtWidgets.QCheckBox(self.groupBox_12)
        self.chkNbjIncub.setObjectName("chkNbjIncub")
        self.verticalLayout_39.addWidget(self.chkNbjIncub)
        self.chkD50Eclo = QtWidgets.QCheckBox(self.groupBox_12)
        self.chkD50Eclo.setObjectName("chkD50Eclo")
        self.verticalLayout_39.addWidget(self.chkD50Eclo)
        self.chkNbjRsp = QtWidgets.QCheckBox(self.groupBox_12)
        self.chkNbjRsp.setObjectName("chkNbjRsp")
        self.verticalLayout_39.addWidget(self.chkNbjRsp)
        self.chkD50Emg = QtWidgets.QCheckBox(self.groupBox_12)
        self.chkD50Emg.setObjectName("chkD50Emg")
        self.verticalLayout_39.addWidget(self.chkD50Emg)
        self.chkNbjPel = QtWidgets.QCheckBox(self.groupBox_12)
        self.chkNbjPel.setObjectName("chkNbjPel")
        self.verticalLayout_39.addWidget(self.chkNbjPel)
        self.chkNbTiSup15Pel = QtWidgets.QCheckBox(self.groupBox_12)
        self.chkNbTiSup15Pel.setObjectName("chkNbTiSup15Pel")
        self.verticalLayout_39.addWidget(self.chkNbTiSup15Pel)
        self.chkNbMaxTiCsfSup15Pel = QtWidgets.QCheckBox(self.groupBox_12)
        self.chkNbMaxTiCsfSup15Pel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkNbMaxTiCsfSup15Pel.setObjectName("chkNbMaxTiCsfSup15Pel")
        self.verticalLayout_39.addWidget(self.chkNbMaxTiCsfSup15Pel)
        self.chkNbTiInf15Pel = QtWidgets.QCheckBox(self.groupBox_12)
        self.chkNbTiInf15Pel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkNbTiInf15Pel.setObjectName("chkNbTiInf15Pel")
        self.verticalLayout_39.addWidget(self.chkNbTiInf15Pel)
        self.chkNbMaxTiCsfInf15Pel = QtWidgets.QCheckBox(self.groupBox_12)
        self.chkNbMaxTiCsfInf15Pel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkNbMaxTiCsfInf15Pel.setObjectName("chkNbMaxTiCsfInf15Pel")
        self.verticalLayout_39.addWidget(self.chkNbMaxTiCsfInf15Pel)
        self.horizontalLayout_11.addLayout(self.verticalLayout_39)
        self.verticalLayout_40 = QtWidgets.QVBoxLayout()
        self.verticalLayout_40.setObjectName("verticalLayout_40")
        self.chkCodeThermi = QtWidgets.QCheckBox(self.groupBox_12)
        self.chkCodeThermi.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkCodeThermi.setObjectName("chkCodeThermi")
        self.verticalLayout_40.addWidget(self.chkCodeThermi)
        self.chkStationThermi = QtWidgets.QCheckBox(self.groupBox_12)
        self.chkStationThermi.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkStationThermi.setObjectName("chkStationThermi")
        self.verticalLayout_40.addWidget(self.chkStationThermi)
        self.chkCeauThermi = QtWidgets.QCheckBox(self.groupBox_12)
        self.chkCeauThermi.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkCeauThermi.setObjectName("chkCeauThermi")
        self.verticalLayout_40.addWidget(self.chkCeauThermi)
        self.chkXYStationThermi = QtWidgets.QCheckBox(self.groupBox_12)
        self.chkXYStationThermi.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkXYStationThermi.setObjectName("chkXYStationThermi")
        self.verticalLayout_40.addWidget(self.chkXYStationThermi)
        self.chkXYSondeThermi = QtWidgets.QCheckBox(self.groupBox_12)
        self.chkXYSondeThermi.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkXYSondeThermi.setObjectName("chkXYSondeThermi")
        self.verticalLayout_40.addWidget(self.chkXYSondeThermi)
        self.chkDistanceThermi = QtWidgets.QCheckBox(self.groupBox_12)
        self.chkDistanceThermi.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkDistanceThermi.setObjectName("chkDistanceThermi")
        self.verticalLayout_40.addWidget(self.chkDistanceThermi)
        self.chkAltitudeThermi = QtWidgets.QCheckBox(self.groupBox_12)
        self.chkAltitudeThermi.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkAltitudeThermi.setObjectName("chkAltitudeThermi")
        self.verticalLayout_40.addWidget(self.chkAltitudeThermi)
        self.chkAappmaThermi = QtWidgets.QCheckBox(self.groupBox_12)
        self.chkAappmaThermi.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkAappmaThermi.setObjectName("chkAappmaThermi")
        self.verticalLayout_40.addWidget(self.chkAappmaThermi)
        self.chkSurfBVThermi = QtWidgets.QCheckBox(self.groupBox_12)
        self.chkSurfBVThermi.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkSurfBVThermi.setObjectName("chkSurfBVThermi")
        self.verticalLayout_40.addWidget(self.chkSurfBVThermi)
        self.chkMoaThermi = QtWidgets.QCheckBox(self.groupBox_12)
        self.chkMoaThermi.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkMoaThermi.setObjectName("chkMoaThermi")
        self.verticalLayout_40.addWidget(self.chkMoaThermi)
        self.chkMeauThermi = QtWidgets.QCheckBox(self.groupBox_12)
        self.chkMeauThermi.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkMeauThermi.setObjectName("chkMeauThermi")
        self.verticalLayout_40.addWidget(self.chkMeauThermi)
        self.chkPdpgThermi = QtWidgets.QCheckBox(self.groupBox_12)
        self.chkPdpgThermi.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkPdpgThermi.setObjectName("chkPdpgThermi")
        self.verticalLayout_40.addWidget(self.chkPdpgThermi)
        self.chkMeauCodeThermi = QtWidgets.QCheckBox(self.groupBox_12)
        self.chkMeauCodeThermi.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkMeauCodeThermi.setObjectName("chkMeauCodeThermi")
        self.verticalLayout_40.addWidget(self.chkMeauCodeThermi)
        self.horizontalLayout_11.addLayout(self.verticalLayout_40)
        self.verticalLayout_29.addWidget(self.groupBox_12)
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_4)
        self.verticalLayout_19.addWidget(self.scrollArea_4)
        self.tabWidget.addTab(self.tabThermi, "")
        self.tabRepro = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabRepro.sizePolicy().hasHeightForWidth())
        self.tabRepro.setSizePolicy(sizePolicy)
        self.tabRepro.setObjectName("tabRepro")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.tabRepro)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.scrollArea_5 = QtWidgets.QScrollArea(self.tabRepro)
        self.scrollArea_5.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_5.setWidgetResizable(True)
        self.scrollArea_5.setObjectName("scrollArea_5")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 430, 404))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_5)
        self.verticalLayout_30.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.groupBox_7 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_5)
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_33.addItem(spacerItem10)
        self.btnReproEt = QtWidgets.QPushButton(self.groupBox_7)
        self.btnReproEt.setObjectName("btnReproEt")
        self.horizontalLayout_33.addWidget(self.btnReproEt)
        self.btnReproOu = QtWidgets.QPushButton(self.groupBox_7)
        self.btnReproOu.setObjectName("btnReproOu")
        self.horizontalLayout_33.addWidget(self.btnReproOu)
        self.verticalLayout_20.addLayout(self.horizontalLayout_33)
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.btnReproAappma = QtWidgets.QPushButton(self.groupBox_7)
        self.btnReproAappma.setObjectName("btnReproAappma")
        self.verticalLayout_21.addWidget(self.btnReproAappma)
        self.btnReproPdpg = QtWidgets.QPushButton(self.groupBox_7)
        self.btnReproPdpg.setObjectName("btnReproPdpg")
        self.verticalLayout_21.addWidget(self.btnReproPdpg)
        self.btnReproCeau = QtWidgets.QPushButton(self.groupBox_7)
        self.btnReproCeau.setObjectName("btnReproCeau")
        self.verticalLayout_21.addWidget(self.btnReproCeau)
        self.btnReproMeau = QtWidgets.QPushButton(self.groupBox_7)
        self.btnReproMeau.setObjectName("btnReproMeau")
        self.verticalLayout_21.addWidget(self.btnReproMeau)
        self.btnReproAnnee = QtWidgets.QPushButton(self.groupBox_7)
        self.btnReproAnnee.setObjectName("btnReproAnnee")
        self.verticalLayout_21.addWidget(self.btnReproAnnee)
        self.horizontalLayout_34.addLayout(self.verticalLayout_21)
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.label_10 = QtWidgets.QLabel(self.groupBox_7)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_36.addWidget(self.label_10)
        self.cmbReproAappma = QtWidgets.QComboBox(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbReproAappma.sizePolicy().hasHeightForWidth())
        self.cmbReproAappma.setSizePolicy(sizePolicy)
        self.cmbReproAappma.setMaximumSize(QtCore.QSize(253, 16777215))
        self.cmbReproAappma.setObjectName("cmbReproAappma")
        self.horizontalLayout_36.addWidget(self.cmbReproAappma)
        self.verticalLayout_22.addLayout(self.horizontalLayout_36)
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.label_22 = QtWidgets.QLabel(self.groupBox_7)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_35.addWidget(self.label_22)
        self.cmbReproPdpg = QtWidgets.QComboBox(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbReproPdpg.sizePolicy().hasHeightForWidth())
        self.cmbReproPdpg.setSizePolicy(sizePolicy)
        self.cmbReproPdpg.setMaximumSize(QtCore.QSize(220, 16777215))
        self.cmbReproPdpg.setObjectName("cmbReproPdpg")
        self.horizontalLayout_35.addWidget(self.cmbReproPdpg)
        self.verticalLayout_22.addLayout(self.horizontalLayout_35)
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.label_24 = QtWidgets.QLabel(self.groupBox_7)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_37.addWidget(self.label_24)
        self.cmbReproCeau = QtWidgets.QComboBox(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbReproCeau.sizePolicy().hasHeightForWidth())
        self.cmbReproCeau.setSizePolicy(sizePolicy)
        self.cmbReproCeau.setMaximumSize(QtCore.QSize(237, 16777215))
        self.cmbReproCeau.setObjectName("cmbReproCeau")
        self.horizontalLayout_37.addWidget(self.cmbReproCeau)
        self.verticalLayout_22.addLayout(self.horizontalLayout_37)
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.label_25 = QtWidgets.QLabel(self.groupBox_7)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_38.addWidget(self.label_25)
        self.cmbReproMeau = QtWidgets.QComboBox(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbReproMeau.sizePolicy().hasHeightForWidth())
        self.cmbReproMeau.setSizePolicy(sizePolicy)
        self.cmbReproMeau.setMaximumSize(QtCore.QSize(235, 16777215))
        self.cmbReproMeau.setObjectName("cmbReproMeau")
        self.horizontalLayout_38.addWidget(self.cmbReproMeau)
        self.verticalLayout_22.addLayout(self.horizontalLayout_38)
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.label_26 = QtWidgets.QLabel(self.groupBox_7)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_39.addWidget(self.label_26)
        self.dateReproAnnee = QtWidgets.QDateEdit(self.groupBox_7)
        self.dateReproAnnee.setObjectName("dateReproAnnee")
        self.horizontalLayout_39.addWidget(self.dateReproAnnee)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_39.addItem(spacerItem11)
        self.verticalLayout_22.addLayout(self.horizontalLayout_39)
        self.horizontalLayout_34.addLayout(self.verticalLayout_22)
        self.verticalLayout_20.addLayout(self.horizontalLayout_34)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_20.addItem(spacerItem12)
        self.verticalLayout_30.addWidget(self.groupBox_7)
        self.groupBox_10 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_5)
        self.groupBox_10.setObjectName("groupBox_10")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.groupBox_10)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.verticalLayout_41 = QtWidgets.QVBoxLayout()
        self.verticalLayout_41.setObjectName("verticalLayout_41")
        self.chkDateRepro = QtWidgets.QCheckBox(self.groupBox_10)
        self.chkDateRepro.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkDateRepro.setObjectName("chkDateRepro")
        self.verticalLayout_41.addWidget(self.chkDateRepro)
        self.chkPassage = QtWidgets.QCheckBox(self.groupBox_10)
        self.chkPassage.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkPassage.setObjectName("chkPassage")
        self.verticalLayout_41.addWidget(self.chkPassage)
        self.chkSgf = QtWidgets.QCheckBox(self.groupBox_10)
        self.chkSgf.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkSgf.setObjectName("chkSgf")
        self.verticalLayout_41.addWidget(self.chkSgf)
        self.chkZfp = QtWidgets.QCheckBox(self.groupBox_10)
        self.chkZfp.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkZfp.setObjectName("chkZfp")
        self.verticalLayout_41.addWidget(self.chkZfp)
        self.chkFrayere = QtWidgets.QCheckBox(self.groupBox_10)
        self.chkFrayere.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkFrayere.setObjectName("chkFrayere")
        self.verticalLayout_41.addWidget(self.chkFrayere)
        self.chkSurfaceFrayere = QtWidgets.QCheckBox(self.groupBox_10)
        self.chkSurfaceFrayere.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkSurfaceFrayere.setObjectName("chkSurfaceFrayere")
        self.verticalLayout_41.addWidget(self.chkSurfaceFrayere)
        self.horizontalLayout_13.addLayout(self.verticalLayout_41)
        self.verticalLayout_42 = QtWidgets.QVBoxLayout()
        self.verticalLayout_42.setObjectName("verticalLayout_42")
        self.chkXYAvalRepro = QtWidgets.QCheckBox(self.groupBox_10)
        self.chkXYAvalRepro.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkXYAvalRepro.setObjectName("chkXYAvalRepro")
        self.verticalLayout_42.addWidget(self.chkXYAvalRepro)
        self.chkXYStationRepro = QtWidgets.QCheckBox(self.groupBox_10)
        self.chkXYStationRepro.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkXYStationRepro.setObjectName("chkXYStationRepro")
        self.verticalLayout_42.addWidget(self.chkXYStationRepro)
        self.chkBaran = QtWidgets.QCheckBox(self.groupBox_10)
        self.chkBaran.setObjectName("chkBaran")
        self.verticalLayout_42.addWidget(self.chkBaran)
        self.chkBaranCorrespond = QtWidgets.QCheckBox(self.groupBox_10)
        self.chkBaranCorrespond.setObjectName("chkBaranCorrespond")
        self.verticalLayout_42.addWidget(self.chkBaranCorrespond)
        self.chkLargeurRepro = QtWidgets.QCheckBox(self.groupBox_10)
        self.chkLargeurRepro.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkLargeurRepro.setObjectName("chkLargeurRepro")
        self.verticalLayout_42.addWidget(self.chkLargeurRepro)
        self.chkLongueurRepro = QtWidgets.QCheckBox(self.groupBox_10)
        self.chkLongueurRepro.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkLongueurRepro.setObjectName("chkLongueurRepro")
        self.verticalLayout_42.addWidget(self.chkLongueurRepro)
        self.horizontalLayout_13.addLayout(self.verticalLayout_42)
        self.verticalLayout_26 = QtWidgets.QVBoxLayout()
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.chkCeauRepro = QtWidgets.QCheckBox(self.groupBox_10)
        self.chkCeauRepro.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkCeauRepro.setObjectName("chkCeauRepro")
        self.verticalLayout_26.addWidget(self.chkCeauRepro)
        self.chkPdpgRepro = QtWidgets.QCheckBox(self.groupBox_10)
        self.chkPdpgRepro.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkPdpgRepro.setObjectName("chkPdpgRepro")
        self.verticalLayout_26.addWidget(self.chkPdpgRepro)
        self.chkMeauRepro = QtWidgets.QCheckBox(self.groupBox_10)
        self.chkMeauRepro.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkMeauRepro.setObjectName("chkMeauRepro")
        self.verticalLayout_26.addWidget(self.chkMeauRepro)
        self.chkMeauCodeRepro = QtWidgets.QCheckBox(self.groupBox_10)
        self.chkMeauCodeRepro.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkMeauCodeRepro.setObjectName("chkMeauCodeRepro")
        self.verticalLayout_26.addWidget(self.chkMeauCodeRepro)
        self.chkMoaRepro = QtWidgets.QCheckBox(self.groupBox_10)
        self.chkMoaRepro.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkMoaRepro.setObjectName("chkMoaRepro")
        self.verticalLayout_26.addWidget(self.chkMoaRepro)
        self.horizontalLayout_13.addLayout(self.verticalLayout_26)
        self.verticalLayout_43 = QtWidgets.QVBoxLayout()
        self.verticalLayout_43.setObjectName("verticalLayout_43")
        self.chkCodeRepro = QtWidgets.QCheckBox(self.groupBox_10)
        self.chkCodeRepro.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkCodeRepro.setObjectName("chkCodeRepro")
        self.verticalLayout_43.addWidget(self.chkCodeRepro)
        self.chkStationRepro = QtWidgets.QCheckBox(self.groupBox_10)
        self.chkStationRepro.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkStationRepro.setObjectName("chkStationRepro")
        self.verticalLayout_43.addWidget(self.chkStationRepro)
        self.chkDistanceRepro = QtWidgets.QCheckBox(self.groupBox_10)
        self.chkDistanceRepro.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkDistanceRepro.setObjectName("chkDistanceRepro")
        self.verticalLayout_43.addWidget(self.chkDistanceRepro)
        self.chkAltitudeRepro = QtWidgets.QCheckBox(self.groupBox_10)
        self.chkAltitudeRepro.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkAltitudeRepro.setObjectName("chkAltitudeRepro")
        self.verticalLayout_43.addWidget(self.chkAltitudeRepro)
        self.chkAappmaRepro = QtWidgets.QCheckBox(self.groupBox_10)
        self.chkAappmaRepro.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkAappmaRepro.setObjectName("chkAappmaRepro")
        self.verticalLayout_43.addWidget(self.chkAappmaRepro)
        self.chkSurfBVRepro = QtWidgets.QCheckBox(self.groupBox_10)
        self.chkSurfBVRepro.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkSurfBVRepro.setObjectName("chkSurfBVRepro")
        self.verticalLayout_43.addWidget(self.chkSurfBVRepro)
        self.horizontalLayout_13.addLayout(self.verticalLayout_43)
        self.verticalLayout_30.addWidget(self.groupBox_10)
        self.scrollArea_5.setWidget(self.scrollAreaWidgetContents_5)
        self.verticalLayout_23.addWidget(self.scrollArea_5)
        self.tabWidget.addTab(self.tabRepro, "")
        self.verticalLayout_11.addWidget(self.tabWidget)
        self.groupBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_8.addWidget(self.label_7)
        self.txtSql = QtWidgets.QTextEdit(self.groupBox_4)
        self.txtSql.setMaximumSize(QtCore.QSize(16777215, 75))
        self.txtSql.setObjectName("txtSql")
        self.verticalLayout_8.addWidget(self.txtSql)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.btnPreviRequete = QtWidgets.QPushButton(self.groupBox_2)
        self.btnPreviRequete.setObjectName("btnPreviRequete")
        self.horizontalLayout_12.addWidget(self.btnPreviRequete)
        self.btnPreviResu = QtWidgets.QPushButton(self.groupBox_2)
        self.btnPreviResu.setObjectName("btnPreviResu")
        self.horizontalLayout_12.addWidget(self.btnPreviResu)
        self.btnRaz = QtWidgets.QPushButton(self.groupBox_2)
        self.btnRaz.setObjectName("btnRaz")
        self.horizontalLayout_12.addWidget(self.btnRaz)
        self.btnEnregistrer = QtWidgets.QPushButton(self.groupBox_2)
        self.btnEnregistrer.setObjectName("btnEnregistrer")
        self.horizontalLayout_12.addWidget(self.btnEnregistrer)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.tbvPrevisu = QtWidgets.QTableView(self.groupBox_2)
        self.tbvPrevisu.setMaximumSize(QtCore.QSize(16777215, 150))
        self.tbvPrevisu.setObjectName("tbvPrevisu")
        self.verticalLayout.addWidget(self.tbvPrevisu)
        self.verticalLayout_11.addWidget(self.groupBox_2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)
        dwcExportForm.setWidget(self.dwcEport)

        self.retranslateUi(dwcExportForm)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(dwcExportForm)

    def retranslateUi(self, dwcExportForm):
        _translate = QtCore.QCoreApplication.translate
        dwcExportForm.setWindowTitle(_translate("dwcExportForm", "Gedopi - Export CSV"))
        self.groupBox.setTitle(_translate("dwcExportForm", "Critères : "))
        self.btnBopeEt.setText(_translate("dwcExportForm", "Et"))
        self.btnBopeOu.setText(_translate("dwcExportForm", "Ou"))
        self.btnBopePossede.setText(_translate("dwcExportForm", "Ajouter"))
        self.btnBopeCommune.setText(_translate("dwcExportForm", "Ajouter"))
        self.btnBopeAappma.setText(_translate("dwcExportForm", "Ajouter"))
        self.btnBopeCeau.setText(_translate("dwcExportForm", "Ajouter"))
        self.btnBopeSign.setText(_translate("dwcExportForm", "Ajouter"))
        self.btnBopeFin.setText(_translate("dwcExportForm", "Ajouter"))
        self.chkBopePossede.setText(_translate("dwcExportForm", "Possédé : "))
        self.label_2.setText(_translate("dwcExportForm", "Commune : "))
        self.label.setText(_translate("dwcExportForm", "AAPPMA : "))
        self.label_3.setText(_translate("dwcExportForm", "Cours d\'eau : "))
        self.label_5.setText(_translate("dwcExportForm", "Année de signature : "))
        self.dateBopeSign.setDisplayFormat(_translate("dwcExportForm", "yyyy"))
        self.label_4.setText(_translate("dwcExportForm", "Année de fin : "))
        self.dateBopeFin.setDisplayFormat(_translate("dwcExportForm", "yyyy"))
        self.groupBox_8.setTitle(_translate("dwcExportForm", "Propriétaire : "))
        self.lbl_nom_2.setText(_translate("dwcExportForm", "Nom :"))
        self.lbl_mail_2.setText(_translate("dwcExportForm", "E-mail :"))
        self.lbl_tel_2.setText(_translate("dwcExportForm", "Téléphone :"))
        self.btnProprio.setText(_translate("dwcExportForm", "Ajouter infos propriétaire"))
        self.lbl_adresse.setText(_translate("dwcExportForm", "Adresse : "))
        self.btnAdresse.setText(_translate("dwcExportForm", "Ajouter adresse"))
        self.groupBox_3.setTitle(_translate("dwcExportForm", "Choix des champs :"))
        self.chkSign.setText(_translate("dwcExportForm", "Date de signature"))
        self.chkFin.setText(_translate("dwcExportForm", "Date de fin"))
        self.chkPossede.setText(_translate("dwcExportForm", "En possession"))
        self.chkIntemporel.setText(_translate("dwcExportForm", "Intemporel"))
        self.chkAappma.setText(_translate("dwcExportForm", "AAPPMA"))
        self.chkCeau.setText(_translate("dwcExportForm", "Cours d\'eau"))
        self.chkParcelle.setText(_translate("dwcExportForm", "N° de parcelle"))
        self.chkSection.setText(_translate("dwcExportForm", "N° de section"))
        self.chkCommune.setText(_translate("dwcExportForm", "Commune"))
        self.chkInsee.setText(_translate("dwcExportForm", "Code INSEE"))
        self.chkPostal.setText(_translate("dwcExportForm", "Code postal"))
        self.chkProprio.setText(_translate("dwcExportForm", "Nom proprio"))
        self.chkAdresse.setText(_translate("dwcExportForm", "Adresse"))
        self.chkTel.setText(_translate("dwcExportForm", "Téléphone"))
        self.chkMail.setText(_translate("dwcExportForm", "E-Mail"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabBope), _translate("dwcExportForm", "Droit de pêche"))
        self.groupBox_5.setTitle(_translate("dwcExportForm", "Critères : "))
        self.btnPecheEt.setText(_translate("dwcExportForm", "Et"))
        self.btnPecheOu.setText(_translate("dwcExportForm", "Ou"))
        self.btnPecheAappma.setText(_translate("dwcExportForm", "Ajouter"))
        self.btnPechePdpg.setText(_translate("dwcExportForm", "Ajouter"))
        self.btnPecheCeau.setText(_translate("dwcExportForm", "Ajouter"))
        self.btnPecheMeau.setText(_translate("dwcExportForm", "Ajouter"))
        self.btnPecheAnnee.setText(_translate("dwcExportForm", "Ajouter"))
        self.btnPecheEspece.setText(_translate("dwcExportForm", "Ajouter"))
        self.label_8.setText(_translate("dwcExportForm", "AAPPMA : "))
        self.label_17.setText(_translate("dwcExportForm", "Contexte PDPG : "))
        self.label_13.setText(_translate("dwcExportForm", "Cours d\'eau : "))
        self.label_14.setText(_translate("dwcExportForm", "Masse d\'eau : "))
        self.label_15.setText(_translate("dwcExportForm", "Année : "))
        self.datePecheAnnee.setDisplayFormat(_translate("dwcExportForm", "yyyy"))
        self.label_16.setText(_translate("dwcExportForm", "Espèces : "))
        self.groupBox_9.setTitle(_translate("dwcExportForm", "Choix des champs :"))
        self.chkDatePeche.setText(_translate("dwcExportForm", "Date"))
        self.chkLongueurPeche.setText(_translate("dwcExportForm", "Longueur"))
        self.chkProfondeur.setText(_translate("dwcExportForm", "Profondeur"))
        self.chkLargeurPeche.setText(_translate("dwcExportForm", "Largeur"))
        self.chkSurfacePeche.setText(_translate("dwcExportForm", "Surface"))
        self.chkPente.setText(_translate("dwcExportForm", "Pente"))
        self.chkXYPeche.setText(_translate("dwcExportForm", "X/Y"))
        self.chkNtt.setText(_translate("dwcExportForm", "Valeur NTT"))
        self.chkNttReel.setText(_translate("dwcExportForm", "NTT réel"))
        self.chkIpr.setText(_translate("dwcExportForm", "IPR"))
        self.chkIprCorrespond.setText(_translate("dwcExportForm", "Corr. IPR"))
        self.chkEspece.setText(_translate("dwcExportForm", "Espèce pêché"))
        self.chkBiomasse.setText(_translate("dwcExportForm", "Biomasse"))
        self.chkBioCorrespond.setText(_translate("dwcExportForm", "Corr. biomasse"))
        self.chkDensite.setText(_translate("dwcExportForm", "Densité"))
        self.chkDenCorrespond.setText(_translate("dwcExportForm", "Corr. densité"))
        self.chkComplet.setText(_translate("dwcExportForm", "Complet/partielle"))
        self.chkObservationPeche.setText(_translate("dwcExportForm", "Observation"))
        self.chkCeauPeche.setText(_translate("dwcExportForm", "Cours d\'eau"))
        self.chkMotif.setText(_translate("dwcExportForm", "Motif de pêche"))
        self.chkCondition.setText(_translate("dwcExportForm", "Condit° de pêche"))
        self.chkPdpgPeche.setText(_translate("dwcExportForm", "PDPG"))
        self.chkMeauPeche.setText(_translate("dwcExportForm", "Masse d\'eau"))
        self.chkMeauCodePeche.setText(_translate("dwcExportForm", "Code M. d\'eau"))
        self.chkCodePeche.setText(_translate("dwcExportForm", "Code opé"))
        self.chkStationPeche.setText(_translate("dwcExportForm", "Nom station"))
        self.chkDistancePeche.setText(_translate("dwcExportForm", "Dist. source"))
        self.chkAltitudePeche.setText(_translate("dwcExportForm", "Altitude"))
        self.chkAappmaPeche.setText(_translate("dwcExportForm", "AAPPMA"))
        self.chkSurfBVPeche.setText(_translate("dwcExportForm", "Surface BV"))
        self.chkMoaPeche.setText(_translate("dwcExportForm", "Maître d\'ouv."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabPeche), _translate("dwcExportForm", "Pêche électrique"))
        self.groupBox_6.setTitle(_translate("dwcExportForm", "Critères : "))
        self.btnThermiEt.setText(_translate("dwcExportForm", "Et"))
        self.btnThermiOu.setText(_translate("dwcExportForm", "Ou"))
        self.btnThermiAappma.setText(_translate("dwcExportForm", "Ajouter"))
        self.btnThermiPdpg.setText(_translate("dwcExportForm", "Ajouter"))
        self.btnThermiCeau.setText(_translate("dwcExportForm", "Ajouter"))
        self.btnThermiMeau.setText(_translate("dwcExportForm", "Ajouter"))
        self.btnThermiAnnee.setText(_translate("dwcExportForm", "Ajouter"))
        self.label_9.setText(_translate("dwcExportForm", "AAPPMA : "))
        self.label_18.setText(_translate("dwcExportForm", "Contexte PDPG : "))
        self.label_19.setText(_translate("dwcExportForm", "Cours d\'eau : "))
        self.label_20.setText(_translate("dwcExportForm", "Masse d\'eau : "))
        self.label_21.setText(_translate("dwcExportForm", "Année : "))
        self.dateThermiAnnee.setDisplayFormat(_translate("dwcExportForm", "yyyy"))
        self.groupBox_12.setTitle(_translate("dwcExportForm", "Choix des champs :"))
        self.chkDateDebut.setText(_translate("dwcExportForm", "Date de début"))
        self.chkDateFin.setText(_translate("dwcExportForm", "Date de fin"))
        self.chkDuree.setText(_translate("dwcExportForm", "Durée"))
        self.chkTimin.setText(_translate("dwcExportForm", "Ti min"))
        self.chkTimax.setText(_translate("dwcExportForm", "Ti max"))
        self.chkAjmaxTi.setText(_translate("dwcExportForm", "Ajmax Ti"))
        self.chkDAjmaxTi.setText(_translate("dwcExportForm", "Date Ajmax Ti"))
        self.chkTmjMin.setText(_translate("dwcExportForm", "Tmj min"))
        self.chkTmjMax.setText(_translate("dwcExportForm", "Tmj max"))
        self.chkTmpMoy.setText(_translate("dwcExportForm", "T°C moy"))
        self.chkTmj30Max.setText(_translate("dwcExportForm", "Tm30j  max"))
        self.chkNbjTmj419.setText(_translate("dwcExportForm", "Nbj Tmj 4-19"))
        self.chkP100Tmj419.setText(_translate("dwcExportForm", "%j Tmj 4-19"))
        self.chkP100TmjInf4.setText(_translate("dwcExportForm", "%j Tmj < 4"))
        self.chkP100TmjSup19.setText(_translate("dwcExportForm", "%j Tmj > 19"))
        self.chkNbMaxTiCsfSup19.setText(_translate("dwcExportForm", "Nbmax Ti csf > 19"))
        self.chkNbMaxTiCsfSupEg25.setText(_translate("dwcExportForm", "Nbmax Ti csf >= 25"))
        self.chkNbMaxTiCsfSupEg15.setText(_translate("dwcExportForm", "Nbmax Ti csf >= 15"))
        self.chkD50Ponte.setText(_translate("dwcExportForm", "Date 50 ponte"))
        self.chkNbjIncub.setText(_translate("dwcExportForm", "Nbj inc"))
        self.chkD50Eclo.setText(_translate("dwcExportForm", "Date 50 ecl"))
        self.chkNbjRsp.setText(_translate("dwcExportForm", "Nbj rsp"))
        self.chkD50Emg.setText(_translate("dwcExportForm", "Date 50 emg"))
        self.chkNbjPel.setText(_translate("dwcExportForm", "Nbj PEL"))
        self.chkNbTiSup15Pel.setText(_translate("dwcExportForm", "Nb Ti > 15 (PEL)"))
        self.chkNbMaxTiCsfSup15Pel.setText(_translate("dwcExportForm", "Nbmax Ti csf >15 (PEL)"))
        self.chkNbTiInf15Pel.setText(_translate("dwcExportForm", "Nb Ti < 1,5 (PEL)"))
        self.chkNbMaxTiCsfInf15Pel.setText(_translate("dwcExportForm", "Nbmax Ti csf <1,5 (PEL)"))
        self.chkCodeThermi.setText(_translate("dwcExportForm", "Code opé"))
        self.chkStationThermi.setText(_translate("dwcExportForm", "Nom station"))
        self.chkCeauThermi.setText(_translate("dwcExportForm", "Cours d\'eau"))
        self.chkXYStationThermi.setText(_translate("dwcExportForm", "X/Y Station"))
        self.chkXYSondeThermi.setText(_translate("dwcExportForm", "X/Y Sonde"))
        self.chkDistanceThermi.setText(_translate("dwcExportForm", "Dist. source"))
        self.chkAltitudeThermi.setText(_translate("dwcExportForm", "Altitude"))
        self.chkAappmaThermi.setText(_translate("dwcExportForm", "AAPPMA"))
        self.chkSurfBVThermi.setText(_translate("dwcExportForm", "Surface BV"))
        self.chkMoaThermi.setText(_translate("dwcExportForm", "Maître d\'ouvr."))
        self.chkMeauThermi.setText(_translate("dwcExportForm", "Masse d\'eau"))
        self.chkPdpgThermi.setText(_translate("dwcExportForm", "PDPG"))
        self.chkMeauCodeThermi.setText(_translate("dwcExportForm", "Code masse d\'eau"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabThermi), _translate("dwcExportForm", "Suivi thermique"))
        self.groupBox_7.setTitle(_translate("dwcExportForm", "Critères : "))
        self.btnReproEt.setText(_translate("dwcExportForm", "Et"))
        self.btnReproOu.setText(_translate("dwcExportForm", "Ou"))
        self.btnReproAappma.setText(_translate("dwcExportForm", "Ajouter"))
        self.btnReproPdpg.setText(_translate("dwcExportForm", "Ajouter"))
        self.btnReproCeau.setText(_translate("dwcExportForm", "Ajouter"))
        self.btnReproMeau.setText(_translate("dwcExportForm", "Ajouter"))
        self.btnReproAnnee.setText(_translate("dwcExportForm", "Ajouter"))
        self.label_10.setText(_translate("dwcExportForm", "AAPPMA : "))
        self.label_22.setText(_translate("dwcExportForm", "Contexte PDPG : "))
        self.label_24.setText(_translate("dwcExportForm", "Cours d\'eau : "))
        self.label_25.setText(_translate("dwcExportForm", "Masse d\'eau : "))
        self.label_26.setText(_translate("dwcExportForm", "Année : "))
        self.dateReproAnnee.setDisplayFormat(_translate("dwcExportForm", "yyyy"))
        self.groupBox_10.setTitle(_translate("dwcExportForm", "Choix des champs :"))
        self.chkDateRepro.setText(_translate("dwcExportForm", "Date"))
        self.chkPassage.setText(_translate("dwcExportForm", "Nbre de passage"))
        self.chkSgf.setText(_translate("dwcExportForm", "SGF"))
        self.chkZfp.setText(_translate("dwcExportForm", "ZFP"))
        self.chkFrayere.setText(_translate("dwcExportForm", "Nbre de frayère"))
        self.chkSurfaceFrayere.setText(_translate("dwcExportForm", "Surf. de frayère"))
        self.chkXYAvalRepro.setText(_translate("dwcExportForm", "X/Y Aval"))
        self.chkXYStationRepro.setText(_translate("dwcExportForm", "X/Y Station"))
        self.chkBaran.setText(_translate("dwcExportForm", "Valeur Baran"))
        self.chkBaranCorrespond.setText(_translate("dwcExportForm", "Corres. Baran"))
        self.chkLargeurRepro.setText(_translate("dwcExportForm", "Largeur"))
        self.chkLongueurRepro.setText(_translate("dwcExportForm", "Longueur"))
        self.chkCeauRepro.setText(_translate("dwcExportForm", "Cours d\'eau"))
        self.chkPdpgRepro.setText(_translate("dwcExportForm", "PDPG"))
        self.chkMeauRepro.setText(_translate("dwcExportForm", "Masse d\'eau"))
        self.chkMeauCodeRepro.setText(_translate("dwcExportForm", "Code M. d\'eau"))
        self.chkMoaRepro.setText(_translate("dwcExportForm", "Maître d\'ouvr."))
        self.chkCodeRepro.setText(_translate("dwcExportForm", "Code opé"))
        self.chkStationRepro.setText(_translate("dwcExportForm", "Nom station"))
        self.chkDistanceRepro.setText(_translate("dwcExportForm", "Dist. source"))
        self.chkAltitudeRepro.setText(_translate("dwcExportForm", "Altitude"))
        self.chkAappmaRepro.setText(_translate("dwcExportForm", "AAPPMA"))
        self.chkSurfBVRepro.setText(_translate("dwcExportForm", "Surface BV"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabRepro), _translate("dwcExportForm", "Inventaire de reproduction"))
        self.groupBox_2.setTitle(_translate("dwcExportForm", "Prévisualisation : "))
        self.groupBox_4.setTitle(_translate("dwcExportForm", "Requête SQL :"))
        self.label_7.setText(_translate("dwcExportForm", "<html><head/><body><p align=\"justify\"><span style=\" font-size:7pt;\">Attention : les modifications dans la requête sont possibles mais peuvent faire échouer celle-ci voir endommager la base de données ! ! !</span></p></body></html>"))
        self.btnPreviRequete.setText(_translate("dwcExportForm", "Prévisualiser la requête"))
        self.btnPreviResu.setText(_translate("dwcExportForm", "Prévisualiser le résultat"))
        self.btnRaz.setText(_translate("dwcExportForm", "Réinitialiser"))
        self.btnEnregistrer.setText(_translate("dwcExportForm", "Exporter en CSV"))

import ressourceGedopi_rc
