# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms\opeInventaireForm.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dwcInventMainForm(object):
    def setupUi(self, dwcInventMainForm):
        dwcInventMainForm.setObjectName("dwcInventMainForm")
        dwcInventMainForm.resize(518, 528)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(dwcInventMainForm.sizePolicy().hasHeightForWidth())
        dwcInventMainForm.setSizePolicy(sizePolicy)
        dwcInventMainForm.setMinimumSize(QtCore.QSize(518, 300))
        self.dwc_inventaire_form = QtWidgets.QWidget()
        self.dwc_inventaire_form.setObjectName("dwc_inventaire_form")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.dwc_inventaire_form)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.scrollArea = QtWidgets.QScrollArea(self.dwc_inventaire_form)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -218, 483, 687))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setContentsMargins(0, 1, 0, 1)
        self.horizontalLayout_21.setSpacing(2)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.btnFiltreCartoManuel = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnFiltreCartoManuel.setEnabled(False)
        self.btnFiltreCartoManuel.setMinimumSize(QtCore.QSize(120, 30))
        self.btnFiltreCartoManuel.setObjectName("btnFiltreCartoManuel")
        self.horizontalLayout_21.addWidget(self.btnFiltreCartoManuel)
        self.chkFiltreCartoAuto = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.chkFiltreCartoAuto.setMinimumSize(QtCore.QSize(130, 0))
        self.chkFiltreCartoAuto.setObjectName("chkFiltreCartoAuto")
        self.horizontalLayout_21.addWidget(self.chkFiltreCartoAuto)
        self.btnFiltreAttributaire = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnFiltreAttributaire.setMinimumSize(QtCore.QSize(97, 30))
        self.btnFiltreAttributaire.setObjectName("btnFiltreAttributaire")
        self.horizontalLayout_21.addWidget(self.btnFiltreAttributaire)
        self.btnDeleteFiltrage = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnDeleteFiltrage.setEnabled(False)
        self.btnDeleteFiltrage.setMinimumSize(QtCore.QSize(110, 30))
        self.btnDeleteFiltrage.setObjectName("btnDeleteFiltrage")
        self.horizontalLayout_21.addWidget(self.btnDeleteFiltrage)
        self.verticalLayout_7.addLayout(self.horizontalLayout_21)
        self.chkVerrouAuto = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.chkVerrouAuto.setChecked(True)
        self.chkVerrouAuto.setObjectName("chkVerrouAuto")
        self.verticalLayout_7.addWidget(self.chkVerrouAuto)
        self.chkVerrouModif = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.chkVerrouModif.setChecked(True)
        self.chkVerrouModif.setObjectName("chkVerrouModif")
        self.verticalLayout_7.addWidget(self.chkVerrouModif)
        self.groupBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lbl_commune = QtWidgets.QLabel(self.groupBox_2)
        self.lbl_commune.setObjectName("lbl_commune")
        self.horizontalLayout_3.addWidget(self.lbl_commune)
        self.cmbRiviere = QtWidgets.QComboBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbRiviere.sizePolicy().hasHeightForWidth())
        self.cmbRiviere.setSizePolicy(sizePolicy)
        self.cmbRiviere.setMinimumSize(QtCore.QSize(170, 0))
        self.cmbRiviere.setObjectName("cmbRiviere")
        self.horizontalLayout_3.addWidget(self.cmbRiviere)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.btnStation = QtWidgets.QPushButton(self.groupBox_2)
        self.btnStation.setObjectName("btnStation")
        self.horizontalLayout_6.addWidget(self.btnStation)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lbl_section = QtWidgets.QLabel(self.groupBox_2)
        self.lbl_section.setMinimumSize(QtCore.QSize(50, 0))
        self.lbl_section.setObjectName("lbl_section")
        self.horizontalLayout_5.addWidget(self.lbl_section)
        self.cmbStation = QtWidgets.QComboBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbStation.sizePolicy().hasHeightForWidth())
        self.cmbStation.setSizePolicy(sizePolicy)
        self.cmbStation.setObjectName("cmbStation")
        self.horizontalLayout_5.addWidget(self.cmbStation)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.verticalLayout_7.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.btnGeom = QtWidgets.QPushButton(self.groupBox_3)
        self.btnGeom.setMinimumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.btnGeom.setFont(font)
        self.btnGeom.setStyleSheet("color: rgb(231, 0, 0)")
        self.btnGeom.setCheckable(True)
        self.btnGeom.setObjectName("btnGeom")
        self.horizontalLayout_7.addWidget(self.btnGeom)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.leCodeOpe = QtWidgets.QLineEdit(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leCodeOpe.sizePolicy().hasHeightForWidth())
        self.leCodeOpe.setSizePolicy(sizePolicy)
        self.leCodeOpe.setAlignment(QtCore.Qt.AlignCenter)
        self.leCodeOpe.setProperty("", False)
        self.leCodeOpe.setObjectName("leCodeOpe")
        self.horizontalLayout_8.addWidget(self.leCodeOpe)
        self.horizontalLayout_16.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_21 = QtWidgets.QLabel(self.groupBox_3)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_20.addWidget(self.label_21)
        self.txtDate = QtWidgets.QTextEdit(self.groupBox_3)
        self.txtDate.setMaximumSize(QtCore.QSize(16777215, 50))
        self.txtDate.setObjectName("txtDate")
        self.horizontalLayout_20.addWidget(self.txtDate)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem3)
        self.horizontalLayout_16.addLayout(self.horizontalLayout_20)
        self.verticalLayout_2.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_28 = QtWidgets.QLabel(self.groupBox_3)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_2.addWidget(self.label_28)
        self.tbvMoa = QtWidgets.QTableView(self.groupBox_3)
        self.tbvMoa.setMaximumSize(QtCore.QSize(16777215, 70))
        self.tbvMoa.setObjectName("tbvMoa")
        self.horizontalLayout_2.addWidget(self.tbvMoa)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.btnAjoutMoa = QtWidgets.QPushButton(self.groupBox_3)
        self.btnAjoutMoa.setMaximumSize(QtCore.QSize(25, 16777215))
        self.btnAjoutMoa.setObjectName("btnAjoutMoa")
        self.verticalLayout_5.addWidget(self.btnAjoutMoa)
        self.btnSuppMoa = QtWidgets.QPushButton(self.groupBox_3)
        self.btnSuppMoa.setMaximumSize(QtCore.QSize(25, 16777215))
        self.btnSuppMoa.setObjectName("btnSuppMoa")
        self.verticalLayout_5.addWidget(self.btnSuppMoa)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.btnExcel = QtWidgets.QPushButton(self.groupBox_3)
        self.btnExcel.setObjectName("btnExcel")
        self.horizontalLayout_9.addWidget(self.btnExcel)
        self.btnAjoutFiche = QtWidgets.QPushButton(self.groupBox_3)
        self.btnAjoutFiche.setMinimumSize(QtCore.QSize(65, 0))
        self.btnAjoutFiche.setMaximumSize(QtCore.QSize(65, 20))
        self.btnAjoutFiche.setObjectName("btnAjoutFiche")
        self.horizontalLayout_9.addWidget(self.btnAjoutFiche)
        self.btnRetraitFiche = QtWidgets.QPushButton(self.groupBox_3)
        self.btnRetraitFiche.setMinimumSize(QtCore.QSize(65, 0))
        self.btnRetraitFiche.setMaximumSize(QtCore.QSize(65, 20))
        self.btnRetraitFiche.setObjectName("btnRetraitFiche")
        self.horizontalLayout_9.addWidget(self.btnRetraitFiche)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout.addWidget(self.label_10)
        self.spnPassage = QtWidgets.QSpinBox(self.groupBox_3)
        self.spnPassage.setObjectName("spnPassage")
        self.horizontalLayout.addWidget(self.spnPassage)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_12.addWidget(self.label_13)
        self.spnLongueur = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.spnLongueur.setMaximum(99999.99)
        self.spnLongueur.setObjectName("spnLongueur")
        self.horizontalLayout_12.addWidget(self.spnLongueur)
        self.horizontalLayout_34.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_15 = QtWidgets.QLabel(self.groupBox_3)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_14.addWidget(self.label_15)
        self.spnLargeur = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.spnLargeur.setDecimals(1)
        self.spnLargeur.setMaximum(200.0)
        self.spnLargeur.setObjectName("spnLargeur")
        self.horizontalLayout_14.addWidget(self.spnLargeur)
        self.horizontalLayout_34.addLayout(self.horizontalLayout_14)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_34.addItem(spacerItem6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_34)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_26 = QtWidgets.QLabel(self.groupBox_3)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_15.addWidget(self.label_26)
        self.spnSgf = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.spnSgf.setMaximum(999.99)
        self.spnSgf.setObjectName("spnSgf")
        self.horizontalLayout_15.addWidget(self.spnSgf)
        self.horizontalLayout_19.addLayout(self.horizontalLayout_15)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_24 = QtWidgets.QLabel(self.groupBox_3)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_17.addWidget(self.label_24)
        self.spnZfp = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.spnZfp.setMaximum(999.99)
        self.spnZfp.setObjectName("spnZfp")
        self.horizontalLayout_17.addWidget(self.spnZfp)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem8)
        self.verticalLayout_2.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_25 = QtWidgets.QLabel(self.groupBox_3)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_24.addWidget(self.label_25)
        self.spnNbreFrayere = QtWidgets.QSpinBox(self.groupBox_3)
        self.spnNbreFrayere.setMaximum(9999)
        self.spnNbreFrayere.setObjectName("spnNbreFrayere")
        self.horizontalLayout_24.addWidget(self.spnNbreFrayere)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_29 = QtWidgets.QLabel(self.groupBox_3)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_28.addWidget(self.label_29)
        self.spnSurfFrayere = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.spnSurfFrayere.setMaximum(999.99)
        self.spnSurfFrayere.setObjectName("spnSurfFrayere")
        self.horizontalLayout_28.addWidget(self.spnSurfFrayere)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_28)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem9)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_27 = QtWidgets.QLabel(self.groupBox_3)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_26.addWidget(self.label_27)
        self.spnBaran = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.spnBaran.setObjectName("spnBaran")
        self.horizontalLayout_26.addWidget(self.spnBaran)
        self.horizontalLayout_31.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_17 = QtWidgets.QLabel(self.groupBox_3)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_29.addWidget(self.label_17)
        self.cmbBaran = QtWidgets.QComboBox(self.groupBox_3)
        self.cmbBaran.setMaximumSize(QtCore.QSize(100, 16777215))
        self.cmbBaran.setObjectName("cmbBaran")
        self.horizontalLayout_29.addWidget(self.cmbBaran)
        self.horizontalLayout_31.addLayout(self.horizontalLayout_29)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_31.addItem(spacerItem10)
        self.verticalLayout_2.addLayout(self.horizontalLayout_31)
        self.verticalLayout_7.addWidget(self.groupBox_3)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.btnPrec = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnPrec.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btnPrec.setObjectName("btnPrec")
        self.horizontalLayout_36.addWidget(self.btnPrec)
        self.btnPremier = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnPremier.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btnPremier.setObjectName("btnPremier")
        self.horizontalLayout_36.addWidget(self.btnPremier)
        self.btnDernier = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnDernier.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btnDernier.setObjectName("btnDernier")
        self.horizontalLayout_36.addWidget(self.btnDernier)
        self.btnSuiv = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnSuiv.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btnSuiv.setObjectName("btnSuiv")
        self.horizontalLayout_36.addWidget(self.btnSuiv)
        self.horizontalLayout_22.addLayout(self.horizontalLayout_36)
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.btnZoom = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnZoom.setMinimumSize(QtCore.QSize(50, 36))
        self.btnZoom.setMaximumSize(QtCore.QSize(100, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/icons/zoom.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnZoom.setIcon(icon)
        self.btnZoom.setObjectName("btnZoom")
        self.horizontalLayout_38.addWidget(self.btnZoom)
        self.btnSelection = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnSelection.setMinimumSize(QtCore.QSize(50, 36))
        self.btnSelection.setMaximumSize(QtCore.QSize(100, 16777215))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/icons/select.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSelection.setIcon(icon1)
        self.btnSelection.setObjectName("btnSelection")
        self.horizontalLayout_38.addWidget(self.btnSelection)
        self.horizontalLayout_22.addLayout(self.horizontalLayout_38)
        self.horizontalLayout_18.addLayout(self.horizontalLayout_22)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem11)
        self.verticalLayout_7.addLayout(self.horizontalLayout_18)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.btnNouveau = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.btnNouveau.setFont(font)
        self.btnNouveau.setStyleSheet("color: rgb(0, 170, 0);")
        self.btnNouveau.setObjectName("btnNouveau")
        self.horizontalLayout_23.addWidget(self.btnNouveau)
        self.btnModif = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.btnModif.setFont(font)
        self.btnModif.setStyleSheet("color: rgb(85, 0, 255);")
        self.btnModif.setObjectName("btnModif")
        self.horizontalLayout_23.addWidget(self.btnModif)
        self.btnSupprimer = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.btnSupprimer.setFont(font)
        self.btnSupprimer.setStyleSheet("color: rgb(231, 0, 0);")
        self.btnSupprimer.setObjectName("btnSupprimer")
        self.horizontalLayout_23.addWidget(self.btnSupprimer)
        self.btnEnregistrer = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnEnregistrer.setObjectName("btnEnregistrer")
        self.horizontalLayout_23.addWidget(self.btnEnregistrer)
        self.btnAnnuler = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnAnnuler.setObjectName("btnAnnuler")
        self.horizontalLayout_23.addWidget(self.btnAnnuler)
        self.verticalLayout.addLayout(self.horizontalLayout_23)
        self.verticalLayout_7.addLayout(self.verticalLayout)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_6.addWidget(self.scrollArea)
        dwcInventMainForm.setWidget(self.dwc_inventaire_form)

        self.retranslateUi(dwcInventMainForm)
        QtCore.QMetaObject.connectSlotsByName(dwcInventMainForm)

    def retranslateUi(self, dwcInventMainForm):
        _translate = QtCore.QCoreApplication.translate
        dwcInventMainForm.setWindowTitle(_translate("dwcInventMainForm", "Gedopi - Inventaire de reproduction"))
        self.btnFiltreCartoManuel.setText(_translate("dwcInventMainForm", "Filtre carto manuel"))
        self.chkFiltreCartoAuto.setText(_translate("dwcInventMainForm", "filtre carto automatique"))
        self.btnFiltreAttributaire.setText(_translate("dwcInventMainForm", "Filtre attributaire"))
        self.btnDeleteFiltrage.setText(_translate("dwcInventMainForm", "Suppression filtrage"))
        self.chkVerrouAuto.setText(_translate("dwcInventMainForm", "* Verrouillage des champs automatiques"))
        self.chkVerrouModif.setText(_translate("dwcInventMainForm", "Verrouillage modification"))
        self.groupBox_2.setTitle(_translate("dwcInventMainForm", "Station"))
        self.lbl_commune.setText(_translate("dwcInventMainForm", "Rivière :"))
        self.btnStation.setText(_translate("dwcInventMainForm", "Fiche complète"))
        self.lbl_section.setText(_translate("dwcInventMainForm", "<html><head/><body><p>Station <span style=\" font-size:7pt;\">(ID ; Nom)</span> :</p></body></html>"))
        self.groupBox_3.setTitle(_translate("dwcInventMainForm", "Information sur l\'inventaire"))
        self.btnGeom.setText(_translate("dwcInventMainForm", "Placement de l\'inventaire (2 points)"))
        self.label_8.setText(_translate("dwcInventMainForm", "Code opération :"))
        self.label_21.setText(_translate("dwcInventMainForm", "Date :"))
        self.txtDate.setHtml(_translate("dwcInventMainForm", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p></body></html>"))
        self.label_28.setText(_translate("dwcInventMainForm", "Maître(s) d\'ouvrage :"))
        self.btnAjoutMoa.setText(_translate("dwcInventMainForm", "+"))
        self.btnSuppMoa.setText(_translate("dwcInventMainForm", "-"))
        self.btnExcel.setText(_translate("dwcInventMainForm", "Fiche Externe"))
        self.btnAjoutFiche.setText(_translate("dwcInventMainForm", "Lier fiche"))
        self.btnRetraitFiche.setText(_translate("dwcInventMainForm", "Délier fiche"))
        self.label_10.setText(_translate("dwcInventMainForm", "Nombre de passages :"))
        self.label_13.setText(_translate("dwcInventMainForm", "* Longueur prospectée (m) :"))
        self.label_15.setText(_translate("dwcInventMainForm", "Largeur moyenne (m) :"))
        self.label_26.setText(_translate("dwcInventMainForm", "Surface granulométrique favorable (m²) :"))
        self.label_24.setText(_translate("dwcInventMainForm", "Surface de frayère potentielle (m²) :"))
        self.label_25.setText(_translate("dwcInventMainForm", "Nombre de frayères :"))
        self.label_29.setText(_translate("dwcInventMainForm", "Surface de frayères (m²) :"))
        self.label_27.setText(_translate("dwcInventMainForm", "Valeur Baran :"))
        self.label_17.setText(_translate("dwcInventMainForm", "Correspondance Baran :"))
        self.btnPrec.setText(_translate("dwcInventMainForm", "<"))
        self.btnPremier.setText(_translate("dwcInventMainForm", "<<"))
        self.btnDernier.setText(_translate("dwcInventMainForm", ">>"))
        self.btnSuiv.setText(_translate("dwcInventMainForm", ">"))
        self.btnZoom.setToolTip(_translate("dwcInventMainForm", "Zoomer sur l\'objet"))
        self.btnSelection.setToolTip(_translate("dwcInventMainForm", "Sélectionner l\'objet"))
        self.btnNouveau.setText(_translate("dwcInventMainForm", "Nouveau"))
        self.btnModif.setText(_translate("dwcInventMainForm", "Enreg. Modif"))
        self.btnSupprimer.setText(_translate("dwcInventMainForm", "Supprimer"))
        self.btnEnregistrer.setText(_translate("dwcInventMainForm", "Enregistrer"))
        self.btnAnnuler.setText(_translate("dwcInventMainForm", "Abandonner"))

import ressourceGedopi_rc
