# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms\opePechePoissonForm.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dlgPecheSaisieForm(object):
    def setupUi(self, dlgPecheSaisieForm):
        dlgPecheSaisieForm.setObjectName("dlgPecheSaisieForm")
        dlgPecheSaisieForm.resize(452, 162)
        self.verticalLayout = QtWidgets.QVBoxLayout(dlgPecheSaisieForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(dlgPecheSaisieForm)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 432, 142))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_50 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_50.setObjectName("horizontalLayout_50")
        self.horizontalLayout_46 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_46.setObjectName("horizontalLayout_46")
        self.label_34 = QtWidgets.QLabel(self.groupBox)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_46.addWidget(self.label_34)
        self.cmbEspece = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbEspece.sizePolicy().hasHeightForWidth())
        self.cmbEspece.setSizePolicy(sizePolicy)
        self.cmbEspece.setObjectName("cmbEspece")
        self.horizontalLayout_46.addWidget(self.cmbEspece)
        self.horizontalLayout_50.addLayout(self.horizontalLayout_46)
        self.horizontalLayout_47 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_47.setObjectName("horizontalLayout_47")
        self.label_35 = QtWidgets.QLabel(self.groupBox)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_47.addWidget(self.label_35)
        self.spnQuantite = QtWidgets.QSpinBox(self.groupBox)
        self.spnQuantite.setMaximum(9999)
        self.spnQuantite.setObjectName("spnQuantite")
        self.horizontalLayout_47.addWidget(self.spnQuantite)
        self.horizontalLayout_50.addLayout(self.horizontalLayout_47)
        self.verticalLayout_7.addLayout(self.horizontalLayout_50)
        self.horizontalLayout_51 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_51.setObjectName("horizontalLayout_51")
        self.horizontalLayout_48 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_48.setObjectName("horizontalLayout_48")
        self.label_36 = QtWidgets.QLabel(self.groupBox)
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_48.addWidget(self.label_36)
        self.spnDensite = QtWidgets.QSpinBox(self.groupBox)
        self.spnDensite.setMinimum(-1)
        self.spnDensite.setMaximum(99999)
        self.spnDensite.setProperty("value", -1)
        self.spnDensite.setObjectName("spnDensite")
        self.horizontalLayout_48.addWidget(self.spnDensite)
        self.horizontalLayout_51.addLayout(self.horizontalLayout_48)
        self.horizontalLayout_49 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_49.setObjectName("horizontalLayout_49")
        self.label_37 = QtWidgets.QLabel(self.groupBox)
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_49.addWidget(self.label_37)
        self.spnBiomasse = QtWidgets.QSpinBox(self.groupBox)
        self.spnBiomasse.setMinimum(-1)
        self.spnBiomasse.setMaximum(9999)
        self.spnBiomasse.setProperty("value", -1)
        self.spnBiomasse.setObjectName("spnBiomasse")
        self.horizontalLayout_49.addWidget(self.spnBiomasse)
        self.horizontalLayout_51.addLayout(self.horizontalLayout_49)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_51.addItem(spacerItem)
        self.verticalLayout_7.addLayout(self.horizontalLayout_51)
        self.verticalLayout_11.addLayout(self.verticalLayout_7)
        self.verticalLayout_15.addWidget(self.groupBox)
        self.btnBox = QtWidgets.QDialogButtonBox(self.scrollAreaWidgetContents)
        self.btnBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.btnBox.setCenterButtons(True)
        self.btnBox.setObjectName("btnBox")
        self.verticalLayout_15.addWidget(self.btnBox)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(dlgPecheSaisieForm)
        QtCore.QMetaObject.connectSlotsByName(dlgPecheSaisieForm)

    def retranslateUi(self, dlgPecheSaisieForm):
        _translate = QtCore.QCoreApplication.translate
        dlgPecheSaisieForm.setWindowTitle(_translate("dlgPecheSaisieForm", "Saisie des résultats"))
        self.groupBox.setTitle(_translate("dlgPecheSaisieForm", "Espèce(s) :"))
        self.label_34.setText(_translate("dlgPecheSaisieForm", "Espèce :"))
        self.label_35.setText(_translate("dlgPecheSaisieForm", "Quantité :"))
        self.label_36.setText(_translate("dlgPecheSaisieForm", "Densité :"))
        self.spnDensite.setSpecialValueText(_translate("dlgPecheSaisieForm", "NaN"))
        self.label_37.setText(_translate("dlgPecheSaisieForm", "Biomasse :"))
        self.spnBiomasse.setSpecialValueText(_translate("dlgPecheSaisieForm", "NaN"))

