# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms\opeSuiviThermiForm.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dwcThermiMainForm(object):
    def setupUi(self, dwcThermiMainForm):
        dwcThermiMainForm.setObjectName("dwcThermiMainForm")
        dwcThermiMainForm.resize(518, 528)
        dwcThermiMainForm.setMinimumSize(QtCore.QSize(518, 300))
        self.dwc_thermi_form = QtWidgets.QWidget()
        self.dwc_thermi_form.setObjectName("dwc_thermi_form")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.dwc_thermi_form)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.dwc_thermi_form)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -305, 491, 1140))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(0, 1, 0, 1)
        self.horizontalLayout_10.setSpacing(2)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.btnFiltreCartoManuel = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnFiltreCartoManuel.setEnabled(False)
        self.btnFiltreCartoManuel.setMinimumSize(QtCore.QSize(120, 30))
        self.btnFiltreCartoManuel.setObjectName("btnFiltreCartoManuel")
        self.horizontalLayout_10.addWidget(self.btnFiltreCartoManuel)
        self.chkFiltreCartoAuto = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.chkFiltreCartoAuto.setMinimumSize(QtCore.QSize(130, 0))
        self.chkFiltreCartoAuto.setObjectName("chkFiltreCartoAuto")
        self.horizontalLayout_10.addWidget(self.chkFiltreCartoAuto)
        self.btnFiltreAttributaire = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnFiltreAttributaire.setMinimumSize(QtCore.QSize(97, 30))
        self.btnFiltreAttributaire.setObjectName("btnFiltreAttributaire")
        self.horizontalLayout_10.addWidget(self.btnFiltreAttributaire)
        self.btnDeleteFiltrage = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnDeleteFiltrage.setEnabled(False)
        self.btnDeleteFiltrage.setMinimumSize(QtCore.QSize(110, 30))
        self.btnDeleteFiltrage.setObjectName("btnDeleteFiltrage")
        self.horizontalLayout_10.addWidget(self.btnDeleteFiltrage)
        self.verticalLayout_6.addLayout(self.horizontalLayout_10)
        self.chkVerrouAuto = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.chkVerrouAuto.setChecked(True)
        self.chkVerrouAuto.setObjectName("chkVerrouAuto")
        self.verticalLayout_6.addWidget(self.chkVerrouAuto)
        self.chkVerrouModif = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.chkVerrouModif.setChecked(True)
        self.chkVerrouModif.setObjectName("chkVerrouModif")
        self.verticalLayout_6.addWidget(self.chkVerrouModif)
        self.groupBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lbl_commune = QtWidgets.QLabel(self.groupBox_2)
        self.lbl_commune.setObjectName("lbl_commune")
        self.horizontalLayout_3.addWidget(self.lbl_commune)
        self.cmbRiviere = QtWidgets.QComboBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbRiviere.sizePolicy().hasHeightForWidth())
        self.cmbRiviere.setSizePolicy(sizePolicy)
        self.cmbRiviere.setMinimumSize(QtCore.QSize(170, 0))
        self.cmbRiviere.setObjectName("cmbRiviere")
        self.horizontalLayout_3.addWidget(self.cmbRiviere)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.btnStation = QtWidgets.QPushButton(self.groupBox_2)
        self.btnStation.setObjectName("btnStation")
        self.horizontalLayout_6.addWidget(self.btnStation)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_6)
        self.verticalLayout_9.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lbl_section = QtWidgets.QLabel(self.groupBox_2)
        self.lbl_section.setMinimumSize(QtCore.QSize(50, 0))
        self.lbl_section.setObjectName("lbl_section")
        self.horizontalLayout_5.addWidget(self.lbl_section)
        self.cmbStation = QtWidgets.QComboBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbStation.sizePolicy().hasHeightForWidth())
        self.cmbStation.setSizePolicy(sizePolicy)
        self.cmbStation.setObjectName("cmbStation")
        self.horizontalLayout_5.addWidget(self.cmbStation)
        self.verticalLayout_9.addLayout(self.horizontalLayout_5)
        self.verticalLayout_6.addWidget(self.groupBox_2)
        self.groupBox_4 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.btnCoordonnee = QtWidgets.QPushButton(self.groupBox_4)
        self.btnCoordonnee.setMinimumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.btnCoordonnee.setFont(font)
        self.btnCoordonnee.setStyleSheet("color: rgb(231, 0, 0)")
        self.btnCoordonnee.setObjectName("btnCoordonnee")
        self.horizontalLayout_7.addWidget(self.btnCoordonnee)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_19 = QtWidgets.QLabel(self.groupBox_4)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_20.addWidget(self.label_19)
        self.leCodeOpe = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leCodeOpe.sizePolicy().hasHeightForWidth())
        self.leCodeOpe.setSizePolicy(sizePolicy)
        self.leCodeOpe.setAlignment(QtCore.Qt.AlignCenter)
        self.leCodeOpe.setObjectName("leCodeOpe")
        self.horizontalLayout_20.addWidget(self.leCodeOpe)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_21 = QtWidgets.QLabel(self.groupBox_4)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_19.addWidget(self.label_21)
        self.dateDebut = QtWidgets.QDateEdit(self.groupBox_4)
        self.dateDebut.setCalendarPopup(True)
        self.dateDebut.setObjectName("dateDebut")
        self.horizontalLayout_19.addWidget(self.dateDebut)
        self.horizontalLayout_23.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_20 = QtWidgets.QLabel(self.groupBox_4)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_21.addWidget(self.label_20)
        self.dateFin = QtWidgets.QDateEdit(self.groupBox_4)
        self.dateFin.setCalendarPopup(True)
        self.dateFin.setObjectName("dateFin")
        self.horizontalLayout_21.addWidget(self.dateFin)
        self.horizontalLayout_23.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_22 = QtWidgets.QLabel(self.groupBox_4)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_22.addWidget(self.label_22)
        self.spnDuree = QtWidgets.QSpinBox(self.groupBox_4)
        self.spnDuree.setMaximum(999)
        self.spnDuree.setObjectName("spnDuree")
        self.horizontalLayout_22.addWidget(self.spnDuree)
        self.horizontalLayout_23.addLayout(self.horizontalLayout_22)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_23)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_28 = QtWidgets.QLabel(self.groupBox_4)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout.addWidget(self.label_28)
        self.tbvMoa = QtWidgets.QTableView(self.groupBox_4)
        self.tbvMoa.setMinimumSize(QtCore.QSize(310, 0))
        self.tbvMoa.setMaximumSize(QtCore.QSize(16777215, 70))
        self.tbvMoa.setObjectName("tbvMoa")
        self.horizontalLayout.addWidget(self.tbvMoa)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.btnAjoutMoa = QtWidgets.QPushButton(self.groupBox_4)
        self.btnAjoutMoa.setMaximumSize(QtCore.QSize(25, 16777215))
        self.btnAjoutMoa.setObjectName("btnAjoutMoa")
        self.verticalLayout_7.addWidget(self.btnAjoutMoa)
        self.btnSuppMoa = QtWidgets.QPushButton(self.groupBox_4)
        self.btnSuppMoa.setMaximumSize(QtCore.QSize(25, 16777215))
        self.btnSuppMoa.setObjectName("btnSuppMoa")
        self.verticalLayout_7.addWidget(self.btnSuppMoa)
        self.horizontalLayout.addLayout(self.verticalLayout_7)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.btnExcel = QtWidgets.QPushButton(self.groupBox_4)
        self.btnExcel.setObjectName("btnExcel")
        self.horizontalLayout_11.addWidget(self.btnExcel)
        self.btnAjoutFiche = QtWidgets.QPushButton(self.groupBox_4)
        self.btnAjoutFiche.setMinimumSize(QtCore.QSize(65, 0))
        self.btnAjoutFiche.setMaximumSize(QtCore.QSize(65, 20))
        self.btnAjoutFiche.setObjectName("btnAjoutFiche")
        self.horizontalLayout_11.addWidget(self.btnAjoutFiche)
        self.btnRetraitFiche = QtWidgets.QPushButton(self.groupBox_4)
        self.btnRetraitFiche.setMinimumSize(QtCore.QSize(65, 0))
        self.btnRetraitFiche.setMaximumSize(QtCore.QSize(65, 20))
        self.btnRetraitFiche.setObjectName("btnRetraitFiche")
        self.horizontalLayout_11.addWidget(self.btnRetraitFiche)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem5)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.verticalLayout_6.addWidget(self.groupBox_4)
        self.groupBox_5 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnImpCsv = QtWidgets.QPushButton(self.groupBox_5)
        self.btnImpCsv.setMinimumSize(QtCore.QSize(100, 30))
        self.btnImpCsv.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.btnImpCsv.setFont(font)
        self.btnImpCsv.setStyleSheet("color: rgb(231, 0, 0)")
        self.btnImpCsv.setObjectName("btnImpCsv")
        self.horizontalLayout_2.addWidget(self.btnImpCsv)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_58 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_58.setObjectName("horizontalLayout_58")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_23 = QtWidgets.QLabel(self.groupBox_5)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_25.addWidget(self.label_23)
        self.spnTiMin = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.spnTiMin.setDecimals(1)
        self.spnTiMin.setMaximum(99.0)
        self.spnTiMin.setObjectName("spnTiMin")
        self.horizontalLayout_25.addWidget(self.spnTiMin)
        self.horizontalLayout_58.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_25 = QtWidgets.QLabel(self.groupBox_5)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_27.addWidget(self.label_25)
        self.spnTiMax = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.spnTiMax.setDecimals(1)
        self.spnTiMax.setMaximum(99.0)
        self.spnTiMax.setObjectName("spnTiMax")
        self.horizontalLayout_27.addWidget(self.spnTiMax)
        self.horizontalLayout_58.addLayout(self.horizontalLayout_27)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_58.addItem(spacerItem7)
        self.verticalLayout_3.addLayout(self.horizontalLayout_58)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_26 = QtWidgets.QLabel(self.groupBox_5)
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_28.addWidget(self.label_26)
        self.spnAjmaxTi = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.spnAjmaxTi.setDecimals(1)
        self.spnAjmaxTi.setMaximum(99.0)
        self.spnAjmaxTi.setObjectName("spnAjmaxTi")
        self.horizontalLayout_28.addWidget(self.spnAjmaxTi)
        self.horizontalLayout_30.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_27 = QtWidgets.QLabel(self.groupBox_5)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_29.addWidget(self.label_27)
        self.dateAjmaxTi = QtWidgets.QDateEdit(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateAjmaxTi.sizePolicy().hasHeightForWidth())
        self.dateAjmaxTi.setSizePolicy(sizePolicy)
        self.dateAjmaxTi.setCalendarPopup(True)
        self.dateAjmaxTi.setObjectName("dateAjmaxTi")
        self.horizontalLayout_29.addWidget(self.dateAjmaxTi)
        self.horizontalLayout_30.addLayout(self.horizontalLayout_29)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_30.addItem(spacerItem8)
        self.verticalLayout_3.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.label_32 = QtWidgets.QLabel(self.groupBox_5)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_31.addWidget(self.label_32)
        self.spnTmjMin = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.spnTmjMin.setDecimals(1)
        self.spnTmjMin.setMaximum(99.0)
        self.spnTmjMin.setObjectName("spnTmjMin")
        self.horizontalLayout_31.addWidget(self.spnTmjMin)
        self.horizontalLayout_36.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.label_33 = QtWidgets.QLabel(self.groupBox_5)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_34.addWidget(self.label_33)
        self.spnTmjMax = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.spnTmjMax.setDecimals(1)
        self.spnTmjMax.setMaximum(99.0)
        self.spnTmjMax.setObjectName("spnTmjMax")
        self.horizontalLayout_34.addWidget(self.spnTmjMax)
        self.horizontalLayout_36.addLayout(self.horizontalLayout_34)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_36.addItem(spacerItem9)
        self.verticalLayout_3.addLayout(self.horizontalLayout_36)
        self.horizontalLayout_59 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_59.setObjectName("horizontalLayout_59")
        self.verticalLayout_3.addLayout(self.horizontalLayout_59)
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.label_34 = QtWidgets.QLabel(self.groupBox_5)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_39.addWidget(self.label_34)
        self.spnTmpMoy = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.spnTmpMoy.setDecimals(1)
        self.spnTmpMoy.setMaximum(99.0)
        self.spnTmpMoy.setObjectName("spnTmpMoy")
        self.horizontalLayout_39.addWidget(self.spnTmpMoy)
        self.label = QtWidgets.QLabel(self.groupBox_5)
        self.label.setObjectName("label")
        self.horizontalLayout_39.addWidget(self.label)
        self.spnTm30jMax = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.spnTm30jMax.setDecimals(1)
        self.spnTm30jMax.setMaximum(99.0)
        self.spnTm30jMax.setObjectName("spnTm30jMax")
        self.horizontalLayout_39.addWidget(self.spnTm30jMax)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_39.addItem(spacerItem10)
        self.verticalLayout_3.addLayout(self.horizontalLayout_39)
        self.horizontalLayout_62 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_62.setObjectName("horizontalLayout_62")
        self.label_49 = QtWidgets.QLabel(self.groupBox_5)
        self.label_49.setObjectName("label_49")
        self.horizontalLayout_62.addWidget(self.label_49)
        self.spnNbjTmj4_19 = QtWidgets.QSpinBox(self.groupBox_5)
        self.spnNbjTmj4_19.setMaximum(999)
        self.spnNbjTmj4_19.setObjectName("spnNbjTmj4_19")
        self.horizontalLayout_62.addWidget(self.spnNbjTmj4_19)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_62.addItem(spacerItem11)
        self.verticalLayout_3.addLayout(self.horizontalLayout_62)
        self.horizontalLayout_40 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.label_35 = QtWidgets.QLabel(self.groupBox_5)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_40.addWidget(self.label_35)
        self.spnTmj4_19 = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.spnTmj4_19.setDecimals(1)
        self.spnTmj4_19.setObjectName("spnTmj4_19")
        self.horizontalLayout_40.addWidget(self.spnTmj4_19)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_40.addItem(spacerItem12)
        self.verticalLayout_3.addLayout(self.horizontalLayout_40)
        self.horizontalLayout_41 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        self.label_36 = QtWidgets.QLabel(self.groupBox_5)
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_41.addWidget(self.label_36)
        self.spnTmjInf4 = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.spnTmjInf4.setDecimals(1)
        self.spnTmjInf4.setObjectName("spnTmjInf4")
        self.horizontalLayout_41.addWidget(self.spnTmjInf4)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_41.addItem(spacerItem13)
        self.verticalLayout_3.addLayout(self.horizontalLayout_41)
        self.horizontalLayout_42 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_42.setObjectName("horizontalLayout_42")
        self.label_37 = QtWidgets.QLabel(self.groupBox_5)
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_42.addWidget(self.label_37)
        self.spnTmjSup19 = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.spnTmjSup19.setDecimals(1)
        self.spnTmjSup19.setObjectName("spnTmjSup19")
        self.horizontalLayout_42.addWidget(self.spnTmjSup19)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_42.addItem(spacerItem14)
        self.verticalLayout_3.addLayout(self.horizontalLayout_42)
        self.horizontalLayout_43 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        self.label_38 = QtWidgets.QLabel(self.groupBox_5)
        self.label_38.setObjectName("label_38")
        self.horizontalLayout_43.addWidget(self.label_38)
        self.spnCsfSup19 = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.spnCsfSup19.setDecimals(1)
        self.spnCsfSup19.setMaximum(9999.0)
        self.spnCsfSup19.setObjectName("spnCsfSup19")
        self.horizontalLayout_43.addWidget(self.spnCsfSup19)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_43.addItem(spacerItem15)
        self.verticalLayout_3.addLayout(self.horizontalLayout_43)
        self.horizontalLayout_44 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_44.setObjectName("horizontalLayout_44")
        self.label_31 = QtWidgets.QLabel(self.groupBox_5)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_44.addWidget(self.label_31)
        self.spnCsfSupeg25 = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.spnCsfSupeg25.setDecimals(1)
        self.spnCsfSupeg25.setMaximum(9999.0)
        self.spnCsfSupeg25.setObjectName("spnCsfSupeg25")
        self.horizontalLayout_44.addWidget(self.spnCsfSupeg25)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_44.addItem(spacerItem16)
        self.verticalLayout_3.addLayout(self.horizontalLayout_44)
        self.horizontalLayout_57 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_57.setObjectName("horizontalLayout_57")
        self.label_50 = QtWidgets.QLabel(self.groupBox_5)
        self.label_50.setObjectName("label_50")
        self.horizontalLayout_57.addWidget(self.label_50)
        self.spnCsfSupeg15 = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.spnCsfSupeg15.setDecimals(1)
        self.spnCsfSupeg15.setMaximum(9999.0)
        self.spnCsfSupeg15.setObjectName("spnCsfSupeg15")
        self.horizontalLayout_57.addWidget(self.spnCsfSupeg15)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_57.addItem(spacerItem17)
        self.verticalLayout_3.addLayout(self.horizontalLayout_57)
        self.horizontalLayout_60 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_60.setObjectName("horizontalLayout_60")
        self.horizontalLayout_45 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_45.setObjectName("horizontalLayout_45")
        self.label_39 = QtWidgets.QLabel(self.groupBox_5)
        self.label_39.setObjectName("label_39")
        self.horizontalLayout_45.addWidget(self.label_39)
        self.datePonte = QtWidgets.QDateEdit(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.datePonte.sizePolicy().hasHeightForWidth())
        self.datePonte.setSizePolicy(sizePolicy)
        self.datePonte.setCalendarPopup(True)
        self.datePonte.setObjectName("datePonte")
        self.horizontalLayout_45.addWidget(self.datePonte)
        self.horizontalLayout_60.addLayout(self.horizontalLayout_45)
        self.horizontalLayout_46 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_46.setObjectName("horizontalLayout_46")
        self.label_40 = QtWidgets.QLabel(self.groupBox_5)
        self.label_40.setObjectName("label_40")
        self.horizontalLayout_46.addWidget(self.label_40)
        self.spnIncubation = QtWidgets.QSpinBox(self.groupBox_5)
        self.spnIncubation.setMaximum(999)
        self.spnIncubation.setObjectName("spnIncubation")
        self.horizontalLayout_46.addWidget(self.spnIncubation)
        self.horizontalLayout_60.addLayout(self.horizontalLayout_46)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_60.addItem(spacerItem18)
        self.verticalLayout_3.addLayout(self.horizontalLayout_60)
        self.horizontalLayout_61 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_61.setObjectName("horizontalLayout_61")
        self.horizontalLayout_47 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_47.setObjectName("horizontalLayout_47")
        self.label_41 = QtWidgets.QLabel(self.groupBox_5)
        self.label_41.setObjectName("label_41")
        self.horizontalLayout_47.addWidget(self.label_41)
        self.dateEclosion = QtWidgets.QDateEdit(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateEclosion.sizePolicy().hasHeightForWidth())
        self.dateEclosion.setSizePolicy(sizePolicy)
        self.dateEclosion.setCalendarPopup(True)
        self.dateEclosion.setObjectName("dateEclosion")
        self.horizontalLayout_47.addWidget(self.dateEclosion)
        self.horizontalLayout_61.addLayout(self.horizontalLayout_47)
        self.horizontalLayout_48 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_48.setObjectName("horizontalLayout_48")
        self.label_42 = QtWidgets.QLabel(self.groupBox_5)
        self.label_42.setObjectName("label_42")
        self.horizontalLayout_48.addWidget(self.label_42)
        self.spnResorption = QtWidgets.QSpinBox(self.groupBox_5)
        self.spnResorption.setMaximum(999)
        self.spnResorption.setObjectName("spnResorption")
        self.horizontalLayout_48.addWidget(self.spnResorption)
        self.horizontalLayout_61.addLayout(self.horizontalLayout_48)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_61.addItem(spacerItem19)
        self.verticalLayout_3.addLayout(self.horizontalLayout_61)
        self.horizontalLayout_49 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_49.setObjectName("horizontalLayout_49")
        self.label_43 = QtWidgets.QLabel(self.groupBox_5)
        self.label_43.setObjectName("label_43")
        self.horizontalLayout_49.addWidget(self.label_43)
        self.dateEmergence = QtWidgets.QDateEdit(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateEmergence.sizePolicy().hasHeightForWidth())
        self.dateEmergence.setSizePolicy(sizePolicy)
        self.dateEmergence.setCalendarPopup(True)
        self.dateEmergence.setObjectName("dateEmergence")
        self.horizontalLayout_49.addWidget(self.dateEmergence)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_49.addItem(spacerItem20)
        self.verticalLayout_3.addLayout(self.horizontalLayout_49)
        self.horizontalLayout_50 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_50.setObjectName("horizontalLayout_50")
        self.label_46 = QtWidgets.QLabel(self.groupBox_5)
        self.label_46.setObjectName("label_46")
        self.horizontalLayout_50.addWidget(self.label_46)
        self.spnNbjPel = QtWidgets.QSpinBox(self.groupBox_5)
        self.spnNbjPel.setMaximum(999)
        self.spnNbjPel.setObjectName("spnNbjPel")
        self.horizontalLayout_50.addWidget(self.spnNbjPel)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_50.addItem(spacerItem21)
        self.verticalLayout_3.addLayout(self.horizontalLayout_50)
        self.horizontalLayout_51 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_51.setObjectName("horizontalLayout_51")
        self.label_45 = QtWidgets.QLabel(self.groupBox_5)
        self.label_45.setObjectName("label_45")
        self.horizontalLayout_51.addWidget(self.label_45)
        self.spnSup15pel = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.spnSup15pel.setDecimals(1)
        self.spnSup15pel.setMaximum(9999.0)
        self.spnSup15pel.setObjectName("spnSup15pel")
        self.horizontalLayout_51.addWidget(self.spnSup15pel)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_51.addItem(spacerItem22)
        self.verticalLayout_3.addLayout(self.horizontalLayout_51)
        self.horizontalLayout_52 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_52.setObjectName("horizontalLayout_52")
        self.label_44 = QtWidgets.QLabel(self.groupBox_5)
        self.label_44.setAlignment(QtCore.Qt.AlignCenter)
        self.label_44.setObjectName("label_44")
        self.horizontalLayout_52.addWidget(self.label_44)
        self.spnCsfSup15pel = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.spnCsfSup15pel.setDecimals(1)
        self.spnCsfSup15pel.setMaximum(9999.0)
        self.spnCsfSup15pel.setObjectName("spnCsfSup15pel")
        self.horizontalLayout_52.addWidget(self.spnCsfSup15pel)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_52.addItem(spacerItem23)
        self.verticalLayout_3.addLayout(self.horizontalLayout_52)
        self.horizontalLayout_53 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_53.setObjectName("horizontalLayout_53")
        self.label_47 = QtWidgets.QLabel(self.groupBox_5)
        self.label_47.setObjectName("label_47")
        self.horizontalLayout_53.addWidget(self.label_47)
        self.spnInf1_5pel = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.spnInf1_5pel.setDecimals(1)
        self.spnInf1_5pel.setMaximum(9999.0)
        self.spnInf1_5pel.setObjectName("spnInf1_5pel")
        self.horizontalLayout_53.addWidget(self.spnInf1_5pel)
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_53.addItem(spacerItem24)
        self.verticalLayout_3.addLayout(self.horizontalLayout_53)
        self.horizontalLayout_54 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_54.setObjectName("horizontalLayout_54")
        self.label_48 = QtWidgets.QLabel(self.groupBox_5)
        self.label_48.setObjectName("label_48")
        self.horizontalLayout_54.addWidget(self.label_48)
        self.spnCsfInf1_5pel = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.spnCsfInf1_5pel.setDecimals(1)
        self.spnCsfInf1_5pel.setMaximum(9999.0)
        self.spnCsfInf1_5pel.setObjectName("spnCsfInf1_5pel")
        self.horizontalLayout_54.addWidget(self.spnCsfInf1_5pel)
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_54.addItem(spacerItem25)
        self.verticalLayout_3.addLayout(self.horizontalLayout_54)
        self.verticalLayout_6.addWidget(self.groupBox_5)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_55 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_55.setObjectName("horizontalLayout_55")
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.btnPrec = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnPrec.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btnPrec.setObjectName("btnPrec")
        self.horizontalLayout_37.addWidget(self.btnPrec)
        self.btnPremier = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnPremier.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btnPremier.setObjectName("btnPremier")
        self.horizontalLayout_37.addWidget(self.btnPremier)
        self.btnDernier = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnDernier.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btnDernier.setObjectName("btnDernier")
        self.horizontalLayout_37.addWidget(self.btnDernier)
        self.btnSuiv = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnSuiv.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btnSuiv.setObjectName("btnSuiv")
        self.horizontalLayout_37.addWidget(self.btnSuiv)
        self.horizontalLayout_55.addLayout(self.horizontalLayout_37)
        self.horizontalLayout_56 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_56.setObjectName("horizontalLayout_56")
        self.btnZoom = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnZoom.setEnabled(True)
        self.btnZoom.setMinimumSize(QtCore.QSize(50, 36))
        self.btnZoom.setMaximumSize(QtCore.QSize(100, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/icons/zoom.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnZoom.setIcon(icon)
        self.btnZoom.setObjectName("btnZoom")
        self.horizontalLayout_56.addWidget(self.btnZoom)
        self.btnSelection = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnSelection.setEnabled(True)
        self.btnSelection.setMinimumSize(QtCore.QSize(50, 36))
        self.btnSelection.setMaximumSize(QtCore.QSize(100, 16777215))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/icons/select.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSelection.setIcon(icon1)
        self.btnSelection.setObjectName("btnSelection")
        self.horizontalLayout_56.addWidget(self.btnSelection)
        self.horizontalLayout_55.addLayout(self.horizontalLayout_56)
        spacerItem26 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_55.addItem(spacerItem26)
        self.verticalLayout_4.addLayout(self.horizontalLayout_55)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.btnNouveau = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.btnNouveau.setFont(font)
        self.btnNouveau.setStyleSheet("color: rgb(0, 170, 0);")
        self.btnNouveau.setObjectName("btnNouveau")
        self.horizontalLayout_24.addWidget(self.btnNouveau)
        self.btnModif = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.btnModif.setFont(font)
        self.btnModif.setStyleSheet("color: rgb(85, 0, 255);")
        self.btnModif.setObjectName("btnModif")
        self.horizontalLayout_24.addWidget(self.btnModif)
        self.btnSupprimer = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.btnSupprimer.setFont(font)
        self.btnSupprimer.setStyleSheet("color: rgb(231, 0, 0);")
        self.btnSupprimer.setObjectName("btnSupprimer")
        self.horizontalLayout_24.addWidget(self.btnSupprimer)
        self.btnEnregistrer = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnEnregistrer.setObjectName("btnEnregistrer")
        self.horizontalLayout_24.addWidget(self.btnEnregistrer)
        self.btnAnnuler = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnAnnuler.setObjectName("btnAnnuler")
        self.horizontalLayout_24.addWidget(self.btnAnnuler)
        self.verticalLayout_4.addLayout(self.horizontalLayout_24)
        self.verticalLayout_6.addLayout(self.verticalLayout_4)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        dwcThermiMainForm.setWidget(self.dwc_thermi_form)

        self.retranslateUi(dwcThermiMainForm)
        QtCore.QMetaObject.connectSlotsByName(dwcThermiMainForm)

    def retranslateUi(self, dwcThermiMainForm):
        _translate = QtCore.QCoreApplication.translate
        dwcThermiMainForm.setWindowTitle(_translate("dwcThermiMainForm", "Gedopi - Suivi thermique"))
        self.btnFiltreCartoManuel.setText(_translate("dwcThermiMainForm", "Filtre carto manuel"))
        self.chkFiltreCartoAuto.setText(_translate("dwcThermiMainForm", "filtre carto automatique"))
        self.btnFiltreAttributaire.setText(_translate("dwcThermiMainForm", "Filtre attributaire"))
        self.btnDeleteFiltrage.setText(_translate("dwcThermiMainForm", "Suppression filtrage"))
        self.chkVerrouAuto.setText(_translate("dwcThermiMainForm", "* Verrouillage des d\'import du CSV"))
        self.chkVerrouModif.setText(_translate("dwcThermiMainForm", "Verrouillage modification"))
        self.groupBox_2.setTitle(_translate("dwcThermiMainForm", "Station"))
        self.lbl_commune.setText(_translate("dwcThermiMainForm", "Rivière :"))
        self.btnStation.setText(_translate("dwcThermiMainForm", "Fiche complète"))
        self.lbl_section.setText(_translate("dwcThermiMainForm", "<html><head/><body><p>Station <span style=\" font-size:7pt;\">(ID ; Nom)</span> :</p></body></html>"))
        self.groupBox_4.setTitle(_translate("dwcThermiMainForm", "Information sur le suivi"))
        self.btnCoordonnee.setText(_translate("dwcThermiMainForm", "Placement suivi"))
        self.label_19.setText(_translate("dwcThermiMainForm", "Code opération :"))
        self.label_21.setText(_translate("dwcThermiMainForm", "* Date début :"))
        self.label_20.setText(_translate("dwcThermiMainForm", "* Date fin :"))
        self.label_22.setText(_translate("dwcThermiMainForm", "* Durée (jours):"))
        self.label_28.setText(_translate("dwcThermiMainForm", "Maître(s) d\'ouvrage :"))
        self.btnAjoutMoa.setText(_translate("dwcThermiMainForm", "+"))
        self.btnSuppMoa.setText(_translate("dwcThermiMainForm", "-"))
        self.btnExcel.setText(_translate("dwcThermiMainForm", "Fiche Externe"))
        self.btnAjoutFiche.setText(_translate("dwcThermiMainForm", "Lier fiche"))
        self.btnRetraitFiche.setText(_translate("dwcThermiMainForm", "Délier fiche"))
        self.groupBox_5.setTitle(_translate("dwcThermiMainForm", "Résultats"))
        self.btnImpCsv.setText(_translate("dwcThermiMainForm", "Import CSV"))
        self.label_23.setText(_translate("dwcThermiMainForm", "* T°C minimale instantanée :"))
        self.label_25.setText(_translate("dwcThermiMainForm", "* T°C maximale instantanée :"))
        self.label_26.setText(_translate("dwcThermiMainForm", "<html><head/><body><p>* Amplitude thermique journalière maximale :</p></body></html>"))
        self.label_27.setText(_translate("dwcThermiMainForm", "* Date :"))
        self.label_32.setText(_translate("dwcThermiMainForm", "* T°C moyenne journalière minimale :"))
        self.label_33.setText(_translate("dwcThermiMainForm", "* T°C moy journalière maximale :"))
        self.label_34.setText(_translate("dwcThermiMainForm", "* T°C moyenne :"))
        self.label.setText(_translate("dwcThermiMainForm", "* T°C moyenne des 30j. consécutifs les + chauds :"))
        self.label_49.setText(_translate("dwcThermiMainForm", "* Nbre total de jours où T°C moy. est > 4°C et < 19 °C :"))
        self.label_35.setText(_translate("dwcThermiMainForm", "* % de jours où T°C moy. est > 4°C et < 19 °C :"))
        self.label_36.setText(_translate("dwcThermiMainForm", "* % de jours où T°C moy. est < 4°C :"))
        self.label_37.setText(_translate("dwcThermiMainForm", "* % de jours où T°C moy. est > 19°C :"))
        self.label_38.setText(_translate("dwcThermiMainForm", "* Nbre d\'heures max. consécutives où T°C > 19 °C :"))
        self.label_31.setText(_translate("dwcThermiMainForm", "* Nbre d\'heures max.consécutives où T°C >= 25 °C :"))
        self.label_50.setText(_translate("dwcThermiMainForm", "* Nbre d\'heures max.consécutives où T°C >= 15 °C :"))
        self.label_39.setText(_translate("dwcThermiMainForm", "* Date médiane de ponte :"))
        self.label_40.setText(_translate("dwcThermiMainForm", "* Nbre de jour d\'incubation :"))
        self.label_41.setText(_translate("dwcThermiMainForm", "* Date médiane d\'éclosion :"))
        self.label_42.setText(_translate("dwcThermiMainForm", "* Nbre de jour de résorption :"))
        self.label_43.setText(_translate("dwcThermiMainForm", "* Date médiane d\'émergence :"))
        self.label_46.setText(_translate("dwcThermiMainForm", "* Durée phase de vie embryo-larvaire (PEL en jours) :"))
        self.label_45.setText(_translate("dwcThermiMainForm", "* Nbre heures totale où T°C > 15 °C (PEL) :"))
        self.label_44.setText(_translate("dwcThermiMainForm", "<html><head/><body><p>* Nbre heures max. consécutives pendant PEL<br/>T°C instantanées restent &gt; 15°C :</p></body></html>"))
        self.label_47.setText(_translate("dwcThermiMainForm", "* Nbre heures totale où T°C < 1,5 °C :"))
        self.label_48.setText(_translate("dwcThermiMainForm", "<html><head/><body><p align=\"center\">* Nbre heures max. consécutives pendant PEL<br/>T°C instantanées restent &lt;1,5 °C :</p></body></html>"))
        self.btnPrec.setText(_translate("dwcThermiMainForm", "<"))
        self.btnPremier.setText(_translate("dwcThermiMainForm", "<<"))
        self.btnDernier.setText(_translate("dwcThermiMainForm", ">>"))
        self.btnSuiv.setText(_translate("dwcThermiMainForm", ">"))
        self.btnZoom.setToolTip(_translate("dwcThermiMainForm", "Zoomer sur l\'objet"))
        self.btnSelection.setToolTip(_translate("dwcThermiMainForm", "Sélectionner l\'objet"))
        self.btnNouveau.setText(_translate("dwcThermiMainForm", "Nouveau"))
        self.btnModif.setText(_translate("dwcThermiMainForm", "Enreg. Modif"))
        self.btnSupprimer.setText(_translate("dwcThermiMainForm", "Supprimer"))
        self.btnEnregistrer.setText(_translate("dwcThermiMainForm", "Enregistrer"))
        self.btnAnnuler.setText(_translate("dwcThermiMainForm", "Abandonner"))

import ressourceGedopi_rc
