# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms\opeStationForm.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dlgStationForm(object):
    def setupUi(self, dlgStationForm):
        dlgStationForm.setObjectName("dlgStationForm")
        dlgStationForm.resize(726, 404)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(dlgStationForm)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.scrollArea = QtWidgets.QScrollArea(dlgStationForm)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -16, 689, 400))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.leId = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leId.sizePolicy().hasHeightForWidth())
        self.leId.setSizePolicy(sizePolicy)
        self.leId.setMaximumSize(QtCore.QSize(50, 16777215))
        self.leId.setAlignment(QtCore.Qt.AlignCenter)
        self.leId.setObjectName("leId")
        self.horizontalLayout.addWidget(self.leId)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_18.addWidget(self.label_6)
        self.leNom = QtWidgets.QLineEdit(self.groupBox)
        self.leNom.setAlignment(QtCore.Qt.AlignCenter)
        self.leNom.setObjectName("leNom")
        self.horizontalLayout_18.addWidget(self.leNom)
        self.verticalLayout_3.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.leAltitude = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leAltitude.sizePolicy().hasHeightForWidth())
        self.leAltitude.setSizePolicy(sizePolicy)
        self.leAltitude.setMaximumSize(QtCore.QSize(50, 16777215))
        self.leAltitude.setAlignment(QtCore.Qt.AlignCenter)
        self.leAltitude.setObjectName("leAltitude")
        self.horizontalLayout_2.addWidget(self.leAltitude)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.leX = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leX.sizePolicy().hasHeightForWidth())
        self.leX.setSizePolicy(sizePolicy)
        self.leX.setMaximumSize(QtCore.QSize(80, 16777215))
        self.leX.setAlignment(QtCore.Qt.AlignCenter)
        self.leX.setObjectName("leX")
        self.horizontalLayout_4.addWidget(self.leX)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.leY = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leY.sizePolicy().hasHeightForWidth())
        self.leY.setSizePolicy(sizePolicy)
        self.leY.setMaximumSize(QtCore.QSize(80, 16777215))
        self.leY.setAlignment(QtCore.Qt.AlignCenter)
        self.leY.setObjectName("leY")
        self.horizontalLayout_3.addWidget(self.leY)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.lePdpg = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lePdpg.sizePolicy().hasHeightForWidth())
        self.lePdpg.setSizePolicy(sizePolicy)
        self.lePdpg.setAlignment(QtCore.Qt.AlignCenter)
        self.lePdpg.setObjectName("lePdpg")
        self.horizontalLayout_7.addWidget(self.lePdpg)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.leAappma = QtWidgets.QLineEdit(self.groupBox)
        self.leAappma.setAlignment(QtCore.Qt.AlignCenter)
        self.leAappma.setObjectName("leAappma")
        self.horizontalLayout_8.addWidget(self.leAappma)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_10.addWidget(self.label_11)
        self.leDistance = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leDistance.sizePolicy().hasHeightForWidth())
        self.leDistance.setSizePolicy(sizePolicy)
        self.leDistance.setMaximumSize(QtCore.QSize(50, 16777215))
        self.leDistance.setAlignment(QtCore.Qt.AlignCenter)
        self.leDistance.setObjectName("leDistance")
        self.horizontalLayout_10.addWidget(self.leDistance)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_11.addWidget(self.label_12)
        self.leSurface = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leSurface.sizePolicy().hasHeightForWidth())
        self.leSurface.setSizePolicy(sizePolicy)
        self.leSurface.setMaximumSize(QtCore.QSize(70, 16777215))
        self.leSurface.setAlignment(QtCore.Qt.AlignCenter)
        self.leSurface.setObjectName("leSurface")
        self.horizontalLayout_11.addWidget(self.leSurface)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem7)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem8)
        self.horizontalLayout_9.addLayout(self.verticalLayout_3)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lePhoto = QtWidgets.QLineEdit(self.groupBox_2)
        self.lePhoto.setObjectName("lePhoto")
        self.verticalLayout_2.addWidget(self.lePhoto)
        self.lblPhoto = QtWidgets.QLabel(self.groupBox_2)
        self.lblPhoto.setScaledContents(True)
        self.lblPhoto.setAlignment(QtCore.Qt.AlignCenter)
        self.lblPhoto.setObjectName("lblPhoto")
        self.verticalLayout_2.addWidget(self.lblPhoto)
        self.horizontalLayout_9.addWidget(self.groupBox_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.label_28 = QtWidgets.QLabel(self.groupBox)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_37.addWidget(self.label_28)
        self.leMeau = QtWidgets.QLineEdit(self.groupBox)
        self.leMeau.setAlignment(QtCore.Qt.AlignCenter)
        self.leMeau.setObjectName("leMeau")
        self.horizontalLayout_37.addWidget(self.leMeau)
        self.verticalLayout_4.addLayout(self.horizontalLayout_37)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.leRiviere = QtWidgets.QLineEdit(self.groupBox)
        self.leRiviere.setAlignment(QtCore.Qt.AlignCenter)
        self.leRiviere.setObjectName("leRiviere")
        self.horizontalLayout_5.addWidget(self.leRiviere)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.verticalLayout_5.addWidget(self.groupBox)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem9)
        self.btnFermer = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnFermer.sizePolicy().hasHeightForWidth())
        self.btnFermer.setSizePolicy(sizePolicy)
        self.btnFermer.setMaximumSize(QtCore.QSize(100, 16777215))
        self.btnFermer.setObjectName("btnFermer")
        self.horizontalLayout_6.addWidget(self.btnFermer)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem10)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_6.addWidget(self.scrollArea)

        self.retranslateUi(dlgStationForm)
        QtCore.QMetaObject.connectSlotsByName(dlgStationForm)

    def retranslateUi(self, dlgStationForm):
        _translate = QtCore.QCoreApplication.translate
        dlgStationForm.setWindowTitle(_translate("dlgStationForm", "Fiche station"))
        self.groupBox.setTitle(_translate("dlgStationForm", "Station"))
        self.label.setText(_translate("dlgStationForm", "ID :"))
        self.label_6.setText(_translate("dlgStationForm", "Nom : "))
        self.label_4.setText(_translate("dlgStationForm", "Altitude (m) :"))
        self.label_2.setText(_translate("dlgStationForm", "Coord X (Lambert-93) :"))
        self.label_3.setText(_translate("dlgStationForm", "Coord Y (Lambert-93) :"))
        self.label_7.setText(_translate("dlgStationForm", "Contexte PDPG :"))
        self.label_8.setText(_translate("dlgStationForm", "AAPPMA :"))
        self.label_11.setText(_translate("dlgStationForm", "Distance à la source (km) :"))
        self.label_12.setText(_translate("dlgStationForm", "Surface du bassin versant amont (km²) :"))
        self.groupBox_2.setTitle(_translate("dlgStationForm", "Photo de la station :"))
        self.label_28.setText(_translate("dlgStationForm", "Masse eau :"))
        self.label_5.setText(_translate("dlgStationForm", "Rivière :"))
        self.btnFermer.setText(_translate("dlgStationForm", "Fermer"))

import ressourceGedopi_rc
