# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms\opeSuiviRechercheForm.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dlgSuiviRechercheForm(object):
    def setupUi(self, dlgSuiviRechercheForm):
        dlgSuiviRechercheForm.setObjectName("dlgSuiviRechercheForm")
        dlgSuiviRechercheForm.resize(375, 542)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(dlgSuiviRechercheForm)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(dlgSuiviRechercheForm)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 355, 522))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.btnEt = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnEt.sizePolicy().hasHeightForWidth())
        self.btnEt.setSizePolicy(sizePolicy)
        self.btnEt.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btnEt.setObjectName("btnEt")
        self.horizontalLayout_7.addWidget(self.btnEt)
        self.btnOu = QtWidgets.QPushButton(self.groupBox)
        self.btnOu.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btnOu.setObjectName("btnOu")
        self.horizontalLayout_7.addWidget(self.btnOu)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.leCodeOpe = QtWidgets.QLineEdit(self.groupBox)
        self.leCodeOpe.setMinimumSize(QtCore.QSize(150, 0))
        self.leCodeOpe.setObjectName("leCodeOpe")
        self.horizontalLayout_8.addWidget(self.leCodeOpe)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.btnCode = QtWidgets.QPushButton(self.groupBox)
        self.btnCode.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btnCode.setObjectName("btnCode")
        self.horizontalLayout_8.addWidget(self.btnCode)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.spnId = QtWidgets.QSpinBox(self.groupBox)
        self.spnId.setMaximum(100000)
        self.spnId.setObjectName("spnId")
        self.horizontalLayout.addWidget(self.spnId)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.btnId = QtWidgets.QPushButton(self.groupBox)
        self.btnId.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btnId.setObjectName("btnId")
        self.horizontalLayout.addWidget(self.btnId)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.dateDebut = QtWidgets.QDateEdit(self.groupBox)
        self.dateDebut.setObjectName("dateDebut")
        self.horizontalLayout_2.addWidget(self.dateDebut)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.btnDebut = QtWidgets.QPushButton(self.groupBox)
        self.btnDebut.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btnDebut.setObjectName("btnDebut")
        self.horizontalLayout_2.addWidget(self.btnDebut)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.dateFin = QtWidgets.QDateEdit(self.groupBox)
        self.dateFin.setObjectName("dateFin")
        self.horizontalLayout_6.addWidget(self.dateFin)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.btnFin = QtWidgets.QPushButton(self.groupBox)
        self.btnFin.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btnFin.setObjectName("btnFin")
        self.horizontalLayout_6.addWidget(self.btnFin)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.cmbRiviere = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbRiviere.sizePolicy().hasHeightForWidth())
        self.cmbRiviere.setSizePolicy(sizePolicy)
        self.cmbRiviere.setObjectName("cmbRiviere")
        self.horizontalLayout_3.addWidget(self.cmbRiviere)
        self.btnRiviere = QtWidgets.QPushButton(self.groupBox)
        self.btnRiviere.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btnRiviere.setObjectName("btnRiviere")
        self.horizontalLayout_3.addWidget(self.btnRiviere)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.cmbPdpg = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbPdpg.sizePolicy().hasHeightForWidth())
        self.cmbPdpg.setSizePolicy(sizePolicy)
        self.cmbPdpg.setObjectName("cmbPdpg")
        self.horizontalLayout_4.addWidget(self.cmbPdpg)
        self.btnPdpg = QtWidgets.QPushButton(self.groupBox)
        self.btnPdpg.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btnPdpg.setObjectName("btnPdpg")
        self.horizontalLayout_4.addWidget(self.btnPdpg)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.cmbAappma = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbAappma.sizePolicy().hasHeightForWidth())
        self.cmbAappma.setSizePolicy(sizePolicy)
        self.cmbAappma.setObjectName("cmbAappma")
        self.horizontalLayout_5.addWidget(self.cmbAappma)
        self.btnAappma = QtWidgets.QPushButton(self.groupBox)
        self.btnAappma.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btnAappma.setObjectName("btnAappma")
        self.horizontalLayout_5.addWidget(self.btnAappma)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_14.addWidget(self.label_13)
        self.cmbMeau = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbMeau.sizePolicy().hasHeightForWidth())
        self.cmbMeau.setSizePolicy(sizePolicy)
        self.cmbMeau.setObjectName("cmbMeau")
        self.horizontalLayout_14.addWidget(self.cmbMeau)
        self.btnMeau = QtWidgets.QPushButton(self.groupBox)
        self.btnMeau.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btnMeau.setObjectName("btnMeau")
        self.horizontalLayout_14.addWidget(self.btnMeau)
        self.verticalLayout.addLayout(self.horizontalLayout_14)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.groupBox_4 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.txtSql = QtWidgets.QTextEdit(self.groupBox_4)
        self.txtSql.setMaximumSize(QtCore.QSize(16777215, 100))
        self.txtSql.setObjectName("txtSql")
        self.verticalLayout_3.addWidget(self.txtSql)
        self.verticalLayout_4.addWidget(self.groupBox_4)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.btnPrevisualiser = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnPrevisualiser.setObjectName("btnPrevisualiser")
        self.horizontalLayout_11.addWidget(self.btnPrevisualiser)
        self.btnExec = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnExec.setObjectName("btnExec")
        self.horizontalLayout_11.addWidget(self.btnExec)
        self.btnRaz = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnRaz.setObjectName("btnRaz")
        self.horizontalLayout_11.addWidget(self.btnRaz)
        self.btnAnnuler = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnAnnuler.setObjectName("btnAnnuler")
        self.horizontalLayout_11.addWidget(self.btnAnnuler)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)

        self.retranslateUi(dlgSuiviRechercheForm)
        QtCore.QMetaObject.connectSlotsByName(dlgSuiviRechercheForm)

    def retranslateUi(self, dlgSuiviRechercheForm):
        _translate = QtCore.QCoreApplication.translate
        dlgSuiviRechercheForm.setWindowTitle(_translate("dlgSuiviRechercheForm", "Recherche de suivi(s) thermique"))
        self.groupBox.setTitle(_translate("dlgSuiviRechercheForm", "Critère(s) :"))
        self.btnEt.setText(_translate("dlgSuiviRechercheForm", "Et"))
        self.btnOu.setText(_translate("dlgSuiviRechercheForm", "Ou"))
        self.label_8.setText(_translate("dlgSuiviRechercheForm", "Code Opération :"))
        self.btnCode.setText(_translate("dlgSuiviRechercheForm", "Ajouter"))
        self.label.setText(_translate("dlgSuiviRechercheForm", "ID :"))
        self.btnId.setText(_translate("dlgSuiviRechercheForm", "Ajouter"))
        self.label_2.setText(_translate("dlgSuiviRechercheForm", "Année début :"))
        self.dateDebut.setDisplayFormat(_translate("dlgSuiviRechercheForm", "yyyy"))
        self.btnDebut.setText(_translate("dlgSuiviRechercheForm", "Ajouter"))
        self.label_7.setText(_translate("dlgSuiviRechercheForm", "Année fin :"))
        self.dateFin.setDisplayFormat(_translate("dlgSuiviRechercheForm", "yyyy"))
        self.btnFin.setText(_translate("dlgSuiviRechercheForm", "Ajouter"))
        self.label_3.setText(_translate("dlgSuiviRechercheForm", "Rivière :"))
        self.btnRiviere.setText(_translate("dlgSuiviRechercheForm", "Ajouter"))
        self.label_4.setText(_translate("dlgSuiviRechercheForm", "Contexte PDPG :"))
        self.btnPdpg.setText(_translate("dlgSuiviRechercheForm", "Ajouter"))
        self.label_5.setText(_translate("dlgSuiviRechercheForm", "AAPPMA :"))
        self.btnAappma.setText(_translate("dlgSuiviRechercheForm", "Ajouter"))
        self.label_13.setText(_translate("dlgSuiviRechercheForm", "Masse d\'eau :"))
        self.btnMeau.setText(_translate("dlgSuiviRechercheForm", "Ajouter"))
        self.groupBox_4.setTitle(_translate("dlgSuiviRechercheForm", "Requête SQL :"))
        self.label_6.setText(_translate("dlgSuiviRechercheForm", "<html><head/><body><p align=\"justify\"><span style=\" font-size:7pt;\">Attention : les modifications dans la requête sont possibles mais peuvent faire échouer celle-ci voir endommager la base de données ! ! !</span></p></body></html>"))
        self.txtSql.setHtml(_translate("dlgSuiviRechercheForm", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p></body></html>"))
        self.btnPrevisualiser.setText(_translate("dlgSuiviRechercheForm", "Prévisualisation"))
        self.btnExec.setText(_translate("dlgSuiviRechercheForm", "Exécuter"))
        self.btnRaz.setText(_translate("dlgSuiviRechercheForm", "Réinitialiser"))
        self.btnAnnuler.setText(_translate("dlgSuiviRechercheForm", "Annuler"))

