# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms\stationForm.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dwcStationMainForm(object):
    def setupUi(self, dwcStationMainForm):
        dwcStationMainForm.setObjectName("dwcStationMainForm")
        dwcStationMainForm.resize(518, 584)
        dwcStationMainForm.setMinimumSize(QtCore.QSize(518, 415))
        self.dwc_station_form = QtWidgets.QWidget()
        self.dwc_station_form.setObjectName("dwc_station_form")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.dwc_station_form)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.scrollArea = QtWidgets.QScrollArea(self.dwc_station_form)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 491, 601))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(0, 1, 0, 1)
        self.horizontalLayout_11.setSpacing(2)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.btnFiltreCartoManuel = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnFiltreCartoManuel.setEnabled(False)
        self.btnFiltreCartoManuel.setMinimumSize(QtCore.QSize(120, 30))
        self.btnFiltreCartoManuel.setObjectName("btnFiltreCartoManuel")
        self.horizontalLayout_11.addWidget(self.btnFiltreCartoManuel)
        self.chkFiltreCartoAuto = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.chkFiltreCartoAuto.setMinimumSize(QtCore.QSize(130, 0))
        self.chkFiltreCartoAuto.setObjectName("chkFiltreCartoAuto")
        self.horizontalLayout_11.addWidget(self.chkFiltreCartoAuto)
        self.btnFiltreAttributaire = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnFiltreAttributaire.setMinimumSize(QtCore.QSize(97, 30))
        self.btnFiltreAttributaire.setObjectName("btnFiltreAttributaire")
        self.horizontalLayout_11.addWidget(self.btnFiltreAttributaire)
        self.btnDeleteFiltrage = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnDeleteFiltrage.setEnabled(False)
        self.btnDeleteFiltrage.setMinimumSize(QtCore.QSize(110, 30))
        self.btnDeleteFiltrage.setObjectName("btnDeleteFiltrage")
        self.horizontalLayout_11.addWidget(self.btnDeleteFiltrage)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_11)
        spacerItem = QtWidgets.QSpacerItem(118, 37, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.chkVerrouAuto = QtWidgets.QCheckBox(self.groupBox)
        self.chkVerrouAuto.setChecked(True)
        self.chkVerrouAuto.setObjectName("chkVerrouAuto")
        self.verticalLayout_3.addWidget(self.chkVerrouAuto)
        self.chkVerrouModif = QtWidgets.QCheckBox(self.groupBox)
        self.chkVerrouModif.setChecked(True)
        self.chkVerrouModif.setObjectName("chkVerrouModif")
        self.verticalLayout_3.addWidget(self.chkVerrouModif)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.btnCoordonnee = QtWidgets.QPushButton(self.groupBox)
        self.btnCoordonnee.setMinimumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.btnCoordonnee.setFont(font)
        self.btnCoordonnee.setStyleSheet("color: rgb(231, 0, 0)")
        self.btnCoordonnee.setObjectName("btnCoordonnee")
        self.horizontalLayout_6.addWidget(self.btnCoordonnee)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.leId = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leId.sizePolicy().hasHeightForWidth())
        self.leId.setSizePolicy(sizePolicy)
        self.leId.setMaximumSize(QtCore.QSize(50, 16777215))
        self.leId.setAlignment(QtCore.Qt.AlignCenter)
        self.leId.setObjectName("leId")
        self.horizontalLayout.addWidget(self.leId)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_18.addWidget(self.label_6)
        self.leNom = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leNom.sizePolicy().hasHeightForWidth())
        self.leNom.setSizePolicy(sizePolicy)
        self.leNom.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.leNom.setAlignment(QtCore.Qt.AlignCenter)
        self.leNom.setObjectName("leNom")
        self.horizontalLayout_18.addWidget(self.leNom)
        self.verticalLayout_3.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.spnAltitude = QtWidgets.QSpinBox(self.groupBox)
        self.spnAltitude.setMaximum(2000)
        self.spnAltitude.setObjectName("spnAltitude")
        self.horizontalLayout_2.addWidget(self.spnAltitude)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.cmbPdpg = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbPdpg.sizePolicy().hasHeightForWidth())
        self.cmbPdpg.setSizePolicy(sizePolicy)
        self.cmbPdpg.setObjectName("cmbPdpg")
        self.horizontalLayout_7.addWidget(self.cmbPdpg)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_12.addWidget(self.label_8)
        self.cmbAappma = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbAappma.sizePolicy().hasHeightForWidth())
        self.cmbAappma.setSizePolicy(sizePolicy)
        self.cmbAappma.setObjectName("cmbAappma")
        self.horizontalLayout_12.addWidget(self.cmbAappma)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.label_28 = QtWidgets.QLabel(self.groupBox)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_37.addWidget(self.label_28)
        self.cmbRiviere = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbRiviere.sizePolicy().hasHeightForWidth())
        self.cmbRiviere.setSizePolicy(sizePolicy)
        self.cmbRiviere.setMinimumSize(QtCore.QSize(150, 0))
        self.cmbRiviere.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cmbRiviere.setObjectName("cmbRiviere")
        self.horizontalLayout_37.addWidget(self.cmbRiviere)
        self.verticalLayout_3.addLayout(self.horizontalLayout_37)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem7)
        self.horizontalLayout_9.addLayout(self.verticalLayout_3)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.btnAjoutPhoto = QtWidgets.QPushButton(self.groupBox_2)
        self.btnAjoutPhoto.setMinimumSize(QtCore.QSize(70, 0))
        self.btnAjoutPhoto.setMaximumSize(QtCore.QSize(70, 20))
        self.btnAjoutPhoto.setObjectName("btnAjoutPhoto")
        self.horizontalLayout_22.addWidget(self.btnAjoutPhoto)
        self.btnRetraitPhoto = QtWidgets.QPushButton(self.groupBox_2)
        self.btnRetraitPhoto.setMinimumSize(QtCore.QSize(70, 0))
        self.btnRetraitPhoto.setMaximumSize(QtCore.QSize(70, 20))
        self.btnRetraitPhoto.setObjectName("btnRetraitPhoto")
        self.horizontalLayout_22.addWidget(self.btnRetraitPhoto)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem8)
        self.verticalLayout_8.addLayout(self.horizontalLayout_22)
        self.lePhoto = QtWidgets.QLineEdit(self.groupBox_2)
        self.lePhoto.setObjectName("lePhoto")
        self.verticalLayout_8.addWidget(self.lePhoto)
        self.verticalLayout_2.addLayout(self.verticalLayout_8)
        self.lblPhoto = QtWidgets.QLabel(self.groupBox_2)
        self.lblPhoto.setMinimumSize(QtCore.QSize(0, 0))
        self.lblPhoto.setText("")
        self.lblPhoto.setScaledContents(True)
        self.lblPhoto.setAlignment(QtCore.Qt.AlignCenter)
        self.lblPhoto.setObjectName("lblPhoto")
        self.verticalLayout_2.addWidget(self.lblPhoto)
        self.horizontalLayout_9.addWidget(self.groupBox_2)
        self.verticalLayout_7.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.spnX = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.spnX.setDecimals(3)
        self.spnX.setMaximum(999999.99)
        self.spnX.setProperty("value", 0.0)
        self.spnX.setObjectName("spnX")
        self.horizontalLayout_3.addWidget(self.spnX)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem9)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.spnY = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.spnY.setDecimals(3)
        self.spnY.setMaximum(9999999.99)
        self.spnY.setProperty("value", 0.0)
        self.spnY.setObjectName("spnY")
        self.horizontalLayout_4.addWidget(self.spnY)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem10)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_21.addLayout(self.verticalLayout)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_19.addWidget(self.label_9)
        self.spnX_L2 = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.spnX_L2.setDecimals(3)
        self.spnX_L2.setMaximum(999999.99)
        self.spnX_L2.setProperty("value", 0.0)
        self.spnX_L2.setObjectName("spnX_L2")
        self.horizontalLayout_19.addWidget(self.spnX_L2)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem11)
        self.verticalLayout_4.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_20.addWidget(self.label_10)
        self.spnY_L2 = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.spnY_L2.setDecimals(3)
        self.spnY_L2.setMaximum(9999999.99)
        self.spnY_L2.setProperty("value", 0.0)
        self.spnY_L2.setObjectName("spnY_L2")
        self.horizontalLayout_20.addWidget(self.spnY_L2)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem12)
        self.verticalLayout_4.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21.addLayout(self.verticalLayout_4)
        self.verticalLayout_7.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.cmbMeau = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbMeau.sizePolicy().hasHeightForWidth())
        self.cmbMeau.setSizePolicy(sizePolicy)
        self.cmbMeau.setObjectName("cmbMeau")
        self.horizontalLayout_5.addWidget(self.cmbMeau)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_10.addWidget(self.label_11)
        self.spnDistance = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.spnDistance.setMaximum(1000.99)
        self.spnDistance.setObjectName("spnDistance")
        self.horizontalLayout_10.addWidget(self.spnDistance)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem13)
        self.verticalLayout_7.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_17.addWidget(self.label_12)
        self.spnSurface = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.spnSurface.setDecimals(3)
        self.spnSurface.setMaximum(9999.99)
        self.spnSurface.setObjectName("spnSurface")
        self.horizontalLayout_17.addWidget(self.spnSurface)
        self.btnSurface = QtWidgets.QPushButton(self.groupBox)
        self.btnSurface.setObjectName("btnSurface")
        self.horizontalLayout_17.addWidget(self.btnSurface)
        self.btnNettoyage = QtWidgets.QPushButton(self.groupBox)
        self.btnNettoyage.setObjectName("btnNettoyage")
        self.horizontalLayout_17.addWidget(self.btnNettoyage)
        spacerItem14 = QtWidgets.QSpacerItem(14, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem14)
        self.verticalLayout_7.addLayout(self.horizontalLayout_17)
        self.verticalLayout_5.addWidget(self.groupBox)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.btnPrec = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnPrec.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btnPrec.setObjectName("btnPrec")
        self.horizontalLayout_36.addWidget(self.btnPrec)
        self.btnPremier = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnPremier.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btnPremier.setObjectName("btnPremier")
        self.horizontalLayout_36.addWidget(self.btnPremier)
        self.btnDernier = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnDernier.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btnDernier.setObjectName("btnDernier")
        self.horizontalLayout_36.addWidget(self.btnDernier)
        self.btnSuiv = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnSuiv.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btnSuiv.setObjectName("btnSuiv")
        self.horizontalLayout_36.addWidget(self.btnSuiv)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_36)
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.btnZoom = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnZoom.setMinimumSize(QtCore.QSize(50, 36))
        self.btnZoom.setMaximumSize(QtCore.QSize(100, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/icons/zoom.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnZoom.setIcon(icon)
        self.btnZoom.setObjectName("btnZoom")
        self.horizontalLayout_38.addWidget(self.btnZoom)
        self.btnSelection = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnSelection.setMinimumSize(QtCore.QSize(50, 36))
        self.btnSelection.setMaximumSize(QtCore.QSize(100, 16777215))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/icons/select.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSelection.setIcon(icon1)
        self.btnSelection.setObjectName("btnSelection")
        self.horizontalLayout_38.addWidget(self.btnSelection)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_38)
        self.horizontalLayout_15.addLayout(self.horizontalLayout_14)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem15)
        self.verticalLayout_5.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.btnNouveau = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnNouveau.setMinimumSize(QtCore.QSize(85, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.btnNouveau.setFont(font)
        self.btnNouveau.setStyleSheet("color: rgb(0, 170, 0);")
        self.btnNouveau.setObjectName("btnNouveau")
        self.horizontalLayout_23.addWidget(self.btnNouveau)
        self.btnModif = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnModif.setMinimumSize(QtCore.QSize(85, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.btnModif.setFont(font)
        self.btnModif.setStyleSheet("color: rgb(85, 0, 255);")
        self.btnModif.setObjectName("btnModif")
        self.horizontalLayout_23.addWidget(self.btnModif)
        self.btnSupprimer = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnSupprimer.setMinimumSize(QtCore.QSize(85, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.btnSupprimer.setFont(font)
        self.btnSupprimer.setStyleSheet("color: rgb(231, 0, 0);")
        self.btnSupprimer.setObjectName("btnSupprimer")
        self.horizontalLayout_23.addWidget(self.btnSupprimer)
        self.btnEnregistrer = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnEnregistrer.setMinimumSize(QtCore.QSize(85, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnEnregistrer.setFont(font)
        self.btnEnregistrer.setObjectName("btnEnregistrer")
        self.horizontalLayout_23.addWidget(self.btnEnregistrer)
        self.btnAnnuler = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnAnnuler.setMinimumSize(QtCore.QSize(85, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnAnnuler.setFont(font)
        self.btnAnnuler.setObjectName("btnAnnuler")
        self.horizontalLayout_23.addWidget(self.btnAnnuler)
        self.horizontalLayout_16.addLayout(self.horizontalLayout_23)
        spacerItem16 = QtWidgets.QSpacerItem(4, 34, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem16)
        self.verticalLayout_5.addLayout(self.horizontalLayout_16)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_6.addWidget(self.scrollArea)
        dwcStationMainForm.setWidget(self.dwc_station_form)

        self.retranslateUi(dwcStationMainForm)
        QtCore.QMetaObject.connectSlotsByName(dwcStationMainForm)

    def retranslateUi(self, dwcStationMainForm):
        _translate = QtCore.QCoreApplication.translate
        dwcStationMainForm.setWindowTitle(_translate("dwcStationMainForm", "Gedopi - Station"))
        self.btnFiltreCartoManuel.setText(_translate("dwcStationMainForm", "Filtre carto manuel"))
        self.chkFiltreCartoAuto.setText(_translate("dwcStationMainForm", "filtre carto automatique"))
        self.btnFiltreAttributaire.setText(_translate("dwcStationMainForm", "Filtre attributaire"))
        self.btnDeleteFiltrage.setText(_translate("dwcStationMainForm", "Suppression filtrage"))
        self.groupBox.setTitle(_translate("dwcStationMainForm", "Station"))
        self.chkVerrouAuto.setText(_translate("dwcStationMainForm", "* Verrouillage des champs automatiques"))
        self.chkVerrouModif.setText(_translate("dwcStationMainForm", "Verrouillage modification"))
        self.btnCoordonnee.setText(_translate("dwcStationMainForm", "Placement station"))
        self.label.setText(_translate("dwcStationMainForm", "ID :"))
        self.label_6.setText(_translate("dwcStationMainForm", "Nom : "))
        self.label_4.setText(_translate("dwcStationMainForm", "* Altitude (m) :"))
        self.label_7.setText(_translate("dwcStationMainForm", "* Contexte PDPG :"))
        self.label_8.setText(_translate("dwcStationMainForm", "* AAPPMA :"))
        self.label_28.setText(_translate("dwcStationMainForm", "* Rivière :"))
        self.groupBox_2.setTitle(_translate("dwcStationMainForm", "Photo de la station :"))
        self.btnAjoutPhoto.setText(_translate("dwcStationMainForm", "Lier photo"))
        self.btnRetraitPhoto.setText(_translate("dwcStationMainForm", "Délier photo"))
        self.label_2.setText(_translate("dwcStationMainForm", "* Coord X : Lambert-93 : "))
        self.label_3.setText(_translate("dwcStationMainForm", "* Coord Y : Lambert-93 :"))
        self.label_9.setText(_translate("dwcStationMainForm", "Lambert-II Étendu :"))
        self.label_10.setText(_translate("dwcStationMainForm", "Lambert-II Étendu :"))
        self.label_5.setText(_translate("dwcStationMainForm", "* Masse d\'eau :"))
        self.label_11.setText(_translate("dwcStationMainForm", "Distance à la source (km) :"))
        self.label_12.setText(_translate("dwcStationMainForm", "Surface du bassin amont (km²) :"))
        self.btnSurface.setText(_translate("dwcStationMainForm", "Calculer surface"))
        self.btnNettoyage.setText(_translate("dwcStationMainForm", "Vider dossier Temp"))
        self.btnPrec.setText(_translate("dwcStationMainForm", "<"))
        self.btnPremier.setText(_translate("dwcStationMainForm", "<<"))
        self.btnDernier.setText(_translate("dwcStationMainForm", ">>"))
        self.btnSuiv.setText(_translate("dwcStationMainForm", ">"))
        self.btnZoom.setToolTip(_translate("dwcStationMainForm", "Zoomer sur l\'objet"))
        self.btnSelection.setToolTip(_translate("dwcStationMainForm", "Sélectionner l\'objet"))
        self.btnNouveau.setText(_translate("dwcStationMainForm", "Nouveau"))
        self.btnModif.setText(_translate("dwcStationMainForm", "Enreg. Modif"))
        self.btnSupprimer.setText(_translate("dwcStationMainForm", "Supprimer"))
        self.btnEnregistrer.setText(_translate("dwcStationMainForm", "Enregistrer"))
        self.btnAnnuler.setText(_translate("dwcStationMainForm", "Abandonner"))

import ressourceGedopi_rc
